### ISSUE TITLE
[Feature] Story, Player Character, Graphics, Animation and Extras

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#100]
# **Description**
 
Focusing more on the character sprite and its animation, As well as designing the death and game over screen. Also focus on the display of the stamina, mana and health of the game to ensure that it matches the rest of the theme. This feature aims to iterate on what has already been created in terms of design but actually implement them into the game, this includes importing PNG files and other design elements in the game to further develop the game.

## SubFeature/component + Examples (optional)
If the ticket contains multiple components, you should explain them in more detail here.
* Character Sprite

> Still Plumber character design

* Character Animation 
> Jumping 
> Wiggling when player walking
* Death Screen + Game over screen
> Fade to Black?
* Stamina, mana, and health graphics displayed in-game
> Top left bar design
* Background or Sound Effect
> Main screen sound
> Sound for each level
> Sound Effects for footsteps + jumping
* Mana / Stamina check function in combat stats

# **Dependencies**

- [x] NPC teams character sprite dimensions.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [x] Goal 1 (Sep. 06) Basic character sprite + User Testing
- [x] Goal 2 (Sep 08)  Basic death screen and game over screen design implemented + User Testing
- [x] Goal 3 (Sep. 10)  Stamina, mana and health display graphics in the game + character animation 
- [x] Goal 4 (Sep. 12)  Implement sound effects for the screen 

**Completion Deadline:** Sep. 13(Tue)

# **Extras**
- [x] Additional sound effects
- Additional iteration on story and character concept
- Additional iteration on design concept

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- [Story, character and Design Development](https://github.com/UQdeco2800/2022-studio-2/wiki/Story%2C-Character-and-Design-Development)
- [Character and Story Concept](https://github.com/UQdeco2800/2022-studio-2/wiki/Character-and-Story-Concept)
- [Design Rule Book](https://github.com/UQdeco2800/2022-studio-2/wiki/Design-Rule-Book)
- [Testing Story and Character Sprint One](https://github.com/UQdeco2800/2022-studio-2/wiki/Testing-Story-and-Character-Sprint-One)
- [Player modifier documentation](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Modification-Framework)
- [Stamina and Mana System Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Stamina-and-Mana-System-Code-Implementation)
- [Item Lore](https://github.com/UQdeco2800/2022-studio-2/wiki/Item-Lore)

# **Members**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)
