### ISSUE TITLE
<Task> Implementation of Basic Sound

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#101]
# **Description**
**Task:** [Implementation of Basic Sounds] (#)

**Feature:** [Story, Player Character, Graphics, Animation and Extras](#100)

Two sound effects or soundtracks are implemented into the game.

## **Example**
* A ‘whoosh’ when the character runs

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Goal 1 (Sep 04) Brainstorm ideas 
- [x] Goal 2 (Sep 09) Draft ideas  
- [x] Goal 3 (Sep 10) Select sounds
- [x] Goal 4 (Sep 12) Implement sound

 
**Completion Deadline:** 
September 12th.
 
# **Documentation**
- [Name of your documentation](../wiki/path to your documentation)

# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
