### ISSUE TITLE
<Task> Character Stats Display Graphics

### ISSUE THREAD

**Issue by whyhlf** [UQdeco2800/2022-studio-2#102]
# **Description**
**Task:**  [Character Stats Display Graphics]

**Feature:** [Story, Player Character, Graphics, Animation and Extras](#100)

Give a description of the feature

Currently the stamina, health and mana is displayed as numbers and text, this is basic and doesn’t fit with the theme of the game. Hence this task aims to design, test and implement graphics for the stamina, health and mana to better display character stats.

## **Example**
Examples of what your system will do.
* Visually depict a rising and falling health bar depending on the attacks the character has received. 
* The mana and stamina bar would change according to the player’s actions and skills consumption.

# **Dependencies**
Does it rely on anything else or anyone else?
* Rely’s on `Inventory` team’s colour choice and style of display
* Rely’s on `Potions` work regarding how visually the character is 
* Rely’s on `Skills` team work on animations around how buffs and debuffs effect the statistic bar.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] (Sep.5th) Drafts done
- [x] (Sep.8th) User testing for the finalized choice of the stats display
- [x] (Sep.9th) Implementation of the new stats display into the game 
 
**Completion Deadline:** Sep.10th
 
# **Documentation**
* Coming soon.

# **Members**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
