### ISSUE TITLE
<Task> Death Screen 

### ISSUE THREAD

**Issue by aalice23** [UQdeco2800/2022-studio-2#103]
# **Description**
**Task:** [Death Screen / Loading screen] (#)

**Feature:** [Story, Player Character, Graphics, Animation and Extras](#100)

Death screen is a feature that displays a ‘Game Over’ message to inform the user and to also ask them if they want to either quit the game or restart the game. 

The loading screen is an add-on feature we've decided to include for a smoother gameplay experience. When the player passes level 1, if they want to move on to the next level, a loading screen would appear for a short period and then it will load the player into level 2. 

## **Example**
- **Minecraft Death Screen**: Transparent background with the main message ‘You Died’ displayed in the centre and buttons that prompt the player to play again or exit.  
Link: https://thenerdstash.com/wp-content/uploads/2021/08/Minecraft-Death-Screen.jpg 

# **Dependencies**
There are no other team dependencies for this task
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Goal 1 (Sep 04) Brainstorm ideas/ draft ideas
- [x] Goal 2 (Sep 09) User testing on some of the ideas confirmed 
- [x] Goal 3 (Sep 10) Finalise design ideas

Loading screens and animations for each level will be continued in the next sprint as the illustration would require more time to complete.
 
**Completion Deadline:** September 10th 
 
# **Documentation**
Current ideas:
https://frill-windflower-3a4.notion.site/Task-Ticket-Game-Over-Screen-44dedea6cd064193844cea763898b299 

# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
