### ISSUE TITLE
<Task> Basic Player Animation

### ISSUE THREAD

**Issue by IsaacGraham128** [UQdeco2800/2022-studio-2#104]
# **Description**
**Task:** [Basic Player Animation](#)

**Feature:** [Story, Player Character, Graphics, Animation and Extras](#100)

Implement the idle and movement player animations through the use of the provided LibGDX animator component. Player animation will change dynamically based on movement.

## **Example**

- When idling the player will bob up and down.
- When moving up the player sprite will have its back facing to the character

# **Dependencies**
Will need too discuss with Team 4 (Weapons) and Team 8 (Skills) to discuss their required animations and implementations of systems.
 
# **Milestones**

- [x] Remove still image render (2/09)
- [x] Figure how to play an animation (2/09)
- [x] Dynamically call specific animations based on player input (3/09)
- [x] Create basic test framework (5/09)
- [x] Create appropriate .png images and atlas files for animations (7/09)
- [x] Replace placeholder animations  (7/09)
- [x] Check with other teams regarding animation handling (9/09)
- [x] Finalise JUnit tests (10/09)
- [x] Improve code based on SonarCloud (10/09)
 
**Completion Deadline:**
Complete by the 10th of September
 
# **Documentation**
- [Player Movement Animations](../wiki/Player-Movement-Animations)

# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Jingyi Luo @Noland#5518 (@Nolandluo)
