### ISSUE TITLE
[Task] Creation and design of level 1 weapons

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#106]
# **Description**
**Task:** Create a graphical representation of a level 1 items
**Feature:** Combat Items #105  

The task is to generate a graphical image for level one items such as plungers and PVC pipes. Research will need to be conducted to suit the Greek Mythology theme this game is currently set within.  Such information could take the form of choosing the colour scheme, size or even weight of the dagger to be implemented for the description of the item. From here, dagger sketches will need to be viewed first to get a better understanding of what kind of dagger will be implemented. Upon creation of all sketches, one (or a collation of multiple ideas) should be selected and implemented on a graphical level through pixelated art. User research will be conducted on users who are familiar with video games to understand what they think of the weapon created. From this changes will be implemented. 
 
## **Example**
Below are some inspirations and directions on potential plunger and PVC pipe options. In addition to this, a wrench was created for the NPC team in order for them to utilise a tool for their guard player friend.

### Plumber Plunger
![image](https://user-images.githubusercontent.com/109809229/188141418-29ee4ab8-01e7-4b6a-a0cb-ad465bc9054a.png)
The key inspirations that were taken from this image stems from the detailing of the plunger especially coming from the outer layer seen at the bottom of the plunger alongside a white shadow outline on the rubber part. Furthermore, another inspiration taken was allowing the wrench to have a hole at the bottom of it as represented by most wrenches today.

### Plumber Wrench
![inspiration1](https://user-images.githubusercontent.com/109809229/189529416-6c03ce70-2b21-45cd-b30d-a1b10d84619c.png) ![inspiration2](https://user-images.githubusercontent.com/109809229/189529418-3f2acc57-e675-479f-b990-a4e105b68ceb.png)
The key inspiration here was allowing the wrench to have one side with a long edge and the other with a short edge. 

### PVC Pipes 
[Nisha please insert an inspiration over here]

# **Milestones**
List of steps that need to be completed for this task.
- [x] Research completed (Sept. 3)
- [x] Sketches completed (Sept. 5)
- [x] Graphical representation drawn (Sept. 6)
- [x] User testing created, completed & Updated Graphical Representation (Sept. 7)
  
# **Documentation**
- [Plunger](https://github.com/UQdeco2800/2022-studio-2/wiki/Plunger)
- [PVC Pipe](https://github.com/UQdeco2800/2022-studio-2/wiki/PVC_Pipe)
 
# **Member**
- Caleb Ang (PurrplePandaa) (Caleb Ang)
- Nisha Vashist (NishaVashist0) (Nisha Vashist)
