### ISSUE TITLE
<Task> Human Guard NPC

### ISSUE THREAD

**Issue by uq-haze** [UQdeco2800/2022-studio-2#107]
# **Description**
**Task:** Creating a Human Guard NPC

**Feature:** [NPC + Dialogue](#92 )

Creating a Human Guard NPC that will interact with the player. This will include multiple drafts, iterations and animated pixel designs. It will be implemented and have a dialogue interaction with the player. The guard will also be holding a weapon from the weapons team.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Create rough drafts and first iteration of Pixel Models (Sep 1)
- [x] Step 2: Implement animated plunger into guard's hand (Sep 3)
- [x] Step 3: User test and create second iteration (Sep 5)
- [x] Step 4: Create idle animation and documentation (Sep 8) 
 
**Completion Deadline:** Sep 13

# **Dependencies**
Creation and design of level 1 weapons [#106](https://github.com/UQdeco2800/2022-studio-2/issues/106)

# **Documentation**
- [Human Guard NPC](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs)
- [Plunger](https://github.com/UQdeco2800/2022-studio-2/wiki/Plunger)

 
# **Member**

- Hazeem bin Suffian (@uq-haze)
- Caleb Ang (@PurrplePandaa)

**Comment by PurrplePandaa** [comment]
Hey @uq-haze, if you could provide me with a basis of how your guard and plumber friend would look like so I can create a weapon for each of them, that would be fantastic. Looking forward to seeing your designs!

**Comment by uq-haze** [comment]
![pixil-frame-128](https://user-images.githubusercontent.com/110069874/189469833-933adc51-c1b9-4e1e-ab3b-bec284f48d5a.png)
hey @PurrplePandaa, above is an image of my human guard. I will provide a plumber picture soon

**Comment by PurrplePandaa** [comment]
Hey broski, yeah thanks for that image, I'll chuck on a plunger on the person and animate it. Please lmk how you feel about it in terms of the weapon style etc.

Here is the image I created:
![pixil-gif-drawing (11)](https://user-images.githubusercontent.com/109809229/189508138-2c658c1a-1710-41bc-8688-4c30434cfa73.gif)

**Comment by uq-haze** [comment]
Just a note, the guard should be holding a weapon instead of a plunger to look more menacing and intimidating

**Comment by PurrplePandaa** [comment]
Yeap, I've actually designed something within sprint 1 which wasn't used. You can use the following level 1 dagger for the guard. I think it'll suit them. [GuardWeapon.zip](https://github.com/UQdeco2800/2022-studio-2/files/9542604/GuardWeapon.zip) Chuck us a picture once it's integrated onto the guard's hand and then maybe I can see if the weapon needs tweaking.
