### ISSUE TITLE
[Task] Weapon proximity functionality

### ISSUE THREAD

**Issue by eugene2341** [UQdeco2800/2022-studio-2#108]
# **Description**
**Task:** Implement pick up functionality when player collides with weapon on the ground
**Feature:** Combat Items #105  

This task is to implement code to enable a player to pick up a weapon from the ground when it collides with the weapon, and automatically inserts the weapon into the inventory, which enables it to be equipped in the future.

When the player collides with the weapon, the weapon will be removed from the map, and the Array of spawned weapons on the map. It will then be added into the inventory, using the insert to inventory method implemented by Team 02.
## **Dependencies**
The inventory class should have a method that adds the weapon to the [inventory.] (https://github.com/UQdeco2800/2022-studio-2/issues/9)

# **Milestones**

- [x] Detect collision of player with weapon. (Sept 6)
- [x] Despawn the weapon from the map, then inserting the weapon to inventory. (Sept 8)
- [x] Update relevant documentation and wiki pages

**Deadline**: 8th Sept

# **Documentation**
Extension of Weapon Logic
(https://github.com/UQdeco2800/2022-studio-2/issues/34)

Weapon Pickup Function 
(https://github.com/UQdeco2800/2022-studio-2/wiki/Weapon-Pickup-Function)

# **Member**

- Eugene Chong (@eugene2341) (Eugene Chong)
