### ISSUE TITLE
<Task> Design for Inventory

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#11]
# **Description**
**Task:** [Design for Inventory](#11 )
**Feature:** [Inventory](#9 )
 
## **Example (optional)**
- **Inventory icon**: Provides an inventory icon for the game interface that can be clicked into with the mouse.
- **Interface of inventory**: An interface that shows the inventory of all collected items.

# **Dependencies**
In sprint1, we only provide the UI design of the general framework of the inventory, so there are no dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Draft of the design inventory (Aug. 19)
- [x] Research the elements and materials of inventory (Aug. 20)
- [x] Complete the initial inventory (Aug. 23)
- [x] Upload to team library (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
