### ISSUE TITLE
[Task] Animation sprite created for player

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#110]
# **Description**
**Task:** Create sprite animation for weapon attack on the player
**Feature:** Combat Items #105  

The goal of this task is to create a sprite animation for the weapon attacks. This would place more visual aesthetics within the game and allow for deeper interaction between the character and the individual playing the game. Two sprite animations will be created within this sprint both of which will be using either a PVC pipe or a level 3 dual-wielded dagger.  A player sprite must be given beforehand in order to complete this task and therefore will become part of this ticket's dependency. Animations should be sketched out before drawing and should adhere to aspects of previous designs created. Upon completion, the animation is to be exported as multiple .png files ready to be implemented into the game by the player class. Details on the player can be added after the weapon animation has been completed.
 
## **Example**
Below are some inspirations and directions on potential animation options:
![Metal Sluf](https://user-images.githubusercontent.com/109809229/188152315-7c45e195-a653-497c-9e39-d72a805ae13e.gif)
![curve](https://user-images.githubusercontent.com/109809229/188152940-ffa52412-55ca-4b30-a265-2fc37c9e344e.gif)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Static player drawing to be given to Weapon's team ready for animation (Sept. 5)
- [x] Sketches completed  (Sept. 7)
- [x] Graphical representation drawn & passed back to player team (Sept. 10)
  
# **Dependencies**
This ticket heavily relies upon the player team to complete their player image in order for the weapons to be visually integrated and for an animation to be completed. 

- [x] #104 

# **Documentation**
- [Weapon Animation](https://github.com/UQdeco2800/2022-studio-2/wiki/Hera-and-Athena#weapon-attack-animation)
- [Dagger Attack Animation](https://github.com/UQdeco2800/2022-studio-2/wiki/Daggers#animations)
 
# **Member**
- Caleb Ang (PurrplePandaa) (Caleb Ang)
- Nisha Vashist (NishaVashist0) (Nisha Vashist)
- Noland Luo (NolandLuo) (Noland Luo)

**Comment by PurrplePandaa** [comment]
Hey @NolandLuo @ew-b, I've done some work on the player attack animation. Was wondering what you guys thought of this. 
![Animation](https://user-images.githubusercontent.com/109809229/189375995-5adc5546-2d3f-413a-87c3-ccd93bbe982a.gif)

**Comment by ew-b** [comment]
Hi! @PurrplePandaa looks good, especially for level 2 weapons, but I think it'll be easiest to make essentially masks instead of animating the sprite each time, especially with the continuing iteration of what the character looks like and how it moves. I do think the sprite you have made is too buff for what our team has envisioned for the player character. Cool to see it moving though!

**Comment by PurrplePandaa** [comment]
Thanks for the input, I'll go ahead and update it accordingly. I do agree that the animation movement of the hand would look nicer this way but probably more implementable to have it as an overlay. Stay tuned!

**Comment by NolandLuo** [comment]
looks very cool, I like this weapon. Also, since we're setting up a plumber who hates his job, being too strong might not be a good fit. But a little muscle is ok (have added some muscle to the sprite after user testing)

**Comment by PurrplePandaa** [comment]
Alright guys, I've created another sprite animation for the player. This time, I've overlayed it ontop of the player so that we no longer have to depend as tightly on each other. The only downside would be that the arms kinda don't swing? But I wreckon for the purposes of this sprint it doesn't look awefully bad. Lmk if you have any concerns, Ta!

![level3DaggerRightAttackAnimationWithoutPlayer](https://user-images.githubusercontent.com/109809229/189513675-29902738-a6fe-4b41-934a-3bfeefe9f27b.gif) ![level3DaggerRightAttackAnimationWithPlayer](https://user-images.githubusercontent.com/109809229/189513676-777e0ad3-d8ef-42d6-a99c-054db7fc0dcb.gif)

**Comment by ew-b** [comment]
Hi! Looks really good, good work! Only think is the white knife shine looks like it's cutting off the characters head so maybe make it blue or something that contrasts well with a whitebackground

**Comment by PurrplePandaa** [comment]
Hey guys, we've come to a conclusion with the animations. Here they are! Feel free to let us know if have any major changes you want to make to these 😄 
| Weapon Description |  Animation |
| :---: | :---: | 
| Level 3 Dagger | ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/109809229/189528781-60475414-a468-4eaf-b9fa-53dbe2b8552d.gif)|
| Level 2 Dagger | ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/109809229/189528816-56b7d51f-8b3e-4395-94ff-7c931606d897.gif) |

**Comment by NolandLuo** [comment]
That looks pretty good. Arm swing we can talk about in the next sprint. (In addition, the latest Player Sprite has been uploaded)
