### ISSUE TITLE
[Task] Weapon appearance on player hand

### ISSUE THREAD

**Issue by eugene2341** [UQdeco2800/2022-studio-2#111]
# **Description**
**Task:** Make weapon to appear on player's hand when it is equipped
**Feature:** Combat Items #105

This task is to spawn an image of the weapon on the player's hands when the player equips the weapon from the inventory. When the weapon is equipped, the stats of the weapon should modify the stats of the player, such as setting the damage stat and decrease the movement stat of the player.

## **Dependencies**
Uses functionality from player class to modify the player's stats. #23 
Potentially requires player sprite image to be provided before weapon can be spawned into their hands #112 

# **Milestones**
- [x] Spawn the weapon on the player's hands. (Sept 10)
- [x] Modify the stats of the player when weapon is equipped. (Sept 10)
- [x] Update relevant documentation and wiki pages

**Deadline**: 11th Sept

# **Documentation**

# **Member**
- Eugene Chong (@eugene2341) (Eugene Chong)
- Caleb Ang (PurrplePandaa) (Caleb Ang)
- Nisha Vashist (NishaVashist0) (Nisha Vashist)

**Comment by IsaacGraham128** [comment]
Hey @NishaVashist0 , hope our little talk during the session was helpful for understanding how to implement your new attack animation system (the one similar to the current skills animation implementation). If you need any additional help or clarification please let me know :)

**Comment by PurrplePandaa** [comment]
Hey @IsaacGraham128, thanks for the tool tips, will most definitely holler tomorrow when we're implementing this section if we require assistance!

**Comment by LachlanBenson** [comment]
@PurrplePandaa @NishaVashist0 @eugene2341  can you please update with status of implementing static image? Do you reckon we could potentially hardcode a static image of the weapon to sit on the player on the isEquip? Could just do for 1 weapon for this sprint.

**Comment by NishaVashist0** [comment]
In accordance with consistency, we collaborated with @kurt-553 from team08 to do an overlay effect, rather than our original plan of changing the whole graphic when it came to adding elements to the player. This implementation has been inspired by the @kurt-553  implementation of the overlay effect.

**Comment by kurt-553** [comment]
Collaborated with @NishaVashist0 and @PurrplePandaa to give some pointers on the animation overlay effect for attack animations, to a similar code design as the skill animation overlay. They did an awesome job.

**Comment by PurrplePandaa** [comment]
Aww, you're too kind! Thanks
