### ISSUE TITLE
<Task> Player Sprite

### ISSUE THREAD

**Issue by NolandLuo** [UQdeco2800/2022-studio-2#112]
# **Description**
**Task:** [Player Sprite](#)

**Feature:** [Story, Player Character, Graphics, Animation and Extras](#100)
To complete the character Sprite design. Hand in the designed pictures to the weapon team (team 4) to create the weapon. And according to the need to create different character face for display in the game.

## **Example**
Character sprite: A dirty, poor plumber with a tool kit.

# **Dependencies**
Follow rule books and design guidelines.
Get as close as possible to the NPC style designed for team 7(NPC and dialogue).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] First edition of character sprite and (Sep 04)
- [x] Second edition of character sprite (Sep 05)
- [x] User testing (Sep 06)
- [x] Final edition of character sprite (Sep 08)
- [x] Design different player sprite orientations and different actions (Sep 11)
- [x] Upload all images of the design to assets(main) (Sep 12)

**Completion Deadline:** 
 Sep 12th
# **Documentation**
- [Player Sprite](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-sprite)

# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Jingyi Luo @Noland#5518 (@Nolandluo)
