### ISSUE TITLE
[Feature] Skills Tree

### ISSUE THREAD

**Issue by 45229848** [UQdeco2800/2022-studio-2#114]
# **Description**
Skill trees will be used throughout the game to give players a variety of different skill upgrades. This can include movement, attack, utility. Players can gain skill points by leveling up to unlock new skills. Different characters have different unique skills that can bring different gameplay experiences to the player.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Put forward the idea (Sep. 4)
- [ ] Began to draw (Sep. 6)
- [ ] User testing (Aug. 8)
- [ ]To complete the work (Aug. 10)

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g.  YongzhiZHOU(@45229848 ) (YONGZHI ZHOU)

**Comment by 45229848** [comment]
finish step 1

**Comment by 45229848** [comment]
finished

**Comment by 45229848** [comment]
finished

**Comment by 45229848** [comment]
fin
