### ISSUE TITLE
[Feature] Inventory storage and item equipment

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#115]
# **Description**
**Feature:** [Inventory storage and item equipment](#115)

In sprint 2, We will implement features that allow users to store items in their inventory and quickbar. In addition, we will implement features that will allow users to equip weapons and consume potions.

## SubFeature/component
-Logic of the item equipment and consumption

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Basic functionality of storing items (Sep. 9)
- [x] Implement inventory UI pop-up (Sep. 9)
- [x] Implement quickbar keybind (Sep. 10)
- [x] Implement potion consumption and item equipment (Sep. 11)
- [x] Implement unit tests for the feature (Sep. 12)

**Completion Deadline:** Sep. 13

# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
- Anders Jepsen (@0ceanfloor)
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
- Siu Ming Lam (@TimothyLam123)
- Lachlan McDonald (@Lukeyone)
