### ISSUE TITLE
Develop Basic Defence Skills

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#116]
# **Description**
**Task:** [Develop Basic Defence Skills (Block, Dodge)](#3).
**Feature:** [Skills](#2)
 
## **Example (optional)**
- **Dodge Skill**: Players can in-place dodge alongside their dash skill. This will allow players to move more quickly for a short time and not take damage, with an emphasis on sideways/backwards movement. If damage is mitigated during the dodge, this gives the player a short movement speed increase at the end of dodging, as well as cooldown reduction on the dodge skill.
- **Block Skill**: Players can block incoming damage for a short time, which will then reduce the cooldowns of all skills by a small amount.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Player Block Animation
- [ ] Player Dodge Animation
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement Movement Speed increase for dodge (05/09)
- [ ] Implement Damage Reduction for Block (05/09)
- [ ] Implement Movement Increase if damage mitigated during dodge (09/09)
- [ ] Implement Cooldown Reduction of all Skills by mitigating damage during block (09/09)
- [ ] Implement Cooldown Reduction on mitigation of damage for Dodge Mechanic (09/09)
 
**Completion Deadline:** September 9
 
# **Documentation**
Coming Soon
 
# **Member**
- Kurt (kurt-553) (kurt)
