### ISSUE TITLE
[Feature] World Traversal + Maps

### ISSUE THREAD

**Issue by otili9890** [UQdeco2800/2022-studio-2#117]
# **Description**
This feature will involve the creation of numerous maps that the player will be able to move between and thus traverse the playable world. This will allow for player progression throughout the story and world. 

## SubFeature/component (optional)
- Map Design
Creation of numerous maps, representing different areas and scenarios within the Atlantis world. Water animation, statues, refinement of existing components (Stairs, Trees, Columns).
- Map Transition
Implementation of transitions for the player to move between multiple maps. Plug hole animation. 
- Minimap
Implementation of a minimap that can be opened, pausing the game and then closed. 
 

## **Examples**
Map Design: 

- Other maps that the player will inhabit will be located below ground level
- These maps will contain weapons and components specific to their environment. 

Mini Map: 

- On click ->  whole map can be viewed - enlarged/overlay
- An indication of where the player is on the map
- Could possibly implement a drag interaction on the mini map (unless it’s always displaying the full map)
- Could mark certain locations, discovered/undiscovered

Map Transition: 

- Dependent on a win condition, the player is transported to the next stage
- A doorway (big plug) opens, allowing access

# **Dependencies**

This feature doesn’t have any dependencies, however many other features will be dependent on the map in order to be implemented, so it is critical to be able to offer a minimum viable product early in the process for their reference. 

# **Milestones**
Sprint 2 
Week 6 - 31st August

- [x] Decide what kinds of terrain level 2 will be. (Discussion with story team required) 
- [x] Create plug and drain designs. 
- [x] Application(s) to use for designing the terrain and other pixelated components

 
Week 7 - 7th September

- [x] Design and implement the level 2 terrain and layout. 
- [x] Creates samples of terrain(Provide options for the group to choose from for a mainstream style)
- [x] Create a few resource chunks to gather materials from (Visual only not functional)
 
Week 8 - 13th September
- [x] Implement the first terrain into the game(Coding Side)
- [x] Implement Wood and Steel resource chunks(Tree and Rock - Coding side) 

Before Studio on Week 8 (13th September)
Completion Deadline: 13th September

# **Documentation**

- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Name ([@github](https://github.com/github)) ([@slack](https://github.com/slack))
- Otis Carmichael (@Otili9890) (@Otis Carmichael)
- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
- Yibo Liu (@rlybgithub)
- Ishaan Ranade (@IshaanM8) (@Ishaan Ranade)
- Lonni Miller-Metzner (@lonnimm) (@Lonni Miller-Metzner)
