### ISSUE TITLE
[Task] Create 'Attack' function

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#118]
# **Description**
**Task:** Create a working attack function #118
**Feature:** Weapon Interaction & Attacking #105

This task is to develop and implement a working attack function on the press of a key, which triggers an attack animation and deals damage to enemies.

# **Dependencies**
- [x] #111 - For the attack function to be fully functional, it requires the attack stats to be modified and for the weapon to appear in the player's hand
- [x] #110 - Animation sprite created for player weapons
- [x] Enemy dies when health reaches zero (Team 3 to implement)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write pseudocode (Sept. 07)
- [x] When a player is within a close radius to the enemy and presses click, it deals damage to the enemy (Sept. 09)
- [x] When a player clicks, this cues the attack animation sprites which have been designed by our designers (Sept. 11)
- [x] Write JUnit Tests
- [x] Update relevant documentation and wiki pages

 
**Completion Deadline:** Sept 12th, 10:00pm
 
# **Members**
- Lachlan Benson (@LachlanBenson) (Lachlan.Benson#4926)
- Madi Feddema (@madifeddema) (madi-feddema#3384)
- Eugene Chong (@eugene2341) (gene#0005)

**Comment by LachlanBenson** [comment]
Note: current bugs - dispose disposes the textures of all enemies, not just of the particular enemy you are attacking
collision function is not ideal

**Comment by eugene2341** [comment]
everything is fixed no more bugs muahahaha

**Comment by madifeddema** [comment]
Issues with JUNIT testing currently, a) the name of the event listener is causing some issues and b) the sound functionality when trying to trigger the "attack" listener
