### ISSUE TITLE
<Task> Implement inventory logic

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#12]
# **Description**
**Task:** [Implement inventory logic](#12 )
**Feature:** [Inventory](#9 )
 
## **Example**
- **Inventory activation**: Players can access inventory by pressing the specified keybind(To be discussed). 

# **Dependencies**

No dependencies for sprint 1 implementation.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial logic of inventory and quickbar planned out (Aug. 19)
- [x] Unit tests implemented for inventory and quickbar (Aug. 20)
- [x] Inventory implemented and tested (Aug. 23)
- [x] Documentation of inventory updated on wiki (Aug. 27)
 
**Completion Deadline:** Aug. 29

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Li-Sung Ou (@PeterOu8)
- Siu Ming Lam (@TimothyLam123)
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
