### ISSUE TITLE
[Collab Task] Plan out spawn locations, availability and craftability for weapons

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#120]
# **Description**
**Task:** #120 
**Feature:** #150   

This ticket serves as a collaboration between Team 04 (Weapons), Team 05 (Maps), Team 06 (Story/Player) and Team 09 (Crafting) to plan out where the weapons will be spawned on the map, which weapons will be provided to the player and which will need to be crafted.

This is to ensure that all weapons can be useful within the game.

# **Depenencies**
- [x] Materials need to be made available to the player / crafting features for weapons need to be implemented
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide which weapons will be spawned and which will be crafted
- [x] Decide where weapons will be spawned on the map on each relative level
- [x] Oversee implementation of material drop and spawns
- [x] Need to spawn in Auras

**Comment by LachlanBenson** [comment]
This has been moved to Sprint 3 for scope creep reasons

**Comment by LachlanBenson** [comment]
@rkoll55 Can you please confirm as per our discussion on Discord it has been decided:
- Weapons will not spawn on the map natively
- Materials will be given to players via NPCs and random item drops from killing enemies
- Materials dropped on a random basis
- Stronger weapons not unlockable until Level 2

**Comment by rkoll55** [comment]
Crafting team approves
