### ISSUE TITLE
[Task] Transfer between levels 

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#121]
# **Description**
**Task:** Transfering between levels
**Feature:** [World Traversal + Maps](#117 )

Implements the animation for pulling a plug that is available after certain conditions are met. This allows the player to transfer between levels which allows for expansion of the game, as well as allows multiple other features to be implemented.
 
## **Example**
- **Plug**: Upon a certain condition being met, the plug is available to the player, which can be clicked and will transport the user to another part of the map to further continue exploring and playing the game.

# **Dependencies**

- [x] Map Design for another level (#126 )

# **Milestones**
- [x] Conduct iterations for Plug component (Sep. 4)
- [x] Develop and experiment with implementing the plug (Sep. 7)
- [x] Add conditionals to only allow the transportation of the user when certain conditions are met (Sep. 10)
- [x] Implement transportation of user and develop components for next level (Sep. 13)
 
**Completion Deadline:** Sep. 13

# **Documentation**

- [Game Area](https://github.com/UQdeco2800/2022-studio-2/wiki/Game-Areas)
- [Map Transition Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Transition-Design)
- [Map System Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-System-Code-Implementation)
 
# **Member**
- Ishaan Ranade (@IshaanM8) (Ishaan Ranade)
- Otis Carmichael (@otili9890) (https://github.com/otis Carmichael)

**Comment by IsaacGraham128** [comment]
Hey @otili9890 @IshaanM8 I have made changes to the transitional code of the levels. I have moved out of the player component and into the game screen levels. New level loading is based on making new map objects. See "MainGameScreen.java" for more info. 

Code in the keyboard component has been cleaned up, the heracles check is still un-commented for you to look into.
