### ISSUE TITLE
<Task> Implement item equipment

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#123]
# **Description**
**Task:** [Implement item equipment](#123).
**Feature:** [Inventory storage and item equipment](#115)

Implement features that enable players to equip suitable items in their inventory. 
 
## **Example (optional)**
- **equipItem()**: Equip the selected item.
- **modifyStats()**: Add effect or modify player's stats.

# **Dependencies**
- [x] Inventory (#9)
- [x] Combat items (#7)

e.g.
- [x] Weapon needs to be placed in a temporary item slot when equipped.
- [x] Player stat needs to be modified for player equipping the weapon.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement item equipment (Sep. 10)
- [x] Implement unit tests for the feature (Sep. 11)
- [x] Documentation on wiki (Sep. 12)

**Completion Deadline:** Sep. 13
 

# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [User documentation](../wiki/Game-Guide#section1)
- ...
 
# **Member**
-Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
-Siu Ming Lam (@TimothyLam123)
-Lachlan McDonald (@Lukeyone)

**Comment by LachlanBenson** [comment]
@PeterOu8 hey, just wanted to check whether we have a working equip function that will allow us to target and check if 'x' weapon is equipped or not?

**Comment by PeterOu8** [comment]
@LachlanBenson You can now equip weapons but you cannot unequip them. The unequip method is WIP

**Comment by LachlanBenson** [comment]
@PeterOu8 is the equip function in main yet?

**Comment by PeterOu8** [comment]
@LachlanBenson Sorry for the late reply, the function is on the main branch right now.
