### ISSUE TITLE
<Task> Implement potion consumption

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#124]
# **Description**
**Task:** [Implement item equipment](#124).
**Feature:** [Inventory storage and item equipment](#115)

Implement features that enable players to consume potion. 
 
## **Example (optional)**
- **consumePotion()**: Consume the selected item.
- **addEffect()**: Add the relevant effect of the potion.
- **modifyStats()**: Modify player's stats.

# **Dependencies**
- [x] Inventory (#9)
- [x] Potions (#32)

e.g.
- [x] Potion quantity needs to be modified after consumption.
- [x] Adding effects after the player consumed the potions.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement `potion` consumption (Sep. 18)
- [ ] Implement unit tests for the feature (Sep. 10)
- [x] Documentation on wiki (Sep. 11)

 
**Completion Deadline:** Sep. 12

 
# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [User documentation](../wiki/Game-Guide#section1)
- ...
 
# **Member**
-Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
-Siu Ming Lam (@TimothyLam123)
-Lachlan McDonald (@Lukeyone)
