### ISSUE TITLE
<Task> Level 2 Map Design Layout

### ISSUE THREAD

**Issue by Abi-B-28** [UQdeco2800/2022-studio-2#125]
# **Description**
**Task:** Level 2 Map Design Layout(#125 ).
**Feature:** World Traversal + Maps (#117)

Develop the map design layout for Level 2. This will be the basis of the textures and which components need to be designed + how/where they will be positioned. 

# **Dependencies**
- [x] Game progression from Level 1 to Level 2 needs to be decided (#xx)
- [x] Spawn Point
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] User Survey for Level 2 Map Inspirations (Sep 7)
- [x] Basic Draft Design for Level 2, create Wiki documentation (Sep 8)
- [x] Start creation (design) of components based on the overall map design (Sep 10)
- [x] Finalise Wiki Documentation (Sep 11)
 
**Completion Deadline:** Sep 13
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Abigail Borromeo (@Abi-B-28) (Abigail Borromeo)
