### ISSUE TITLE
<Task> Level 2 Base Map Implementation

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#126]
# **Description**
**Task:** Level 2 Base Map Implementation
**Feature:** World Traversal + Maps (#117)

The code implementation of level two base map. Create a new java Class which allow the other team to drop their design works for level two. The transition between different level will also be tested through Level one and Level two maps.

# **Dependencies**
At the beginning we will only put a rough map as a playground, once the design of Level two has finished, the styles will be implemented properly as planned.

- [x] Level 2 Map Design Layout (#125 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new Game Area class (Sep. 06)
- [x] Implement the necessary elements in the game (Sep. 06)
- [x] Test and load the map (Sep. 08)
- [x] Implement the base map styles once finished the design (Sep. 13)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**
- [Game Area](https://github.com/UQdeco2800/2022-studio-2/wiki/Game-Areas)
- [Map System Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-System-Code-Implementation)
 
# **Member**
Otis Carmichael (@otili9890) (https://github.com/otis Carmichael)
Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
Yibo Liu (@rlybgithub)
Ishaan Ranade (@IshaanM8) (@ishaan Ranade)
Lonni Miller-Metzner (@lonnimm) (@Lonni Miller-Metzner)
