### ISSUE TITLE
<Task> Implement Button and Menu Background Soundtrack

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#128]
# **Description**
**Task:** [ Implement Button and Menu Background Soundtrack](#128).
**Feature:** [Game Main Menu Soundtrack Design](#84 )
 
## **Example (optional)**
- When player click the buttons will have soundtrack.

# **Dependencies**
Corresponding soundtracks will be created based on story background.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Think about the soundtrack design according to button and story background (Sept. 5)
- [x] Make the soundtracks (Sept. 8)
- [x] Implement in game(Sept. 10)
- [x] User Testing (Sept. 12)
 
**Completion Deadline:** Sept. 12
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
