### ISSUE TITLE
Improve Crafting Table Design

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#130]
# **Redesigning Crafting Table**
**Task:** [Crafting Menu Table](#130 ).
**Feature:** [Refinement of Crafting Menu and Additional Features](#82)

Redesign and improve the crafting table.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Sept 4th)
- [x] User Testing (Sept 5th)
- [x] Updating Design Based on Feedback (Sept 6th)
- [x] Final Iteration/Implementation (Sept 7th)
 
**Completion Deadline:** Sept 7th
 
# **Documentation**
- [Crafting Table Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-Table-Visual-Assets-Design)
 
# **Member**
- Emily Southgate (@emily.southgate)
- Yingzheng Cai (@Rey-666)
