### ISSUE TITLE
<Task> Implement inventory and crafting menu display

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#131]
# **Description**
**Task:** [Implement inventory and crafting menu display](#131).
**Feature:** [Inventory storage and item equipment](#115)

Implement features that enable players to equip suitable items in their inventory. 

# **Dependencies**
- [x] Inventory (#9)
- [x] Integration of Inventory with Crafting System (#99)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Display them on the crafting menu in the correct slots (4th Sept)
- [x] Reading the availability of items in the inventory (9th Sept)
- [ ] Adding weapons that have been crafted into the inventory (9th Sept)
- [ ] Implement unit tests for the feature (Sep. 12)
- [x] Documentation on wiki (Sep. 15)

**Completion Deadline:** Sep. 18
 

# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [User documentation](../wiki/Game-Guide#section1)
- [Crafting System Code Implementation](../wiki/Crafting System Code Implementation)
 
# **Member**
-Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
-Siu Ming Lam (@TimothyLam123)
-Ly Phung (@lyphng)

**Comment by lyphng** [comment]
Hi @PeterOu8 @TimothyLam123 ! May I suggest a change to your RemoveItem method? Right now it will only remove the exact instance of the entity that's being passed through, but you ideally want it to remove one of whichever entity has the same type as the parameter.

**Comment by PeterOu8** [comment]
Hi Ly, thank you for capturing the issue. The intended functionality is to only remove one entity. I will fix this issue ASAP.

> Hi @PeterOu8 @TimothyLam123 ! May I suggest a change to your RemoveItem method? Right now it will only remove the exact instance of the entity that's being passed through, but you ideally want it to remove one of whichever entity has the same type as the parameter.
