### ISSUE TITLE
Implement New UI Features and Screens

### ISSUE THREAD

**Issue by lyphng** [UQdeco2800/2022-studio-2#133]
# **Description**
**Task:** Implement New UI Features and Screens(#132).
**Feature:** Refinement of Crafting Menu and Additional Features(#82)

This task involves replacing the current UI design with a new one, adding catalogue screens as well as navigation between the screens and additional features. These features are closing the menu with an exit button rather than a keybind, adding support for pause functionality with the button and allowing users to keep their current crafting progress when navigating between screens.
 
# **Dependencies**
- [x] Game Pausing Code Implementation (#89)
- [x] Crafting Menu Update (#86)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Replace menu design (Sept. 6)
- [x] Add catalogue screen and navigation between screens (Sept. 6)
- [x] Exit button functionality (Sept. 9)
- [x] Add support for pause functionality with exit button (Sept. 9)
 
**Completion Deadline:** Sept. 9
 
# **Documentation**
- [Crafting System Code Implementation](../wiki/Crafting System Code Implementation)
 
# **Member**
- Ly Phung (@lyphng)
