### ISSUE TITLE
<Task> Develop Attack Skills

### ISSUE THREAD

**Issue by TTevita** [UQdeco2800/2022-studio-2#134]
# **Description**
**Task:** [Develop Attack Skills](#3)
**Feature:** [Skills](#78)

This task is to develop two attack skills (bleed and root). Bleed applies an effect to the player's next attack which does additional damage over time to an enemy. Root applies an effect to the player's next attack which slows enemy movement.
 
# **Dependencies**

- [x] Need attack function because the skills are applied on top of regular attacks (#118)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement bleed functionality (Sept. 10)
- [x] Implement root functionality (Sept. 11)
- [x] Incorporate attack function into both skills (Sept. 13)
 
**Completion Deadline:** Sept. 13

# **Member**
- Name (@TTevita) (Tyler)
