### ISSUE TITLE
<Task>Implement potion effects

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#135]
# **Description**
**Task:** [Implement potion effects](#135).
**Feature:** [Inventory storage and item equipment](#115)

Implement features that add effect to the player based on the specific potion intake.
 
# **Dependencies**
- [x] Potions (#32)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Update and modify the potionFactory and potionEffect feature (Sep. 10)
- [x] Implement unit tests for the feature (Sep. 11)
- [x] Documentation on wiki (Sep. 12)

 
**Completion Deadline:** Sep. 13

 
# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [User documentation](../wiki/Game-Guide#section1)
- ...
 
# **Member**
-Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
