### ISSUE TITLE
Level 2 Map Environmental Components 

### ISSUE THREAD

**Issue by lonnimm** [UQdeco2800/2022-studio-2#136]
# **Level 2 Map Elements**
**Task:** [Level 2 Map Elements](#3).
**Feature:** [World Traversal + Maps](#117)

This task involves designing the various elements found within the level 2 map. Whilst some elements can be duplicated or adapted from level 1, there is a range of new elements to be added, in order to convey the dungeon/underground theme of this level. 
 
## **Example elements to be developed**
- **Torch**
- **Crumbling columns**
- **Moss covered walls/floors**
- **Barrels**
- **Rubble**

# **Dependencies**
This task depends on the following tasks:

- [x] Dependency 1 Level 2 Map Design Layout(#125)
- [x] Dependency 2 Level 2 Base Map Implementation(#126)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Brainstorm Elements (Sept. 7)
- [x] Step 2: Assign Elements (Sept. 8)
- [x] Step 3: Design Elements  (Sept. 10)
- [x] Step 4: User test/feedback of elements (Sept. 11)
- [x] Step 5: Implement elements (Sept. 12)
 
**Completion Deadline:** Sept. 12 

# **Documentation**
- [Level 2 Map Layout](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Layout-Design-Level-2)
- [Floor Tiles](https://github.com/UQdeco2800/2022-studio-2/wiki/Tile-Components#underground-level-floor-tiles---designing)
- [Water](https://github.com/UQdeco2800/2022-studio-2/wiki/Water#sprint-3---water-animation)
- [Walls](https://github.com/UQdeco2800/2022-studio-2/wiki/Walls-Component#wall-border--outer-dirt-filler-area)
- [Columns](https://github.com/UQdeco2800/2022-studio-2/wiki/Columns#level-2-column-final-iteration)
- [Torches](https://github.com/UQdeco2800/2022-studio-2/wiki/Torch-Level-2#final-iteration)
- [Pipes](https://github.com/UQdeco2800/2022-studio-2/wiki/Pipes-Level-2)
- [Statues](https://github.com/UQdeco2800/2022-studio-2/wiki/Statues)
 
# **Member**
- Lonni Miller-Metzner (@lonnimm) (Lonni Miller-Metzneer)
- Abi Borromeo (@Abi-B-28 ) (Abi Borromeo)
