### ISSUE TITLE
<Task> Implement Player Projectiles

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#137]
# **Description**
**Task:** [Implement Player Projectiles](#3).
**Feature:** [Skills](#2)

Implement a player projectile for skill attacks which can be fired at enemies for massive damage.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Projectile animation/texture (#xx)
- [ ] Enemy Projectiles (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement Spawn Projectile in game area (Sep. 13)
- [ ] Pin Projectile to skill keypress (Sep. 13)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**
- [Main description of feature](../wiki/Feature)

 
# **Member**
- Kurt (kurt-553) (Kurt Lucas)
