### ISSUE TITLE
<Task> User test for male citizen

### ISSUE THREAD

**Issue by hideonbush-crl** [UQdeco2800/2022-studio-2#139]
# **Description**
**Task:** [User test for male citizen](#3).
**Feature:** [NPC + Dialogue](https://github.com/UQdeco2800/2022-studio-2/issues/92)

In order to produce better male citizens, I created user tests for the male citizens I produced to help me confirm whether the male citizens I produced fit the style of the theme.
 
## **Example (optional)**
- **Main**: 
![male-citizen](https://user-images.githubusercontent.com/84514165/189519127-3c876219-1169-4cec-9efb-077eef0ee03c.png)

- **Animation**: 
![male-citizen 0](https://user-images.githubusercontent.com/84514165/189519141-8d37bae6-3708-4cc0-8138-c63bae606a1f.png)

# **Dependencies**

- [x] Needs to be paired with a female citizen (<TASK> Creating Female Citizen NPC Design #53 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Producing user tests for male citizens (Sep. 8)
- [x] Collecting data (Sep. 10)
- [x] Collating data for iteration (Sep. 11)

 
**Completion Deadline:** Sep. 11

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Bokai Zhang (@hideonbush-crl ) (Bkai Z)

**Comment by hideonbush-crl** [comment]
Finish!
