### ISSUE TITLE
Code movement pattern for melee enemy

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#14]
# **Description**
**Task:** Code movement pattern for melee enemy
**Feature:** Enemies (#3)

Currently the enemies are slow and very easy to outrun. Therefore, the enemies should become faster so that they are harder to outrun, creating a more intense experience for the player. Also currently, it is easy for the player to avoid the enemy by blocking them with a tree. Enemies should be able to detect trees and move around them.

 # **Dependencies**
- [x] Will need to have the new walking sprites before updating the default enemy walking sprites (#13)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide how enemy is going to move
- [x] Make the enemies faster and more intense
- [x] Change the enemies default walking sprites to the created walking sprites
 
**Completion Deadline:** Aug. 24

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Caitlenn Alsop (github: c-alsop) (Slack: Caitlenn Alsop)

**Comment by c-alsop** [comment]
Removed "Make the enemies more intelligent so they don't get blocked by obstacles" milestone as this is a lot more complex than first thought and not in the scope of Sprint 1. This will be added as a task to the Enemy Feature ticket.

**Comment by c-alsop** [comment]
Since the walking sprites for enemies were only finished recently, the enemies default walking sprites will be updated at the start of Sprint 2.
