### ISSUE TITLE
<Task>Fix the issue of switching between different maps.(Co-work by team 5 and team 9)

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#140]
# **Description**
**Task:** Fix the issue of switching between different maps.
**Feature:** [World Traversal + Maps](#117)

The issue was found during the implementation of changing the game map, which was the crafting system bound with the current Forest Game Area so it was unable to load another map. Team 5 and Team 9 will work together to fix the issue, the brief idea is to make the crafting system more generic and able to load different maps without any problem.
 
# **Milestones**

- [x] Team 5 Investigates the problem and determines which files and classes need to be modified. (Sep. 08)
- [x] Conclude and discuss with Team 9 (Sep. 09)
- [x] Team 9 works on the modification of the crafting system (Sep. 10)
- [x] Once the issue is fixed, Team 5 tests the updated feature by loading a different map (Sep. 11)
 
**Completion Deadline:** Sep. 12
 
# **Member**
- Yibo Liu (@rlybgithub)
- Otis Carmichael (@otili9890) (https://github.com/otis Carmichael)
- Ly Phung (@lyphng)

**Comment by rlybgithub** [comment]
Hi Crafting team. I am from team-05 map, we are creating the GameArea for Level two. I found there is a factor from the craft table not allowing me to load the new map. so the problem is for the current game the map can only be loaded with the crafting system because the setting in ServiceLocator, which is bound with the ForestGameArea. In this case, we will not able to load other maps except the ForestGameArea unless we remove the crafting stuff from ServiceLocator.

**Comment by rlybgithub** [comment]
Ideally, you can have the crafting system with a more generic approach, since all the maps are the subclass of the GameArea, then we can not only load the ForestGameArea with crafting but also load the different maps without changing the code manually.

**Comment by lyphng** [comment]
Thanks for letting us know! I've made the ServiceLocator functions work with the GameArea superclass rather than ForestGameArea and implemented a different method of detecting the player proximity to the crafting table so that it no longer relies on the table being spawned. You can see the details here https://github.com/UQdeco2800/2022-studio-2/commit/2c94489fe9172ef2f91e3de217235afb9685327a

**Comment by rlybgithub** [comment]
Thank you so much, It's been a pleasure working with you!

**Comment by lyphng** [comment]
You too! I'll close the ticket now since it's been resolved.
