### ISSUE TITLE
[Feature] Enemies (Sprint 3)

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#147]
# **Description**
Continuing to work on the enemy feature. This sprint will involve improving upon the base code for enemies that is already there, and also implement and design the level 2 boss.

## SubFeature/component (optional)
Fix different aspects of enemies
Create Level 2 Boss

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fixing the enemy projectiles. (Fix the hitbox. Also make it so that after projectile hits something it disappears)
- [x] Put in jump animation for boss.
- [x] Fix speed for enemies, so it can be increased without glitching.
- [x] Fix attack power for enemies to make it more balanced.
- [x] Make disposing enemies work
- [x] Work with map team to place enemies on the map
- [x] Design level 2 boss
- [x] Code level 2 boss
- [x] UML Diagram
- [x] Sequence Diagram

**Completion Deadline:** Sprint 3 Deadline

# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Caitlenn Alsop (@c-alsop) (Caitlenn Alsop)
- Yi Zhou (@MandalorianForce) (Yi Zhou)
