### ISSUE TITLE
[Feature] NPC + Dialogue

### ISSUE THREAD

**Issue by MonitaMegaele** [UQdeco2800/2022-studio-2#148]
# **Description**
NPC + Dialogue team this sprint is purely focusing on **_functionality of the NPCs_** and the **_Dialogue box_** which will create a story-like environment towards the game. _The player will be able to interact with our NPCs, obtain materials and gain knowledge on the story aspect._

## Features
---
1. Dialogue Box Design for each NPCs
- Dialogue Box Text 1234 then Close Dialogue Box upon clicking a button (instead of gif-like animation)
- Story Implementation
---
2.  Voice Overs
- Voice Over Implementation
---
3. Functionality
- Giving Potions / Materials
---

# Dependencies

**We depend on the Inventory Team to fully implement the inventory.**
Features affected : Functionality (Giving Potions/Materials)
- This is due to the interaction making the player obtaining a potion placed into the inventory

# **Milestones**

**Week 8**
- [x] Dialogue Box Rough Drafts (Sep. 17 Sat)
- [x] Voice Lines Draft (Sep. 18 Sun)

**Week 9**
- [x] Final Design of Dialogue Boxes (Sep. 19 Mon)
- [x] Implementation of Dialogue Boxes (Sep. 24 Sat)
- [x] Voice Lines Audio Files (Sep. 24 Sat)
- [x] Dialogue Functionality of Potion Giving (Sep. 25 Sun)

**Week 10 Break**

**Week 11**
- [x] Final Quality Check (Oct. 1 Sat) 
- [x] JUnit Testing (Oct. 1 Sat)
- [x] Final Implementation + Merge (Oct. 3 Mon)

**Completion Deadline:** October 4th Tuesday 4pm

# **Documentation**
- [Main description of feature](../wiki/[Dialogue + NPC](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs))

# **Members**
- Megaele Muniappan (@MonitaMegaele)
- Hazeem bin Suffian (@uq-haze)
- Nor Farahain Binti Husain (@Fayrain)
- Pengxu Chen (@viachen1)
- Bokai Zhang (@hideonbush-crl)
