### ISSUE TITLE
[Feature] Inventory interactions and refinements

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#149]
# **Description**
**Feature:** [Inventory interactions and refinements](#149)

In sprint 3, we will implement features that allow users to unequip items and add more interactive features.

# **Milestones**
List of sub-features you intend to have done and in Main by the end of the sprint.
- [x] [Implement unequip](https://github.com/UQdeco2800/2022-studio-2/issues/188) (Sep. 19)
- [x] [Implement sorting algorithm](https://github.com/UQdeco2800/2022-studio-2/issues/164) (Sep. 19)
- [x] [Implement inventory display update](https://github.com/UQdeco2800/2022-studio-2/issues/197) (Sep. 20)
- [x] [Implement equippable display](https://github.com/UQdeco2800/2022-studio-2/issues/192)  (Sep. 21)
- [x] Implement more button eventListeners (Sep. 21)
- [x] [Implemente swap method for Weapon/Armour](https://github.com/UQdeco2800/2022-studio-2/issues/216) (Sep. 28)
- [x] Implement unit tests(Sep. 29)
- [x] [Documentation on wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/Inventory) (Oct. 2)

**Completion Deadline:** Oct 2

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
- Anders Jepsen (@0ceanfloor)
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
- Siu Ming Lam (@TimothyLam123)
- Lachlan McDonald (@Lukeyone)
