### ISSUE TITLE
[Task] Level 2 Pause Menu

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#152]
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151)

# Description
Design and implement the level 2 pause menu.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] General Concept/Design (Sept 19th)
- [ ] User Testing (Sept 20th)
- [ ] Updating Design Based on Feedback (Sept 21st)
- [ ] Final Iteration/Implementation (Sept 23rd)
 
**Completion Deadline:** Sept 25th
 
# **Documentation**
- [Pause Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Game-Pause-Screen--Visual-Assets-Design)
 
# **Member**
- Enoe (Jolo) Gapusan (@jgapusan)

**Comment by cluanzon** [comment]
Hey @jgapusan what do you think of these ideas as an inspiration to the new pause menu screen?

![A3F90FB0-3F35-41CE-8D08-D8B5C3FF146D](https://user-images.githubusercontent.com/110017386/192686240-04b47f4a-7e99-4b1e-a783-3fadb2f8f101.jpg)

![E5EA0AA4-5A6F-4A6B-8105-89DEC41A00D5](https://user-images.githubusercontent.com/110017386/192686467-46f2ee96-f043-4e0c-87a7-bfe4447d2d81.jpg)

**Comment by jgapusan** [comment]
@cluanzon looks good! just let me know once you have a design going :DD

**Comment by cluanzon** [comment]
@jgapusan I've made some base designs but debating what size. Wdyt ?

Big Size
![8551FC99-E2D9-4C10-9E8F-14B035C05883](https://user-images.githubusercontent.com/110017386/192686950-7b9bc360-ef06-46b2-b4ff-3cb457d5ef45.jpg)


Small Size
![738F756A-90F1-4C4D-B718-C828057074C5-1](https://user-images.githubusercontent.com/110017386/192686962-fb10d86e-9b7c-423b-9a96-8c00e278414e.jpg)

**Comment by jgapusan** [comment]
the small looks clean but i think might as well go with the big one honestly @cluanzon

**Comment by cluanzon** [comment]
oki oki Ive pushed the final design at the images folder under another folder called the PauseMenu folder because I wasn't sure where to put it.

**Comment by jgapusan** [comment]
just had a look it looks great ! just one thing, because way that we do buttons we need to have separate widget files, so you can please do those for each button ?

**Comment by cluanzon** [comment]
Ye sure do u want me to push it at the same folder?

**Comment by jgapusan** [comment]
yup that'd be good !

**Comment by cluanzon** [comment]
aight ive just pushed the widgets over

**Comment by cluanzon** [comment]
i made a new folder in the pauseMenu called "widgets" they will be in there
