### ISSUE TITLE
[Task] Main Menu Screen 

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#155]
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151)

# Description
Design and implement the main menu screen and its animations
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] General Concept/Design (Sept 19th)
- [ ] User Testing (Sept 20th)
- [ ] Updating Design Based on Feedback (Sept 21st)
- [ ] Implementing Animations (Sept 22nd)
- [ ] Final Iteration/Implementation (Sept 23rd)
 
**Completion Deadline:** Sept 25th
 
# **Documentation**
- TBC
 
# **Member**
- Emily Southgate (@e-southgate)
