### ISSUE TITLE
Fixing Enemy Projectile Issues

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#156]
# **Description**
**Task:** Fixing Enemy Projectile Issues
**Feature:** [Sprint 3 Enemies](#147 )

This task will involve fixing enemy projectile issues. Projectile's hit box is currently bigger than the projectile so that needs to be fixed. Also, after projectile hits something, it should disappear. Also, the projectiles aiming should be edited so that instead of constantly following the player, they will instead aim for the initial position of the player so that the player has a chance of dodging them.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix projectile hit box issue where it knocks the player back
- [x] Fix projectile hit box issue where the hit box is too large compared to the projectile
- [x] Make it so that projectile disappears on contact
- [x] Change projectiles aiming to not follow the player
- [x] Document in wiki
- [x] Write JUnit tests
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Caitlenn Alsop (c-alsop) (slack: Caitlenn Alsop)

**Comment by c-alsop** [comment]
Projectiles no longer throw player back and they now shoot at the player but don't follow the player around. Still working on projectiles disappearing on collisions.

**Comment by c-alsop** [comment]
Hit boxes and collision components have now been re-sized and re-aligned to match projectile size. This has been documented on the wiki.

**Comment by c-alsop** [comment]
Projectile successfully disappears on contact with player. All that is left now is to finish up documentation on wiki and write JUnit tests,

**Comment by c-alsop** [comment]
Documentation done.
