### ISSUE TITLE
Put in Jump Animation for Heracles (Level 1 boss)

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#157]
# **Description**
**Task:** Put in Jump Animation for Heracles (Level 1 boss)
**Feature:** [Sprint 3 Enemies](#147)

Put in jump animation for the boss.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Edit Heracles' sprite sheet to include jump animation
- [x] Code Heracles' to have jump animation
- [x] Document in wiki
- [x] Write JUnit tests
 
**Completion Deadline:** Sprint 3 Deadline

# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)

# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
