### ISSUE TITLE
Fix speed for enemies, so it can be increased without glitching.

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#158]
# **Description**
**Task:** Fix speed for enemies, so it can be increased without glitching.
**Feature:** [Sprint 3 Enemies](#147)

Fix the speed for enemies, so the speed can be increased without the enemies glitching out.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the speed for enemies
- [x] Document on wiki
- [ ] Write JUnit tests
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
- Bach Truong(bach-truong)(Bach Truong)
