### ISSUE TITLE
Fix attack power for enemies to make it more balanced.

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#159]
# **Description**
**Task:** Fix attack power for enemies to make it more balanced.
**Feature:** [Sprint 3 Enemies](#147)

Fix attack power for enemies to make the combat more balanced.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix attack power for enemies to make the combat more balanced.
- [x] Document on wiki
- [x] Write JUnit tests
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
