### ISSUE TITLE
Make disposing enemies work

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#160]
# **Description**
**Task:** Make disposing enemies work
**Feature:** [Sprint 3 Enemies](#147)

Fix the disposal of enemies so that it works.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the disposal of enemies so that it works
- [ ] Document on wiki
- [ ] Write JUnit tests
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
- Bach Truong(bach-truong)(Bach Truong)
