### ISSUE TITLE
[Collaboration] Placing enemies on the map

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#161]
# **Description**
**Task:** Work with map team to place enemies on the map
**Feature:** [Sprint 3 Enemies](#147)

Work with map team to place enemies on the map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide where enemies will go on the map.
- [x] Place enemies on the map.
- [x] Document on wiki
- [x] Write JUnit tests.
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Extras**
For next sprint:
- [ ] Perform user tests to gather feedback about where the enemies are and if any changes need to be made
- [ ] Implement those changes, if any

# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Caitlenn Alsop (c-alsop) (slack: Caitlenn Alsop)

**Comment by LachlanBenson** [comment]
@bach-truong just thought i'd throw in my 2 cents here. Think it would make sense to spawn the weakest enemy first (make there a few of them) - the melee only enemies (gymbro).

After you kill all the gymbros, then the big boss dude spawns.

I think if you were to spawn the boss at the same time it would be too challenging and potentially confusing.

**Comment by bach-truong** [comment]
My team was planning to do that as well. Now it's just showing that the Boss existed for sake of grading. But we'll work on how to spawn enemies properly with team Map.

**Comment by bach-truong** [comment]
Hey Team 5 (Map team), do you guys have any plan on configuring the map so that we can spawn it on a specific area?

**Comment by LachlanBenson** [comment]
> Hey Team 5 (Map team), do you guys have any plan on configuring the map so that we can spawn it on a specific area?

This would definitely be ideal. We need to get the spawn locations in by end of sprint. I guess waiting on map team to update implementation for now.

**Comment by IshaanM8** [comment]
> > Hey Team 5 (Map team), do you guys have any plan on configuring the map so that we can spawn it on a specific area?
> 
> This would definitely be ideal. We need to get the spawn locations in by end of sprint. I guess waiting on map team to update implementation for now.
Hey there, Yes, we can give specific coordinates that can be used to spawn the Entities at, that should suffice in deploying them at a particular location

**Comment by c-alsop** [comment]
Hi, the level 2 enemies (basic poop enemy, mega poop boss) are on the underground map now and they have also been removed from the level 1 map

**Comment by IshaanM8** [comment]
> > > Hey Team 5 (Map team), do you guys have any plan on configuring the map so that we can spawn it on a specific area?
> > 
> > 
> > This would definitely be ideal. We need to get the spawn locations in by end of sprint. I guess waiting on map team to update implementation for now.
> 
> Hey there, Yes, we can give specific coordinates that can be used to spawn the Entities at, that should suffice in deploying them at a particular location

> Hi, the level 2 enemies (basic poop enemy, mega poop boss) are on the underground map now and they have also been removed from the level 1 map

Hey Everyone, I've provided a miro board that displays a bunch of coordinates across the map that should help you in the placements of your entities, thanks for already getting on with the transition!
https://miro.com/app/board/uXjVPRET2Lo=/?share_link_id=131599096866
