### ISSUE TITLE
Design Level 2 Boss

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#162]
# **Description**
**Task:** Design Level 2 Boss
**Feature:** [Sprint 3 Enemies](#147)

Design Level 2 Boss
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Come up with concept for level 2 boss
- [x] Design level 2 boss
- [x] Create animations for level 2 boss
- [x] User Test Level 2 Boss
- [x] Document on Wiki
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
