### ISSUE TITLE
Code Level 2 Boss

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#163]
# **Description**
**Task:** Code Level 2 Boss
**Feature:** [Sprint 3 Enemies](#147)

Code the level 2 boss into the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide how the boss will move
- [x] Code the boss into the game
- [x] Code the bosses' moves and attacks
- [x] Write JUnit tests.
- [x] Document on wiki
 
**Completion Deadline:** Sprint 3 Deadline
 
# **Next Sprint**
- [ ] Recode projectile attack to be a multi-projectile attack that leaves areas covered in poop

# **Documentation**
- [Enemies Feature Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Caitlenn Alsop (c-alsop) (slack: Caitlenn Alsop)
