### ISSUE TITLE
<Task> Implemente inventory sorting algorithm

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#164]
# **Description**
**Task:** [Implemente inventory sorting algorithm](#164)
**Feature:** [Inventory interactions and refinements](#149)

The current inventory stacking system allows the player to stack items in the inventory. Once an item is removed, the quantity array does not change the order itself and therefore causing the item after the removed item to have a quantity of 0. In sprint 3, we will implement a sorting algorithm for the inventory to avoid item quantity being wrongly stacked.
 

# **Milestones**
- [x] Implement the sorting algorithm (Sep. 16)
- [x] implement unit tests (Sep. 23 )
- [x] documentation on wiki (Sep. 24)

**Completion Deadline:** Sep.24

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
