### ISSUE TITLE
[Task] Unique Dialogue Box Implementation

### ISSUE THREAD

**Issue by MonitaMegaele** [UQdeco2800/2022-studio-2#165]
# **Description**
**Task:** [Unique Dialogue Box Implementation](#3).
**Feature:** [NPC + Dialogue](#148 )

Dialogue Box Implementation creates a unique dialogue box design of each NPC which contains story aspects. The box goes through the dialogue from start to finish with clicks of buttons and closes the dialogue box when player finishes the final dialogue read.
 
## **Example**
**Dialogue Box**: 
- The Dialogue box should have a unique design for each NPC
- The Dialogue box should contain unique quotes to navigate the player towards the story
- The Dialogue box should not be an animation but a change in image on the click of a button
- When Dialogue is done, Dialogue Box should close
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Dialogue Boxes Draft (Sep. 17)
- [x] NPC Quotes (Sep. 18)
- [x] Dialogue Boxes Final Design (Sep. 19)
- [x] Dialogue Boxes Implementation (Sep. 24)
- [x] User Testing (Sep. 25)
- [x] Dialogue Box Functionality Testing (Oct. 1)
- [x] Implementation (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs) 
- Code Yet to be Implemented
 
# **Member**
- Monita (@MonitaMegaele) (Monita Muniappan)
- Farahain (@Fayrain) (Farahain Husain)
