### ISSUE TITLE
<Task> Implemente unequip method for equippables

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#166]
# **Description**
**Task:** [Implemente unequip method for equippables](#166)
**Feature:** [Inventory interactions and refinements](#149)

I will implement an unequip method for any equipable item. This includes the weapons and armor. When unequip is called, it should remove the previous stat modifications on the player.
 

# **Milestones**
- [x] Implement unequip method (Sep. 16)
- [x] implement unit tests (Sep. 23 )
- [x] documentation on wiki (Sep. 24)

**Completion Deadline:** Sep.24

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
- Lachlan McDonald (@Lukeyone)
