### ISSUE TITLE
[Feature] Skill Tree and Skills

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#167]
# **Description**
Implementing a full skill tree, alongside all the skills developed within the tree will afford the player diverse gameplay options for how they would like to move and attack enemies within the game. Progression of how to earn new skills within the gameplay loop should also be considered and developed to finalise the skills as a functional part of player progression.

# **Dependencies**
- [x] Skill assignment needs skill earning from enemy deaths
- [x] Skill tree art required to implement skill tree
- [x] Finalisation of all skill ideation

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Ultimate/Time-stop functionality implemented (20 Sep.) 
- [x] Implement aoe push skill (20 Sep.)
- [x] Design the animation of the aoe push skill (24 Sep.) _-Andy_
- [x] Skill tree displayed in-game (24 Sep.) 
- [x] Design the skill icon of the projectile skill (25 Sep.) 
- [x] Design the animation of invulnerability skill (27 Sep.) _-Andy_
- [x] Skill tree can assign skills to player (27 Sep.)
- [x] Finalise skill keybindings (27 Sep.)
- [x] Ultimate/Time-stop full-screen white flash implemented (27 Sep.) 
- [x] Charge attack skill implemented (27 Sep.)
- [x] Finalise projectile skills (27 Sep.)
- [x] Implement invulnerability buff skill (27 Sep.)
- [x] Implement visual cooldown representation on UI bar (27 Sep.) - Jessica Froio
- [x] Create wrench projectile skill (27 Sep.)
- [x] List conception of all skills (29 Sep.) _-Andy_
- [x] Design the animation of another ultimate skill (1 Oct.) _-Andy_
- [x] Optimise some icons and animations based on feedback (3 Oct.) _-Andy_
- [x] design projectile icon -(23 Sep) - Futian Jiang
- [x] design attack speed icon - (24 Sep) - Futian Jiang
- [x] redesign and update the skill tree icon - (30 sep) - Futian Jiang

**Completion Deadline:** Oct 4

# **Documentation**
- [skills](../wiki/Skills)

# **Members**
- Kurt Lucas (kurt-553) (Kurt Lucas)
- Zhuohang Song(AndySong-2324) (AndySong)
- Tyler Tevita (TTevita) (Tyler)
- Futian Jiang (FutianJiang)
- Jessica (jessfroio)
- Yongzhi Zhou (45229848)
