### ISSUE TITLE
[Feature] Loading, Death, and Win Screen Implementations and Support

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#168]
# **Description**

In this sprint, we aim to develop death screens per level (animations), win screen, lose screen, and loading screen, then implement them into the game to create a cohesive storyline and develop a stronger emotional attachment. These aspects are fundamental in making the game feel polished.
We also plan to support the following teams:
The NPC team is in their programming implementation as they only have one programmer in their team. This includes a proximity key prompt, in which a player is near the thing to interact with and is promoted to click a key.
Skills team in their skill tree implementation since they are struggling to find a space in the game and implement it.

## **Examples (optional)**
- **Win screen**: shows Atlantis sinking into the ocean with the words ‘you win’ on the screen.

- **Loading Screen**: the loading screen will vertically display all the death screens made previously. More examples can be seen in the link below:
https://www.canva.com/design/DAFLPo_VsZQ/PQqQ5-WQBq-AkudZVd7MJw/edit

# **Dependencies**
List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

* All screen designs will depend on the Maps team (team 5) to ensure that the designs are cohesive. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Basic sketches for the loading screens done (Sept. 20)
- [x] Basic sketches for the win and lose screens done (Sept. 20)
- [x] Implementation of death screen levels 1 and 2 complete (Sept. 23)
- [x] Implementation of programming of win, lose, and loading screen complete (Sept. 26)
- [x] Key prompt interaction system implemented (Sept. 26)
- [x] User testing all screen designs (Sept. 26) 
- [x] Iterate designs based on user feedback (Sept. 30)
- [x] All screen graphics implemented (Oct. 2)
- [x] Wiki’s updated to reflect work(Oct. 4)

**Completion Deadline:** Oct. 4(Tue)

# **Extras (optional)**
 Skill tree implementation with Skills Team.

# **Documentation**
[Death & Death Screen Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-&-Win-Screen-Code-Implementation)
[Death Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-Screen-Design)
[Key Bind Menu](https://github.com/UQdeco2800/2022-studio-2/wiki/Key-Binds-Menu)
[Loading Screen Transition Screen](https://github.com/UQdeco2800/2022-studio-2/wiki/Loading-Screen---Transition-Screen)
[Player Guide](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Guide)
[Win Screen Testing](https://github.com/UQdeco2800/2022-studio-2/wiki/Testing-plan-and-User-testing-of-Win-screen)
[Win Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Win-Screen-Design)

# **Members**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)
