### ISSUE TITLE
<Task> Screen Implementation

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#169]
# **Description**
**Task:** Screen Implementation (#3).
**Feature:** Loading, Death, and Win Screen Implementations and Support (#168)

The goal of this task is to implement the programming side of the death, loading, win and lose screens. A screen class will be made for the relevant elements, a folder in components will be added for the relevant elements, GdxGame screenType enum will have each of the screens added, as well as implemented in the switch case under newScreen. ServiceLocator will also be updated to have the associated elements loaded into the game. For each time the player dies, when health is 0, a death screen will display with the correlated level on it, it will reload the level and reset the bosses. When the character loses the final boss battle, with a health of 0, the lose screen with display and the level will reset. When the character wins the final boss battle, the final enemy health of 0, the win screen displays and the player is taken back to the main menu. The loading screen displays when the player transitions from level 1 to level 2, specifically when the final boss of level 1’s health is zero AND the character is over the plug.
 

# **Dependencies**
* Map team implementation for checking the map has been cleared of enemies
* Character on or near plug being able to be registered
 
# **Milestones and Deadlines**
List of steps that need to be completed for this task.
- [x] Character health function to check the character's health (Sept. 19)
- [x] Initial death screen classes created and documented (Sept.19)
- [x] Code commented and javadoc’s added (Sept. 21)
- [x] Death screen levels 1 and 2 implemented (Sept. 23)
- [x] Wiki documentation complete (Sept. 23)
- [x] Replace placeholder images with the final animations/designs (Sept. 30)

 
# **Documentation**
[Death & Death Screen Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-&-Win-Screen-Code-Implementation)
[Death Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-Screen-Design)
[Player Guide](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Guide)
[Win Screen Testing](https://github.com/UQdeco2800/2022-studio-2/wiki/Testing-plan-and-User-testing-of-Win-screen)
[Win Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Win-Screen-Design)
[Key Bind Menu](https://github.com/UQdeco2800/2022-studio-2/wiki/Key-Binds-Menu)
[Key Bind Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Keybind-(Controls)-Page-Implementation)
[Loading Screen Transition Screen](https://github.com/UQdeco2800/2022-studio-2/wiki/Loading-Screen---Transition-Screen)
[Loading Transition Screen Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Loading---Transition-Screen-Implementation)

# **Members**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)
