### ISSUE TITLE
 Code melee enemy drops

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#17]
# **Description**
**Task:**  Code melee enemy drops.
**Feature:** Enemies (#3)

When enemies are defeated, they will drop certain equipment or weapons. Melee enemies will drop melee weapons amongst other equipment.
 
# **Dependencies**
- [x] Enemies will need a health stat, so they can die and therefore drop equipment (#10)
- [x] The weapons/equipment to drop will need to be created

# **Milestones**
- [x] Code way to store enemy weapon.
- [x]  Code way to kill enemies
- [x] When enemy dies, code weapon to drop where enemy died
- [ ] Write JUNIT test for drop weapon
- [x] Update wiki and documentation
 
**Completion Deadline:** Sep. 12

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)

# **Member**
- Caitlenn Alsop (github: c-alsop) (Slack: Caitlenn Alsop)
- Bach Truong (github: bach-truong) (slack: bach truong)

**Comment by c-alsop** [comment]
This task has been partially completed in sprint 1, however, it will be fully completed in sprint 2.

**Comment by LachlanBenson** [comment]
@bach-truong no worries, we will work on having this finalised by the end of the sprint

**Comment by madifeddema** [comment]
Pseudo code is partially written. Need to talk to player about their equip function first to make sure that the weapon drop function can be used in multiple always

**Comment by LachlanBenson** [comment]
@madifeddema please provide status update

**Comment by madifeddema** [comment]
At the moment I've got a weapon temporarily dropping, however it is not staying on the map. This is on a key press event (Y) at the current moment

**Comment by madifeddema** [comment]
Task finish :)

**Comment by bach-truong** [comment]
Great job everyone
