### ISSUE TITLE
<Task>  Key prompt interaction system 

### ISSUE THREAD

**Issue by whyhlf** [UQdeco2800/2022-studio-2#170]
# **Description**
**Task:** Key prompt interaction system 
**Feature:**  Loading, Death, and Win Screen Implementations and Support (#168)

The goal of this task is to help the user to know each key bind in the game. To guide the player better play the game, instead of spending a lot of time learning all key binds. Users could see the helpful tips when they are crafting, interacting with the npc and moving around the map etc.

## **Example (optional)**
- **Key Promot**: The pop up message would tell the user which key to interact with the npc or the item. 

![image](https://user-images.githubusercontent.com/70302896/190565000-272a7edf-f85f-47fc-aeb5-3bdf5e3f997b.png)

# **Dependencies**

- working with NPC team to work out the workflow with the map characters
- [x] working with CRAFTING team to fit the crafting system with appropriate message
- working with MAP team to figure out how to interact with the level end plug

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Look into the code and try to implement a demo function (Sep 20)
- [x] Finalised the idea with other teams(Sep. 22)
- [x] Implement most functions in the branch(Sep. 24)
- [x] Key prompt interaction system in the game(Sep. 26)
 
**Completion Deadline:** Sep. 26
 
# **Documentation**
- Wiki page coming soon
 
# **Members**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)

**Comment by whyhlf** [comment]
@viachen1  I have added the key prompt system into the game.  You can add the NPC key prompt based on that, or I can do that
