### ISSUE TITLE
<Task> Loading Screen / In Between Level Transition Screen 

### ISSUE THREAD

**Issue by aalice23** [UQdeco2800/2022-studio-2#171]
# **Description**
**Task:** Loading screen (#171).
**Feature:** Loading, Death, and Win Screen Implementations and Support (#168)

This screen will appear when the player is transitioning between levels. The purpose of this screen is to make the gameplay smoother and to inform the player the level that they’ll be moving to. 
 
## **Example (optional)**

- **Loading screen display**: Using the death screen designs, the loading screen will be displayed in a vertical format
https://i.pinimg.com/564x/e8/c8/93/e8c8935d55968fdd5fd8c112d405265a.jpg

# **Dependencies**
* Death screen designs (sprint 2)
* Placeholder loading screen implemented in the game, to be replaced once loading screen developed. (#169)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Brainstorm ideas (ideation board) (Sept. 17)
- [x] Show the team the ideas and get confirmation (Sept 18)
- [x] Screens designed (Sept. 20)
- [x] Conduct user testing on the designs (Sept 26)
- [x] Make iterations based on design (Sept 30)
- [x] Implement loading screens into game (Oct 2)

**Completion Deadline:**  Oct 4

# **Documentation**
[Loading Screen Transition Screen](https://github.com/UQdeco2800/2022-studio-2/wiki/Loading-Screen---Transition-Screen)
 
# **Members**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)
