### ISSUE TITLE
<Task> Win Screen Design and Implementation

### ISSUE THREAD

**Issue by NolandLuo** [UQdeco2800/2022-studio-2#172]
# **Description**
**Task:** Win Screen Design and Implementation (#172)
**Feature:**  Loading, Death, and Win Screen Implementations and Support (#168)
In the game to achieve the player after winning the victory interface. Once a player has successfully passed level 2, a screen appears to tell the player that he(she) has successfully completed the game and ask whether they want to play again or not.

# **Dependencies**
A final plug completed by Team 5(map) is required. The win screen is only displayed when the player jumps from the plug at Level 2.

-  The level 2 plug needs to  be implemented by map team (team 5) and be placed onto map. **Didn't happen, partial implementation complete.**
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] The sketch draft of win screen (Sep. 20)
- [x] The pixel image of win screen (Sep. 24)
- [x] The user testing of win screen (Sep. 26)
- [x] Implementation of programming of win screen complete (Sept. 26)
- [x] Iterate designs based on user feedback (Sept. 30)
- [x] The win screen graphics implemented into the game (Oct. 2)
- [x] Wiki’s updated to reflect work (Oct. 3)
 
**Completion Deadline:** Oct. 3

# **Documentation**
[Win Screen Testing](https://github.com/UQdeco2800/2022-studio-2/wiki/Testing-plan-and-User-testing-of-Win-screen)
[Win Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Win-Screen-Design)
[Death & Death Screen Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-&-Win-Screen-Code-Implementation)
 
# **Members**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)

**Comment by ew-b** [comment]
Level 2 is still undergoing changes. Due to timeline it was not possible to implement a win state. Level 2 still does not have enemies and maps team are still intending to update the map layout. Hence it was decided for now the win state is pressing the letter N, it will be easy to change to a proper win state in KeyboardPlayerInputComponent under Enter.
