### ISSUE TITLE
<Task> Design and optimize skill animations and icons (dynamic)

### ISSUE THREAD

**Issue by AndySong-2324** [UQdeco2800/2022-studio-2#173]
# **Description**
**Task:** [Design and optimise skill animations and icons (dynamic)](#3).
**Feature:** [Skills](#2)

I will work on the ultimate skill, critical number, invulnerability animation and three skill icons by pixel art. Besides, I will summarise all the skills that our team has designed and list all the functions for easy code implementation, and optimise the skill animations and icons I designed before. And finally documented most of the skill design part in the wiki up to now.

# **Dependencies**

# **Milestones**
List of steps that need to be completed for this task.

- [x] Collab with team 2 to place the skill tree on the screen (22 Sep.)
- [x] Design the animation of the critical hit numbers (24 Sep.)
- [x] Add different versions of teleport/block/dash/dodge/invulnerability skill icons(hover, active and disable) (26 Sep.)
- [x] Optimise some icons and animations based on feedback (after user testing)(27 Sep.)
- [x] List conception of all skills (29 Sep.)
- [x] Design the animation of another ultimate skill (1 Oct.)
- [x] Design the animation of invulnerability skill (2 Oct.)
- [x] Design the blood skill icon by pixel art (3 Oct.)
- [x] Design the charge skill icon by pixel art (3 Oct.)
- [x] Design the time stop(ultimate skill) icon by pixel art (4 Oct.)
- [x] Document the skill design section in the wiki (3 Oct.)
 
**Completion Deadline:** 3 Oct.

# **Member**
- Zhuohang Song(AndySong-2324) (AndySong)
