### ISSUE TITLE
[Collaboration] Spawn Materials On Map System

### ISSUE THREAD

**Issue by Rey-666** [UQdeco2800/2022-studio-2#174]
# **Description**
**Collaboration** Spawn/drop materials on map when enemies are killed (#3).
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151)

In the previous sprints, all materials available for drafting have been provided in the inventory for the purpose of demonstration. But in this sprint, all materials will only fall when the enemy is killed. This will greatly improve the playability of the game. This feature will have a strong relationship with when the enimies system. Different enimies will drop different materials. For example, a level one enimy will only drop one wood, and only the big boss will drop gold or platinum and etc.

Team four previously enabled materials to be picked up from the map which was changed this sprint to be materials.
 
## **Example (optional)**
<img width="383" alt="image" src="https://user-images.githubusercontent.com/109886027/190595679-06eb5dd5-b06a-4728-9226-b8720e2eba8a.png">

# **Dependencies**

- [ ]  #161 
- [ ]  #160
- [ ]  #156
- [ ]  #147
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Drop any materials when enimies are killed (Sept. 20)
- [ ] Killing specific enemies will drop specific items (Aug. 24)
- [ ] Documentation of this task on wiki. (Sept. 27th)
- [ ] Link picked materials with inventory. (Sept. 26th)
 
**Completion Deadline:** Sept. 28th

 
# **Documentation**
-  [Materials-Dropping-System-Code-Implementation ](https://github.com/UQdeco2800/2022-studio-2/wiki/Materials-Dropping-System-Code-Implementation)
# **Member**
- Rohan Kollambalath (@rkoll55 ) 
- Eugene (@eugene2341 )

**Comment by rkoll55** [comment]
Eugene will help with the collection of materials from the map as it was previously done by team 4

**Comment by eugene2341** [comment]
Yes i helped.
