### ISSUE TITLE
Key Binds Menu

### ISSUE THREAD

**Issue by cluanzon** [UQdeco2800/2022-studio-2#176]
# **Key Bind Menu**
**Task:** [Key Bind Menu](#3).
**Feature:** [Pause Screen] (#83)

The key tutorial is an image that will be overlaid / displayed on the pause / main menu (to be discussed with other teams). It will display the key binds used and assigned in this game that will allow the user to play the game smoothly. 
 
## **Examples**
- **Inspirations**: How to play screen

![how to play ](https://user-images.githubusercontent.com/110017386/190834574-e7946648-b7e6-49e0-97e0-bff57df1327c.png)

- **Inspiration 2**: Button that will direct the user / show a pop up image, informing the user on how to play the game.
![image](https://user-images.githubusercontent.com/110017386/190834607-4b867eea-0417-4e70-9359-5dd15bfe45ae.png)

# **Dependencies**
- Pause Screen (#83)

 
# **Milestones**

- [x] User testing on where to have the how to play information (+ Ask teams what key binds they are using) [Sept. 18]
- [x] Create initial designs [Sept. 20]
- [x] Conduct a user testing for design improvements [Sept. 22]
- [x] Implement the code to the game [Sept. 24]
- [x] Ensure that it is fully functional / Debug the code if needed [Oct. 2]

**Completion Deadline:** Oct. 3

# **Documentation**
[Key Bind (Wiki Page)](https://github.com/UQdeco2800/2022-studio-2/wiki/Key-Binds-Menu)
 
# **Member**
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)
