### ISSUE TITLE
Skill Tree Implementation

### ISSUE THREAD

**Issue by cluanzon** [UQdeco2800/2022-studio-2#177]
# **Skill Tree Implementation**
**Task:** [Task Name](#177).
**Feature:** Loading, Death, and Win Screen Implementations and Support (#168)

As the player progresses throughout the game, their ability will evolve with the aid of a skill tree. The basic design of the skill tree was achieved in sprint 2 by team 8 (#114) (See documentations for the designs). This ticket focuses on displaying the skill tree in the game and ensuring that it is functional and intuitive. This task will also allow collaboration between team 6 and 8 to implement a functional skill tree in the game. 

# **Dependencies**
- [ ] #167

# **Milestones**
- [ ] Finalising the skill tree design and its components (Sep. 20)
- [ ] Implementing the designs and its features into the game (Sept. 24)
- [ ] Debugging / Ensuring there is no issues when merging to main (Oct. 1)
 
**Completion Deadline:** Oct. 1

# **Documentation**
- [Skill Tree Wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/Skill-Tree#icons-for-skill-tree)
- [Skill Tree 2 Wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/Skill-Tree_2)
- [Skill Tree 3 Wiki](https://github.com/UQdeco2800/2022-studio-2.wiki.git)

# **Members**
_Team 6_
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)
- Hao Yang Wu (@whyhlf)
- Jingyi Luo (@Nolandluo)
- Yin Fang (@aalice23)
- Chaitanya Dasi Luanzon (@cluanzon)

_Team 8_
- Kurt Lucas (@kurt-553)
(To be updated)

**Comment by cluanzon** [comment]
Updating Documentation - Adding the wiki pages for the skill trees designed in sprint 2
