### ISSUE TITLE
Weapon Attack Animations

### ISSUE THREAD

**Issue by madifeddema** [UQdeco2800/2022-studio-2#178]
# **Description**
**Task:** [Weapon Attack Animations](#3)
**Feature:** [Augmenting and capabilities of the weapons](#150)

The aim of this task is to create the remaining animations for the weapons in the game. While in the previous sprint we animated two of the weapons for the game, the goal will be to do this for the other weapons. These weapons include:

- Trident
- Dagger
- PVC Pipe 
- Plunger  
- Sword

This is essential to the game because it adds to the game aesthetics and visual demonstrates the 'attack' functionality in the game. In order to complete this task the assigned team members will each need to complete sketches followed by user testing and  then implement the changes before finalising the design of each animation. 
 
## **Example (optional)**
Inspiration of different animation styles for weapons:

![A3](https://user-images.githubusercontent.com/55269390/190855443-87f027ba-4660-48f2-9e7c-6ea811f8cf6d.gif)

# **Dependencies**
No dependencies exist for this task.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Background research (Sept. 19)
- [x] User testing prior to the creation of animations (Sept. 20)
- [x] Sketches (Sept. 25)
- [x] Draw the pixel animations (Sept. 27)
- [x] Survey for user feedback (Oct. 02)
- [x] Amend changes (Oct. 03)
- [x] Compile all items together into a single atlas file and name items accordingly (Oct. 05)

**Completion Deadline:** Oct. 05
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Caleb Ang, @PurrplePandaa
- Nisha Vashist, @NishaVashist0
- Madi Feddema, @madifeddema
