### ISSUE TITLE
[Task] Crafting System and Pause Menu JUnit Test & Wiki 

### ISSUE THREAD

**Issue by EverittZ** [UQdeco2800/2022-studio-2#179]
# **Description**
**Task:** [Crafting Refinement JUnit Test & Wiki](#90 ).
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151 )

Write JUnit Test for the code in sprint 3 and Complete the Junit Test that was not completed in Sprint 2 . Complete all design and code wiki page structure and layout make it easy for other members to fill in.
 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Wiki page  page structure and layout (Sept. 25)
- [x] Spawn Materials On Map System Junit test(Sept. 28)
- [x]  Junit Test Test plan (Oct. 3)
- [x] Pause Screen Junit test (Oct. 3)
- [x] Crafting system Junit test(Oct. 2)
- [x] Crafting System UML(Oct. 2)
- [x] Pause Screen UML(Oct. 2)

 
**Completion Deadline:** Oct. 3

# **Documentation**
- [Crafting Contents Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-Contents-Page)

 
# **Member**
- Zhihao Zhang(@EverittZ ) (EverittZ)
