### ISSUE TITLE
[Task] Creation of new projectile weapon 

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#180]
# Description
Task: Create a graphical representation of a level 2 ranged weapon
Feature: Combat Items #150 

The task is to generate a graphical image for a projectile level 2 item - a bow. Research will need to be conducted to suit the Greek Mythology theme this game is currently set within. Such information could take the form of choosing the colour scheme, size, weight, and rarity of the bow to be implemented. From here, bow sketches will need to be viewed first to get a better understanding of what kind of bows could be implemented. Upon creation of all sketches, one (or a collation of multiple ideas) should be selected and implemented on a graphical level through pixelated art. User research will be conducted on users who are familiar with video games to understand what they think of the weapon created. From this changes will be implemented to iterate the design.

## Example
Below are some examples and inspirations of the bows briefly viewed.
![Bow](https://user-images.githubusercontent.com/109809229/190883759-61c4bdab-7c04-4b8b-b6d6-45aa8157740e.png)
![bow2](https://user-images.githubusercontent.com/109809229/190883760-d9b0cb1a-8c20-4b98-9845-430b829bc395.png)

# Dependencies
As of now, there are currently no dependencies for this task. 

# Milestones
List of steps that need to be completed for this task.

- [x] Complete Initial background research (Sept. 18)
- [x] Sketches completed (Sept. 19)
- [x] Pixel art graphical representation completed (Sept. 20)
- [x] User testing created and tested (Sept. 22)
- [x] Pixel art graphical representation iterated (Sept. 25)

_Note: The last two milestones could be repeated until the appropriate outcome is desired._

# Documentation
- [Bow Plunger](https://github.com/UQdeco2800/2022-studio-2/wiki/Bow-Plunger)

# Member
- Caleb Ang (PurrplePandaa) (Caleb Ang)
