### ISSUE TITLE
Creation of buff aura animations on weapon/player 

### ISSUE THREAD

**Issue by NishaVashist0** [UQdeco2800/2022-studio-2#181]
# **Description**
**Task:** Creation of buff aura animations on weapon/player r (Oct .02)
**Feature:** Augmenting and capabilities of the weapons (#150)

This task aims to create a sprite animation of the buff auras for the weapon attacks.  This would place more of a reward system into the game, in hopes of giving more motivation to the player to keep playing the game. The [buff icons](https://github.com/UQdeco2800/2022-studio-2/wiki/Buffs-&-Debuffs) created in sprint one are what activate the buff on the weapon. Within that sprint, the statistic of the effect the buff had was defined.  The animations will continue on from this. 

Animations should be sketched out before drawing and should adhere to aspects of previous designs created – that is adhering to the overlay effect of elements such as skills, and combat item animations. Upon completion, the animation is to be exported as multiple .png files ready to be implemented into the game. 

 
## **Example (optional)**
![buffinspo](https://user-images.githubusercontent.com/109975114/190883325-c0b850e9-503c-4fce-85e4-b939b7b83466.gif)
![buss inspo 3](https://user-images.githubusercontent.com/109975114/190883505-f0ced946-3530-4cda-9c70-0fa6bb987950.gif)

# **Dependencies**
This ticket heavily relies upon completing our Weapon Attack Animations #178 as the buff animations build upon the weapon animations. 

e.g.
- [ ] Swing of weapon animations needs to be created 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x]  Background research (Sep 20th)
- [x] User testing on the expectation around aura animations (Sep 21st)
- [x]  Sketches (Sep 24th)
- [x]  Make the pixel art (Sep 28th)
- [x] User test on the pixel art (Sep 29th)
- [x] Amend changes (Oct 1st) 
- [x] Compile aura attack animations together into a single atlas file and name items accordingly (Oct 2nd)

**Completion Deadline:** Oct 02. 
 
# **Documentation**
- [Main description of feature](../wiki/Feature)

# **Member**
- Caleb Ang, @PurrplePandaa
- Nisha Vashist, @NishaVashist0
- Madi Feddema, @madifeddema
