### ISSUE TITLE
<Task> Crafting Visual Indicators

### ISSUE THREAD

**Issue by lyphng** [UQdeco2800/2022-studio-2#183]
# **Description**
**Task:** [Adding visual indicators for weapons being crafted](#183).
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151)

When a weapon is crafted, display a pop up that shows the user which weapons have been crafted.
 
# **Dependencies**
- [x] [Task] Design of Crafting Visual Indicator (#185)

# **Milestones**
- [x] Add functionality to detect weapons that are crafted (Sept. 24)
- [x] Store number of weapons that have been crafted in each session (Sept. 26)
- [x] Display information on the menu for the user (Sept. 30)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- [Crafting System Code Implementation](../wiki/Crafting-System-Code-Implementation)
 
# **Member**
- Ly Phung (@lyphng)

**Comment by lyphng** [comment]
commits: https://github.com/UQdeco2800/2022-studio-2/commit/40db46c3ccf48a689d80157b6d267fa798c33c4e
