### ISSUE TITLE
<Task> Implement a Different Crafting Menu and Table For Each Map

### ISSUE THREAD

**Issue by lyphng** [UQdeco2800/2022-studio-2#184]
# **Description**
**Task:** [Implement a Different Crafting Menu and Table For Each Map](#184).
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151)

When the user moves to a different map, a different crafting table design will be spawned. When they open the crafting menu, they will also see the corresponding menu for each map. This is to fit with the overall theme of each environment.

# **Dependencies**
- [x] Level 2 Base Map Implementation (#126)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Detect which map the user is on (Sept. 24)
- [x] Set different cases for each map to spawn different crafting table designs (Sept. 26)
- [x] Set different cases for each map to spawn different crafting menu designs (Sept. 30)
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Crafting System Code Implementation](../wiki/Crafting-System-Code-Implementation)
 
# **Member**
- Ly Phung (@lyphng)

**Comment by lyphng** [comment]
commits:
https://github.com/UQdeco2800/2022-studio-2/commit/e0a91ea758a4fd819cf65305865dbacd28d2c5bd
https://github.com/UQdeco2800/2022-studio-2/commit/38293025ed3bec58464734930099717d9c30c0a9
