### ISSUE TITLE
[Feature] Create more potions with diffrent effects

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#187]
# **Description**
**Feature:** [Create more potions with diffrent effects](#187)

In sprint 3, we will design and implement more potions with different effects.

# **Milestones**
List of sub-features you intend to have done and in Main by the end of the sprint.
- [x] Design potions (Sep. 19)
- [x] User testing (Sep. 21)
- [x] Implement potions (Sep. 21)
- [x] Implement unit tests(Sep. 25)
- [x] Documentation on wiki (Sep. 30)

**Completion Deadline:** Oct 1

# **Documentation**
- [Main description of feature](../wiki/Potions)
- https://github.com/UQdeco2800/2022-studio-2/wiki/New-Potions

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
- Anders Jepsen (@0ceanfloor)
- Lachlan McDonald (@Lukeyone)
