### ISSUE TITLE
<Task> Implement unequip for weapon/armour

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#188]
# **Description**
**Task:** [Implemente unequip for weapon/armour](#188)
**Feature:** [Inventory interactions and refinements ](#149)

In the previous sprints, the inventory is only capable of equipping weapon/armour to the player but not unequipping them. In sprint 3, I will implement the unequip method that allows the player to unequip the equipped items.
 
# **Milestones**
- [x] Implement the unequip weapon/armour (Sep. 16)
- [x] implement unit tests (Sep. 23 )
- [x] documentation on wiki (Sep. 24)

**Completion Deadline:** Sep.25

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
