### ISSUE TITLE
<Task> Design the button of inventory menu

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#189]
# **Description**
**Task:** [Design the button of inventory menu](#189 )
**Feature:** [Inventory interactions and refinements](#149 )

Design the button which in the inventory menu, let these buttons fits to the inventory and game
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Draft for the button (Sep. 17)
- [x] Finalize the design (Sep. 19)
- [x] Implement to the game  (Sep. 21)
- [x] User test (Sep. 23)
 
**Completion Deadline:** Sep. 23

# **Member**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
