### ISSUE TITLE
Create Crafting Logic

### ISSUE THREAD

**Issue by rkoll55** [UQdeco2800/2022-studio-2#19]
# **Description**
**Task:** [Create Logic Behind Crafting](#3).
**Feature:** [Crafting System](#4)

A new class named crafting will be created which will host all the methods. Combinations class will hold logic to make each item (wood + steel = sword for this sprint) and will also contain event handlers for clicks made by the user. The class will also determine what items are shown on the menu and updates when user clicks on items. Class will also check if user has required resources for the crafting (will always return true this sprint). 

Integration with weapons and inventory classes will not be done this sprint.
 
## **Example (optional)**
- **Craft Sword**: Players can craft the sword using the menu and have it put in their inventory

# **Dependencies**
This task will require an inventory to be partially present to check for resources. It will also require the display to work in order to get user inputs.

- [x] Inventory class will be needed to check for resources(#xx)
- [x] Visual display will need to work for event handlers to get inputs (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Class structure defined(Aug. 19)
- [x] Logic to craft sword complete(Aug. 20)
- [x] Logic to check inventory complete (Aug. 23)
- [x] Event handlers to check users clicks complete (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- Crafting System Layout (../wiki/Crafting System Layout)

# **Member**
- Rohan (rkoll55)

**Comment by rkoll55** [comment]
@notalie @BozenX
