### ISSUE TITLE
<Task> Quickbar Redesign

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#190]
# **Description**
**Task:** [Quickbar Redesign](#190 ).
**Feature:** [Inventory](#9 )

The quickbar storage content has changed, so it has been redesigned and the appearance has been improved
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] discussion how to redesign (Sep. 19)
- [x] Redesign the quickbar (Sep. 20)
- [x] Implement to game (Sep. 22)
- [x] User test (Sep. 23)
 
**Completion Deadline:** Sep. 23
 
# **Member**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
