### ISSUE TITLE
<Task> Implemente equipable display

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#192]
# **Description**
**Task:** [Implemente equipable display](#192)
**Feature:** [Inventory interactions and refinements](#149)

The current inventory display method allows the player to display items in the inventory and equip the items. Once an item is equipped, stats are changed but there is no visual feedback to the plater. In sprint 3, we will implement the display method to display all the equipped items.
 

# **Milestones**
- [x] Implement equipable display (Sep. 20)
- [x] Implement unequip button (Sep. 21)
- [x] documentation on wiki (Sep. 24)

**Completion Deadline:** Sep.24

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
