### ISSUE TITLE
[Collaboration] Work with Team 3 to determine if entity exists

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#193]
# **Description**
**Task:** Collaborate with team 3 to determine if an entity exists in the game
**Feature:** [Enemies](#147 )

Since the user has to beat the level 1 boss to be able to advance onwards to level 2, Team 5 requires a conditional check to see if Level 1 boss is alive or not. Hence, collaboration with team 3 (enemies) is necessary in order to develop a method that returns the desired value of True or False which ultimately allows the player to progress the game. 
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Explore how to select the specific entity (Sep. 20)
- [x] Develop a method that checks if the entity is placed on map (Sep. 21)
- [x] Implement the conditional in the method that allows the user to transition between levels (Sep. 22)
 
**Completion Deadline:** October 4th

# **Documentation**
- [Enemies feature page](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
- [Map transition](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Transition-Design)
 
# **Member**
- Team 3
- Team 5

**Comment by c-alsop** [comment]
In ForestGameArea.java I have created a method getHeracles() which will let you select Heracles the level 1 boss. I have also created ifHeraclesOnMap() which will let you check if Heracles is placed on the map. That is also in ForestGameArea.java, and finally, in Entity.java there is a method isDead() which will return true if an enemy is dead. This can be used for checking if Heracles is dead.

**Comment by c-alsop** [comment]
These methods have been uploaded to main.

**Comment by IshaanM8** [comment]
Thank you, I will be incorporating the ForestGameArea.ifHeraclesOnMap() method to see if the boss exists or not, much appreciated!
