### ISSUE TITLE
Timestop Ultimate Implementation

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#194]
# **Description**
**Task:** [Add timestop functionality for the ultimate skill](#3).
**Feature:** [Skill tree and Skills](#2)

The timestop functionality will be the ultimate final-tier skill for the game, which should allow the player a very powerful skill to help with combat during harder levels. This will involve time stopping all non-player related game entities. There will also be a white flash over the full screen when the player starts the timestop ultimate.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Timestop Animation (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement timestop functionality for pausing game entities (21 Sep.)
- [ ] Implement full screen white flash (28 Sep.)
- [ ] Implement full timestop skill linkage with PlayerSkillComponent Class (28 Sep.)
 
**Completion Deadline:** 28 Sep.
 
# **Documentation**
- [Skills](../wiki/Skills)
 
# **Member**
- Kurt (@kurt-553) (Kurt Lucas)
