### ISSUE TITLE
Implement sound effect for skills, refinements inventory button and create some unit tests.

### ISSUE THREAD

**Issue by TimothyLam123** [UQdeco2800/2022-studio-2#195]
# **Description**
**Task:** [Implement sound effect for skills, create some unit tests and functions for inventory button](#3).
**Feature:** [skills' sound effect, unit test, button function](#2)

Create and Implement sound effects for most of the skills that we've already have. Create or revise functions for image button in inventory. Create some unit tests to test InventoryComponent file. Create or revise functions for image button in inventory.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create or find some sound effects. 
- [x] Implement sound effect to current skills in game 
- [x] dispose image button in inventory when player click one of them.
- [x] test functions in InventoryComponent
 
**Completion Deadline:** 

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name Siu Ming Lam (@TimothyLam123)
