### ISSUE TITLE
Overall Pause Menu Update and Button Interaction

### ISSUE THREAD

**Issue by Rey-666** [UQdeco2800/2022-studio-2#196]
# **Pause Menu Update and Buttons Interaction**
**Task:** [Pause Menu Button Interaction](#3).
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151 )

The pause menu is a newly added feature in sprint 2. But in this sprint, the main task is to make the buttons on the menu work, namely the "Resume" button and the "Exit" button. The two buttons are strongly connected with the `Game pausing` feature, and `main menu`. The player should be able to use the resume button to unpause the game and dispose the pause menu, the exit button should bring the player to the main menu. Additionally, the same task for the level two map as well.

# **Dependencies**

- [x] (#89)
- [x] (#83)
- [x] (#152)
- [x] (#176)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make the resume button work (Sept. 20)
- [x] Connect the controls button to keybind menu. (Sept. 25)
- [x] Make the exit button work (Sept. 21)
- [x] Update the level two pause menu in level 2 map. (Oct. 1)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
[Pause Menu Button Interaction Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Pause-Menu-Button-Interaction-Code-Implementation)
 
# **Member**
- Yingzheng Cai (@Rey-666  (Rey-666)

**Comment by IsaacGraham128** [comment]
Hey @Rey-666, I've added some additional functionality to now include the key binding aspect of the pause menu. I have also taken the liberty of changing some aspects of the OpenPauseComponent.java, GameAreaDisplay.java, and KeyboardPlayerInputComponent.java elements of your pause functionality to make things a little easier to run / use.
