### ISSUE TITLE
<Task> Implemente inventory display update

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#197]
# **Description**
**Task:** [Implemente inventory display update](#197)
**Feature:** [Inventory interactions and refinements ](#149)

In sprint 3, I will implement method that updates the inventory pop-up menu when any changes has been made to the inventory items.
 
# **Milestones**
- [x] Implement the inventory display update (Sep. 20)
- [x] implement unit tests (Sep. 23 )
- [x] documentation on wiki (Sep. 24)

**Completion Deadline:** Sep.25

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
