### ISSUE TITLE
[Collaboration] Team 9 & Team 5, request a method to detect the current map.

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#199]
# **Description**
**Task:** Team 9 & Team 5, request a method to detect the current map.

Making a method to detect which map the player is on. The method should return a value that uses to check the condition for the current map, some of the entities spawn will rely on this condition.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Figure out the class to have this method (Sep. 19)
- [x] Apply the code (Sep. 21)
- [x] Test and feedback (Sep. 21)
 
**Completion Deadline:** Sep. 21
 
# **Member**
- Yibo Liu(@rlybgithub )
- Ly Phung (@lyphng)

**Comment by lyphng** [comment]
i'm trying to test which map the player is on in the GameAreaDisplay class but im not sure how to call the method do u hv any idea?

**Comment by rlybgithub** [comment]
Hi Lyphng, I have created a method under GameAreaDisplay class. So now if you want to operate in GameAreaDisplay, you can call getGameAreaName() to get a return string of the current map names which were set in ForestGameArea and the UndergroundGameArea. if the current map is level one it will return "Forest" and "Underground" for level two, I have checked with the logger, should be working fine.

Please feel free to contact me if you can have any further questions.
