### ISSUE TITLE
[Task] Play the attack animation dependent on the currently equipped weapon

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#200]
# **Description**
**Task:** #200
**Feature:** #150 

This task involves harmonising the various animations which will be created for each weapon, ensuring that the corresponding attack animation is played dependent on the weapon that is equipped.

## **Example (optional)**
- **Attack animation**: If dagger level one is equipped, play the corresponding animation for dagger level one.

# **Dependencies**
- [x] #178 - Animation for weapons needs to be created before it can be implemented into the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create function/method that tests to see what weapon is currently equipped
- [x] Based on the weapon equipped, place a still image of the weapon on the player's hand
- [x] Based on the weapon that is equipped, play the associated attack animation for that weapon when SPACE is pressed
- [x] Only play attack animation if the player attack status is current
- [x] Dispose animation when weapon is unequipped
- [ ] Write visual test inspection guide
 
**Completion Deadline:** Sept. xx
 
# **Documentation**
- [Attack function](https://github.com/UQdeco2800/2022-studio-2/wiki/Attack-function)
 
# **Member**
- Lachlan Benson (@LachlanBenson ) (Lachlan.Benson#4926)
- Eugene Chong (@eugene2341 ) (gene#0005)
- Nisha Vashist (@NishaVashist0 ) (Nisha Vashist #4270)

**Comment by LachlanBenson** [comment]
Attack animation now plays based on the weapon that the player is holding in their hand

Still to do - make a still image appear of the weapon before pressing attack

**Comment by LachlanBenson** [comment]
Attack animation now plays when weapon is equipped. Figured this was acceptable rather than a still image - just means the player tests out the weapon when they equip it.

Would like assistance from someone with disposing of the weapon atlas upon "unequip" or "drop"

**Comment by LachlanBenson** [comment]
hey @PeterOu8 are you able to assist with the final coding-related item for this task?

- [ ] Dispose animation when weapon is unequipped

**Comment by PeterOu8** [comment]
> 

Sure thing!

**Comment by PeterOu8** [comment]
The animation will be correctly disposed of after unequipping now.

**Comment by LachlanBenson** [comment]
Currently, animation is played based on weapon, plus the associated buff effect. will need to see how this works with stationary animation.

**Comment by LachlanBenson** [comment]
> The animation will be correctly disposed of after unequipping now.

thanks Peter!
