### ISSUE TITLE
Implement projectile functionality for ranged weapons

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#202]
# **Description**
**Task:** #202 
**Feature:** #150 

This sprint, our team aims to implement a ranged attack ability for the player, to assist them with fighting ranged enemies and thus improve game balance. This means implementing code for moving an object across the map in a straight line, and that when the projectile hits the enemy, it deals damage.

# **Dependencies**
- [x] #180 - new weapon needs to be designed before the visuals of the attack can be implemented
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write the code base for creating moving projectiles 
- [x] Test the functionality works using a test sprite
- [x] Implement the design of the plunger projectile from the design team to fire upon attack
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Attack function](https://github.com/UQdeco2800/2022-studio-2/wiki/Attack-function)
 
# **Member**
- Lachlan Benson (@LachlanBenson ) (Lachlan.Benson#4926)
- Eugene Chong (@eugene2341 ) (gene#0005)

**Comment by eugene2341** [comment]
This code heavily relies on Skills Team's projectile code written by @kurt-553. Majority of the code will be the same with some changes.

**Comment by kurt-553** [comment]
@eugene2341 and team 4 did great work here. Glad to see you were able to change my code into something new for the game
