### ISSUE TITLE
Implement buff functionality

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#203]
# **Description**
**Task:** #203
**Feature:** #150 

This task involves allowing the players to consume buffs, which will be placed in strategic locations around the map to assist the player in defeating difficult enemies. The buffs that have been created are attack speed, attack damage and fire, for example.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a function which "consumes" the buff and removes it from the map
- [x] Apply the statistic boost that the buff entails
- [x] Apply the visual effect that the buff entails
- [x] Spawn the buffs in strategic locations on the maps
- [x] Write tests
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Buffs and Debuffs](https://github.com/UQdeco2800/2022-studio-2/wiki/Buffs-&-Debuffs)
- [Aura Pickup and Application](https://github.com/UQdeco2800/2022-studio-2/wiki/Aura-Pickup-and-Application)
 
# **Member**
- Eugene Chong (@eugene2341 ) (gene#0005)
