### ISSUE TITLE
<Task> Animate Water graphics for Both Levels

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#204]
# **Description**
**Task:** [Animating Water tiles].
**Works on:** [Level 1 Static Environmental Components](#45) and [Level 2 Map Environmental Components](#136)

Re-iterate on the Static water tiles on both levels to animate them and give a more lively of a feel to the game so it is not too static and there are components on the move so it provides real-time feedback.
 
# **Dependencies**
The implementation of the animation relies on the following tickets to be completed.

- [x] Creation of Base map (#40)
- [x] Implementation of Underground level (#126)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Acquire gif animation of animated water (Sep. 19)
- [x] Explore and learn editor to utilize animation feature (Sep. 20)
- [x] Implement Animation to Level 1 for visual inspection and user testing purposes (Sep. 21)
- [x] Implement the Animation to both levels once they have been enlarged (Sep. 23)
 
**Completion Deadline:** Oct. 4

# **Documentation**
- [Sprint 3 - Water animation](https://github.com/UQdeco2800/2022-studio-2/wiki/Water#sprint-3---water-animation)

# **Member**

- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
- Ishaan Ranade (@IshaanM8)
