### ISSUE TITLE
[Collaboration] Team 8 & Team 5, statues. 

### ISSUE THREAD

**Issue by 45229848** [UQdeco2800/2022-studio-2#205]
Make a statues on the map. This statues will stand somewhere on the map as decoration.
 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] search material (Aug. 21)
- [x] draw by pixel studio (Aug. 23)
- [x] user testing(Aug. 25)
 

 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Yongzhi ZHOU (@45229848 ) (YONGZHI ZHOU)
- Ishaan Ranade (@IshaanM8)

**Comment by 45229848** [comment]
finished

**Comment by IshaanM8** [comment]
Thanks! I will be sure to implement them in the game 👍🏼
