### ISSUE TITLE
<Task> Level 1 Map Expansion

### ISSUE THREAD

**Issue by lonnimm** [UQdeco2800/2022-studio-2#207]
# **Level 1 Map Expansion **
**Task:** [Level 1 Map Exansion](#3).
**Feature:** [World Traversal + Maps](#117)

After receiving user feedback as well as reflecting on the game, it became clear that the map should be expanded for both levels. An expansion of the map will allow for greater game exploration, making the game more exciting and less predictable. The map will be updated in the tile editor and implemented into the game.
 

# **Dependencies**

This task depends on collaboration with other teams based on where they are placing their elements, for example placement of NPCs and collectable items. 

- [ ] Dependency 1 - NPC Team Collaboration (#)

e.g.
- [ ] Analyse original map and sketch new map design based on dependencies.
- [ ] Import map into tile editor and update map based on design sketches.
- [ ] Undertake user testing to determine how effective the new map design is.
- [ ] Update map based on feedback and implement to game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Map plan/sketched design
- [ ] Map creation on tile editor
- [ ] Updated map user testing
- [ ] Implement new map to game
 
**Completion Deadline:** Sept. 28

 
# **Documentation**
- [Map Layout Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Layout-Design)
 
# **Member**
- Lonni (@lonnimm) (Lonni Miller-Metzner)
