### ISSUE TITLE
[Collaboration] Team 7 X Team 5 Map Expansion Design Collab 

### ISSUE THREAD

**Issue by lonnimm** [UQdeco2800/2022-studio-2#208]
# **Team 7 X Team 5 Map Expansion Design Collab **
**Task:** [Team 7 X Team 5 Map Expansion Design Collab ](#3).
**Feature:** [World Traversal and Maps](#117)

In order to ensure that the map expansion is suitable to incorporate into the game and aligns with components and story elements of other teams, cross-team collaboration is essential. This will create a cohesive game experience. 
 

# **Dependencies**
This task depends on the expanded map design. 

- [ ] Level 1 Map Expansion(#207 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - Plan within team 5 (Sept. 19)
- [ ] Step 2 - Discuss and collaborate with team 7 (Sept. 21)
- [ ] Step 3 - Implement ideas and feedback from the collaboration session (Sept. 28)

 
**Completion Deadline:** Sept. 28

# **Member**
- Lonni Miller-Metzner (@lonnimm) (Lonni Miller-Metzner)
- Monita Megaele (@MonitaMegaele) (Monita Megaele)

**Comment by MonitaMegaele** [comment]
Hello, I have mapped out the NPC placements on the new map expansion. Could you have a look and double check it does not interfere with Enemy rooms/ Boss room? [Image of Placements](https://cdn.discordapp.com/attachments/1005678711288377384/1026145014625079367/mapwithnpcplacements.png)
