### ISSUE TITLE
Voice Overs

### ISSUE THREAD

**Issue by uq-haze** [UQdeco2800/2022-studio-2#209]
# **Description**
**Task:** Creating Voices Overs in the game
**Feature:** [NPC + Dialogue](https://github.com/UQdeco2800/2022-studio-2/issues/148)

Creating and Implementing Voice Overs into the 'Atlantis Sinks' Game. This will consist of different voice overs for NPCs depending on the characteristics of each NPCs. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Creating Lines for each different NPCs [Sep 20]
- [x] Step 2: Creating different voice overs for different NPCs [Sep 25]
- [x] Step 3: Implement the voices into the game [Sep 26 ]

 
**Completion Deadline:** Sep 26

# **Documentation**
[Dialogue + NPC](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs)

 
# **Member**
- Hazeem bin Suffian @uq-haze 
- Pengxu Chen @viachen1 
- Monita Megaele @MonitaMegaele
