### ISSUE TITLE
<Task> Level 2 Map Expansion

### ISSUE THREAD

**Issue by Abi-B-28** [UQdeco2800/2022-studio-2#214]
# **Expanding the level 2 map (from Sprint 2)**
**Task:**[Level 2 Map Expansion](#3).
**Feature:** [World Traversal + Maps](#117 )

Expanding the level 2 map from Sprint 2, especially enlarging the map size and ensuring that it appropriately considers the rest of the teams and their components, for example, enemies and story for team progression.
 
## **Example (optional)**
- **Spawn**: Have a specific spawn area where the player will load in instead of just randomly on the map. 
- **Items**: Items team want to place certain items in a specific area.
- **Enemies**: Enemies team needs a certain layout.

# **Dependencies**
- [x] Collaboration with other teams to discuss their needs in relation to the map layout.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Discuss with other teams (Sep. 25)
- [x] Create map layout options on tile editor and user test (Sep. 27)
- [x] Finalise map layout and items (Sep. 29)
- [x] Implement Animations (Oct 2.)
 
**Completion Deadline:** Oct 4
 
# **Documentation**
- [Map Layout Level 1](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Layout-Design#map-expansion)
- [Map Layout Level 2](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Layout-Design-Level-2#sprint-3---lvl-2-map-layout-enlargement)
 
# **Member**
Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
Ishaan Ranade (@IshaanM8)
