### ISSUE TITLE
<Task> Implemente swap method for Weapon/Armour

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#216]
# **Description**
**Task:** [Implemente swap method for Weapon/Armour](#216)
**Feature:** [Inventory interactions and refinements ](#149)

In the previous sprints, the inventory is only capable of equipping/unequipping weapon/armour to the player but not swapping them. In sprint 3, I will implement the swapItem() method that allows the player to quickly swap their items.
 
# **Milestones**
- [x] Implement swapItem (Sep. 26)
- [x] implement unit tests (Sep. 28 )
- [x] documentation on wiki (Sep. 29)

**Completion Deadline:** Sep.30

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
