### ISSUE TITLE
[Collaboration] Fix the bug of the game crashing when opening the crafting table in the level two map

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#217]
# **Description**
**Task:** Fix the bug of the game crashing when opening the crafting table in the level two map

This is a collaboration ticket which is a bug report from Team 9. When the player tries to open the crafting table on the level two map, the game will be crashed. Team 5 will work out with Team 9 to find out the problem and fix this bug.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Report the bug (Sep. 26)
- [x] Find & fix the bug (Sep. 28)
- [x] Test and feedback (Sep. 29)
 
**Completion Deadline:** Sep. 29
 
# **Member**
- Yibo Liu(@rlybgithub )
- Ly Phung (@lyphng)

**Comment by lyphng** [comment]
hey @rlybgithub ! There's been a problem with the lvl 2 map where it crashes when I try interacting with things like opening the crafting menu, killing enemies, etc., do you have any idea why this might be happening?

**Comment by lyphng** [comment]
oh btw I modified your GameAreaDisplay function slightly so instead of the
ServiceLocator.registerCraftArea(this);
line being in that function its in create() instead. Just wanted to check if this would interfere with anything in your code before I push it? I ran it n everything works fine on my end

**Comment by rlybgithub** [comment]
Hi, The modification on GameAreaDisplay seems all good to me.

Moreover, I have fixed the issue of the crash in level two when opening the crafting table. Thanks for reporting the issue! it should be alright now. The problem was missing some image assets of the crafting system in the Underground file.

**Comment by lyphng** [comment]
Awesome tysm! I'll close the ticket then since it's now resolved :)
