### ISSUE TITLE
<Task> create sound effect to skills and implement into game, create some unit test to test inventoryComponent

### ISSUE THREAD

**Issue by TimothyLam123** [UQdeco2800/2022-studio-2#219]
# **Description**
**Task:** create sound effect to skills and implement into game, create some unit test to test inventoryComponent.
**Feature:** [Inventory interactions and refinements](#149)

Create sound effect to skills that have already been in the game and implement them. Help the team to create some unit test to test funtions in inventoryComponent
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] create or find appropriate sound effect
- [x] implement sound effect to game
- [x] create unit test

# **Member**
- Siu Ming Lam (Timothy_Lam123) (Siu Ming Lam)
