### ISSUE TITLE
[Feature] Map + Environment Interaction

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#22]
# **Description**
The Map / Environment feature is going to be a team-based component of the game that will be custom developed to suit the theme of Atlantis. The map is going to be a fundamental dependency on many aspects of the game as the player, NPCs, items and interactive objects are going to be placed on the map itself. The map also contributes to the emotional experience the user will face, affect their gameplay and also contain a foundation for further display of graphics such as explosions, special effects, particles and much more.

## SubFeature/component (optional)
Base Map(e.g. different textures of terrains like sea, plains, forest, etc.)
Environment components for appearance(e.g. trees, building components, etc.)
Environment Interaction to trigger events when arriving in certain locations(e.g. move to next stage, get buff or debuff, etc.)

## **Examples (optional)**
- **Live Map:**
The camera follows users as they navigate/move around OR Obvious scene changes from one level/stage to another 
Players can move around the map (freely/restricted by stages/level)
- **Mini Map:**
On click -> the whole map can be viewed - enlarged/overlay
An indication of where the player is on the map
Could possibly implement a drag interaction on the mini-map (unless it’s always displaying the full map)
Could mark certain locations, discovered/undiscovered
- **Environment Interaction:**
User is able to interact with certain objects or NPCs -> text pop-ups?
The player is unable to go through certain blocks (buildings/ walls etc.). 
Players can pick up certain objects and add them to inventory. Or on pick-up -> buff/debuff
The player encounters enemies at certain locations on the map.

# **Dependencies**

This feature doesn’t have any dependencies, however many other features will be dependent on the map in order to be implemented, so it is critical to be able to offer a minimum viable product early in the process for their reference. 

# **Milestones**
**Sprint 1
Week 4 - 17th August**
- [x] Decide what kinds of terrains will be in the game. (Discussion with story team required) 
- [x] Decide the basic components in the corresponding terrains(e.g. the number of trees, ghosts, buildings, etc.)
- [x] Application(s) to use for designing the terrain and other pixelated components

**Week 5 - 22nd August**
- [x] Design the first type of terrain(e.g. images for textures, basic components, etc.)
- [x] Creates samples of terrain(Provide options for the group to choose from for a mainstream style)
- [x] Create a few resource chunks to gather materials from (Visual only not functional)

**Week 5 - 26th August** 
- [x] Implement the first terrain into the game(Coding Side)
- [x] Implement Wood and Steel resource chunks(Tree and Rock - Coding side) 
****
****Completion Deadline:** Aug. 30**

# **Extras (optional)**
- **Minimap:** Compressed version of the map to provide the user with an overall view of their position
- **Hidden rooms:** Sort of like an easter egg where upon being found, gives sort of a message and an item of sorts.

# **Documentation**
- [Terrain](https://github.com/UQdeco2800/2022-studio-2/wiki/Terrain)
- [Game Area](https://github.com/UQdeco2800/2022-studio-2/wiki/Game-Areas)
- [Map](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Design)
- [Map System Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-System-Code-Implementation)
# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Name ([@github](https://github.com/github)) ([@slack](https://github.com/slack))
- Otis Carmichael (@Otili9890) (@Otis Carmichael)
- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
- Yibo Liu (@rlybgithub)
- Ishaan Ranade (@IshaanM8) (@Ishaan Ranade)
- Lonni Miller-Metzner (@lonnimm) (@Lonni Miller-Metzner)

**Comment by rlybgithub** [comment]
@notalie @BozenX Please check the feature ticket from team 5, thank you!

**Comment by BozenX** [comment]
looks good!
