### ISSUE TITLE
<Task> Implement Skill Tree

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#222]
# **Description**
**Task:** [Skill Tree Implementation].
**Feature:** [Skill Tree and Skills](#167)

Skill tree will be implemented on a new screen in game, and allows the player to assign skills for use throughout gameplay. These will have to be unlocked with skill points which will be acquired by killing enemies within the game.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Skill Tree Art (#xx)
- [ ] Skill Icons (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Add icon to skill tree button (2/10)
- [ ] Add skill tree image to new game screen (2/10)
- [ ] Add skill tree icons to skill tree as buttons (2/10)
- [ ] Implement image buttons for tree (2/10)
- [ ] Allow buttons to assign skills (2/10)
- [ ] Allow the collection and allocation of skill points for the skill tree (2/10)
 
**Completion Deadline:** 4/10
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Kurt Lucas (@kurt-553 ) (Kurt Lucas)
