### ISSUE TITLE
<Task> Implement Critical Attack, Attack Speed, Invulnerability and Ultimate Skills

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#223]
# **Description**
**Task:** [Implement Critical Attack, Attack Speed, Invulnerability and Ultimate Skills](#3).
**Feature:** [Skill Tree and Skills](#167)

This will implement the remaining skills in the skill tree. The critical attack skill will allow players a damage boost for a short period of time, the invulnerability will grant players a small speed boost and temporary invulnerability, the attack speed skill will allow players a short attack speed boost when activated and the Ultimate skills include the time stop skill and a skill that releases a strong wave of projectiles both of which will be on very long cooldowns.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ]  Design and optimize skill animations and icons (dynamic)  (#173)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement Critical Attack Damage Buff
- [ ] Implement Attack Speed Buff Skill
- [ ] Implement Second Ultimate Skill
- [ ] Implement Time Stop for the timestop ultimate
- [ ] Implement full screeen white flash for timestop ultimate

 
**Completion Deadline:** 2/10
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Kurt Lucas (@kurt-553) (Kurt Lucas)
