### ISSUE TITLE
<Task> Crafting Menu Animations

### ISSUE THREAD

**Issue by lyphng** [UQdeco2800/2022-studio-2#229]
# **Description**
**Task:** [Crafting Menu Animations](#229).
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151)

Animations for the crafting menu. This includes animations for the visual indicators and a pop up that shows the user when a weapon has been crafted. 

# **Dependencies**
- [x] Crafting Visual Indicators (#183)
- [x] Design of Crafting Visual Indicator (#185)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add animations for visual indicators (Oct. 1)
- [x] Add animations for the "crafted" pop-up (Oct. 2)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Crafting System Code Implementation Sprint Three](../wiki/Crafting-System-Code-Implementation-Sprint-Three)
 
# **Member**
- Ly Phung (@lyphng)

**Comment by lyphng** [comment]
commits: https://github.com/UQdeco2800/2022-studio-2/commit/9100ccca7d100d7c0b9ea91775e0e9453fcaeb04
