### ISSUE TITLE
<Task> Player Modification Framework

### ISSUE THREAD

**Issue by IsaacGraham128** [UQdeco2800/2022-studio-2#23]
# **Description**
**Task:** [Player Modification Framework](#)

**Feature:** [Story and Player](#5)

Implement the player modification framework. This framework should provide a simple and easily customisable system to externally modify player statistics. This should enable other teams to create features such a buffing and de-buffing mechanics. These modifiers will be able to be coded such that they are either temporary or permanent.

## **Example**
- **Mana mayhem**: On every 3rd spell class the player passively regenerates a percentage of their total mana instantly.

- **Get a move on**: After dodging the player has increased movement speed (+25%) for 3 seconds. 

# **Dependencies**
No other required systems or work to implement as this is purely a player modification framework and all existing systems are already present.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create class that stores modifying targets and modifying values (19 Aug.)
- [x] Create player entity storage for modifiers (21 Aug.)
- [x] Allow modifiers to alter player statistics (26 Aug.)
- [x] Implement modifier lifetime (27 Aug.)
- [x] Create mock modifier that activates on key press and times out after a few seconds (28 Aug.)
- [x] Complete code commenting  (28 Aug.)
- [x] Completed Junit tests for build verification (28. Aug)
- [x] Complete wiki entry for API documentation (28. Aug)
- [x] Merge with main branch
- [x] Include stamina and mana modifications (26. Aug)
- [x] Merge with main branch  (26. Aug)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Player modifier documentation](../wiki/Player_modifier)

# **Member**
- Isaac Graham (@IsaacGraham128) (Isaac Graham)

**Comment by ew-b** [comment]
Completed
