### ISSUE TITLE
[Collaboration] Main Menu Transition Animation Programming

### ISSUE THREAD

**Issue by Rey-666** [UQdeco2800/2022-studio-2#230]
# **Description**
**Task:** [Main Menu Transition Animation Programming](#3)
**Feature:** [Optimisation of Crafting Functionality and Additional Features](#151 )

The main menu transition animation is designed and added in order to make the game more coherent to play. It will also improve the game asethetic at the same time. The task is to play the 84 frames animation when the player click the start button, and then the game will start after the animation ends. At this stage, the player can press the `ENTER` key to skip animation at the end. We will see if there is necessary need to let the game automatically start right after animation ends. The animation will be built based on the [Loading Transition Screen Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Loading---Transition-Screen-Implementation) system made by @IsaacGraham128
 
# **Dependencies**

- [x] (#151)
- [x] (#155)
- [x] (#168)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Understand and modify [Team06's animation system code](https://github.com/UQdeco2800/2022-studio-2/wiki/Loading---Transition-Screen-Implementation).
- [x] Implement the transition animation into the game (Sept. 27)
- [x] Connect the transtion animation with the start button (Sept. 28)
- [x] Bind ENTER key to allow player to skip the transition animation (Aug. 29)
- [x] Debugging (Oct. 1)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- [Main Menu Transition Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Main-menu-transition-code-implementation)
 
# **Member**
- Yingzheng Cai (@Rey-666 ) (Rey-666)
- Isaac Graham (@IsaacGraham128)
- Elias Blanch (@ew-b)

**Comment by IsaacGraham128** [comment]
Thanks for writing up the collaboration ticket <3

**Comment by ew-b** [comment]
For context on the LevelTransition implementation, I created the basics of the classes and methods, Isaac then took over and did the majority of it, it has a problem of lacking the ability to use timers and relies on a button press to change screens when the animation is finished but I am glad it was adapted and used as a template for the main menu!

**Comment by Rey-666** [comment]
The main menu transitioning animation is implemented based on team 06's level transitioning code logics. They have both provided heaps of help along the way either.

**Comment by IsaacGraham128** [comment]
Sprint 3 complete! Woohoo!
