### ISSUE TITLE
NPC test sprint3

### ISSUE THREAD

**Issue by hideonbush-crl** [UQdeco2800/2022-studio-2#232]
# **Description**
**Task:** [NPC test sprint3](#3).
**Feature:** [NPC + Dialogue](https://github.com/UQdeco2800/2022-studio-2/issues/92)

Tested for dialog text loading, changes, item addition, new npc positions and dialog button positions.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] dialog text (Oct.3)
- [x] dialog text changes (Oct.3)
- [x]  item addition (Oct.3)
- [x] new npc positions  (Oct.3)
- [x] dialog button positions (Oct.3)

 
**Completion Deadline:** Oct.3

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Bokai Zhang (@hideonbush-crl ) (Bkai Z#6469)

**Comment by hideonbush-crl** [comment]
done
