### ISSUE TITLE
[Collaboration] Discuss where NPCs and Enemies Go on Map

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#234]
# **Description**
**Feature:** [Enemies](#147)
**Feature:** [NPC](#148)

Need to discuss locations of NPCs and Enemies to make sure there are no double-ups.
 

# **Dependencies**
- [x] Updated maps need to be in game
- [x] Need to have co-ordinates of updated maps

# **Milestones**
- [x] Discuss where enemies and NPCs are going on map
 
**Completion Deadline:** 4th April

# **Documentation**
- [Placing Enemies on Map](https://github.com/UQdeco2800/2022-studio-2/wiki/Placing-Enemies-On-Map)
 
# **Member**
- Caitlenn (c-alsop) (Caitlenn Alsop)

**Comment by c-alsop** [comment]
So we don't accidentally put the enemies and npcs in the same place. Here are our current co-ordinates for the enemies on level 2: (37, 47), (32, 67), (20, 80), (65, 47), (85, 54) and (35, 98)

**Comment by c-alsop** [comment]
And here are the level 1 enemies co-ordinates: (129, 22), (99, 65), (45, 47), (118, 141), (118, 175) and (153, 113). Are these okay or should we change them?

**Comment by MonitaMegaele** [comment]
hold up let me take a look!

**Comment by MonitaMegaele** [comment]
npc positions are (87,29), (33,96), (110, 42), (96,13), (74,122)

**Comment by c-alsop** [comment]
Is that for level 1?

**Comment by MonitaMegaele** [comment]
i think it is seperated quite evenly, only concern being on (99,65) and (96,13) being at a close x axis but it should be fine, the map is pretty large

**Comment by MonitaMegaele** [comment]
yep level 1!

**Comment by c-alsop** [comment]
Okay, I think that is fine. There should be enough space between enemies and NPCs.

**Comment by MonitaMegaele** [comment]
for sure!
