### ISSUE TITLE
[Feature] Enemies (Sprint 4)

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#237]
# **Description**
Continuing to work on the enemy feature. This sprint will involve polishing off the enemies.

# **Milestones**
- [x] Add death animations for enemies
- [x] Change the projectile attack to a multi-projectile attack for Mega Poop (based on prior user testing)
- [x] Do user testing relating to the amounts of enemies on the maps and the locations of those enemies.
- [x] Balancing enemy stats (to better balance the strong weapons and attacks from the player)
- [x] Code clean up and bug fixes

**Completion Deadline:** 18th October

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)

# **Members**
- Caitlenn (@c-alsop) (Caitlenn Alsop)
