### ISSUE TITLE
<Task> Stamina  System Framework

### ISSUE THREAD

**Issue by whyhlf** [UQdeco2800/2022-studio-2#24]
# **Description**
**Task:** [Stamina  System Framework](#24)
**Feature:** [Story & Player](#5)

Implement a stamina system. Stamina slots will affect the player's actions. Once the stamina level drops to zero, players will not be able to perform any actions until they have rested.

 
## **Example (optional)**

- **Fatigue effect**:  When the player’s stamina level falls below a certain value it will reduce movement speed.

# **Dependencies**

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial design of `Stamina System’ created and documented on wiki (Aug. 19).
- [x] Unit tests implemented for `Stamina System` (Aug. 20).
- [x] `Stamina` class implemented and tested (Aug. 23).
- [x] Documentation of `Stamina System` updated on wiki (Aug. 23).

**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Stamina  System Documentation](../wiki/Stamina_System)
- ...
 
# **Member**
- Hao Yang Wu (@whyhlf) (Hao Yang Wu )

**Comment by ew-b** [comment]
Completed
