### ISSUE TITLE
<Feature>Main Menu, Setting and Different Level Map Background Soundtrack

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#245]
# **Description**
Feature: [Main Menu, Setting and Different Level Map Background Soundtrack](#245 )

Redesigned the background sound of the main menu, and made the background sound of the settings page and different map pages.

## **Examples (optional)**
- #84 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Redesign the main menu background soundtrack (Oct. 10)
- [x] Desgin setting and map background soundtrack (Oct. 13)
- [x] Interaction with the main game (Oct. 15)
- [x] User Test (Oct. 16)

**Completion Deadline:** Oct. 16

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
