### ISSUE TITLE
<Task> Implement the Main Menu , Setting and Different Level Map Background Soundtrack

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#246]
# **Description**
**Task:** [Implement the Main Menu , Setting and Different Kevel Map Background Soundtrack](#246 ).
**Feature:** [Main Menu, Setting and Different Level Map Background Soundtrack ](#245 )

A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")
 
## **Example (optional)**
- #128 

# **Dependencies**
A soundtrack will be created based on the story background, map elements, and functionality.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Think about the soundtrack design according story background,map elements and functionality (Oct. 10)
- [x] Make the soundtracks (Oct. 10)
- [x] Implement in game(Oct. 16)
- [x] User Testing (Oct. 17)
 
**Completion Deadline:** Oct. 18
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
