### ISSUE TITLE
<Task> Mana System Framework

### ISSUE THREAD

**Issue by whyhlf** [UQdeco2800/2022-studio-2#25]
# **Description**
**Task:** [Mana System Framework](#25)
**Feature:** [Story & Player](#5)

Implement a mana system. Mana slots will affect the player's actions. Once the stamina level drops to zero, players will not be able to use any skill until the mana been regenerated.

 
## **Example (optional)**

- **Unable to cast spells**:  When the player’s mana level falls below a certain value, the player would not able to use the skill.

# **Dependencies**

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial design of `Mana System’ created and documented on wiki (Aug. 19).
- [x] Unit tests implemented for `Mana System` (Aug. 20).
- [x] `Mana` class implemented and tested (Aug. 23).
- [x] Documentation of `Mana System` updated on wiki (Aug. 23).

**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Mana  System Documentation](../wiki/Mana_System)
- ...
 
# **Member**
- Hao Yang Wu (@whyhlf) (Hao Yang Wu )

**Comment by ew-b** [comment]
Completed
