### ISSUE TITLE
[Task] Updating Current Crafting Designs

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#252]
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features](#247)

# Description
Update and reiterate upon existing designs/animations for the crafting system.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Updates to Design (Oct 9th)
- [x] Further User Testing (Oct 10th)
- [x] Updating Design Based on Feedback (Oct 11th)
- [x] Final Iteration/Implementation (Oct 12th)
 
**Completion Deadline:** Oct 12th
 
# **Documentation**
- TBC
 
# **Member**
- Enoe (Jolo) Gapusan (@jgapusan)
- Emily Southgate (@e-southgate)
