### ISSUE TITLE
[Feature] Visual Skill Cooldowns, Skill Optimisation and Skill Visual Design Improvements

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#253]
# **Description**
This ticket will be the final improvements to the skill system within the studio 2 game. This will include a cooldown system with equipped skills on the main game screen bottom bar, as well as visual improvements to the skill tree and skills.
Another consideration is the improvement/optimisation of user experience for all skills, as some changes made by other teams throughout the 3 development cycles so far have caused some of the skills developed in earlier sprints to not function properly (bleed proc no longer works with all the different types of weapons, and teleport has not changed to meet the recently updated new map size for examples).

## Visual Skill Cooldowns
The skills equipped from the skill tree should be visible on the main game screen UI and the cooldowns for each skill should be visually represented on this screen. This will likely be implemented through a bar with the equipped skills on the bottom of the screen, with overlaid countdowns based on the time remaining on the skill cooldown.

## Skill Visual Design Improvements
The visual elements of the skill tree and skills (such as all of the skill icons, and the skill tree image, as well as the skill tree clear button and background, alongside some missing animations such as for bleed) need user testing/visual updates to make the visual design more consistent with the game vision at this point in production. 

## Skill Optimisation
Optimise cooldowns lengths, and skill functionality. Some key functionality that needs fixing after changes to the game made in previous sprints by other teams:
* Bleed and root proc needs to be tested and fixed
* Teleport functionality needs to be tuned for the new map size
* Add a charge-up to the charge skill
* Add a visual representation to the aoe skill
* Change damage of all skills to better fit within the desired user experience of the game
* Consider changing the skill tree such that some skills cannot be picked if others are picked in code

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Fix bleed proc  (13/10)
- [ ] Fix root proc (13/10)
- [ ] Fix teleport distance (13/10)
- [ ] Finalise skill damage and knockback (20/10) 
- [ ] Add charge-up to dash skill (13/10)
- [ ] Lock skills from activation if other skills being used (eg cannot teleport and ultimate at the same time) (13/120)
- [ ] Update code structure to ensure the correct structure is used for all skills (eg.  movementIsModified() giving correct value in playerSkillComponent) (20/10) 
- [ ] Lock some skills from being equipped if others chosen (13/10)
- [ ] Finalise experience gained from each enemy  (20/10) 
- [ ] Add correct skills to main game screen after equipping (13/10)
- [ ] Add cooldown overlay to skills on main game screen (13/10)
- [ ] Finalise all Skill Icons (20/10) 
- [ ] Finalise Skill tree visual design (13/10) 
- [ ] Finalise skill tree equip UI (20/10) 
- [ ] Add full code coverage (20/10) 
- [ ] Add UML diagrams (20/10) 
- [ ] Finalise Wiki (20/10) 

**Completion Deadline:** October 20th

# **Extras (optional)**

# **Documentation**
- [Skills Wiki](../wiki/Skills)

# **Members**
-Kurt Lucas (kurt-553) (Kurt Lucas)
