### ISSUE TITLE
<Task> Design and Optimise Skill Animations, Icons and Skill Tree Interface

### ISSUE THREAD

**Issue by AndySong-2324** [UQdeco2800/2022-studio-2#254]
# **Description**
**Task:** [Design and optimise skill animations, icons and skill tree interface (Final)](#3).
**Feature:** [Skills](#2)

I will work on the charge skill, area, root, bleed skill and arrow animation by pixel art. Besides, I will not only optimise the skill tree screen section, like changing the screen's background and redesigning the skill tree model but also optimise the skill animations and icons I designed before after user testing. And finally documented most of the skill design part in the wiki at present and got the finalised version in Week 13 stand-up.

# **Dependencies**

# **Milestones**
List of steps that need to be completed for this task.

- [x] Change the background for the skill tree interface (Oct. 18)
- [x] Conceive and design all the skill description images (Oct. 18)
- [x] Conceive and design the animation of the arrow(hint where to place the skill tree icon) (Oct. 18) 
- [x] Optimise the interface for the skill tree (Oct. 18)
- [x] Conceive and design the animation of the area (Oct. 18)
- [x] Conceive and design the animation of bleed skill (Oct. 18)
- [x] Conceive and design the animation of charge skill (Oct. 18) 
- [x] Conceive and design the animation of root skill (Oct. 18) 
- [x] User testing (Oct. 18)
- [x] Conceive and design the new skill tree icon (Oct. 18)
- [x] Optimise the whole design of my part (the animations and icons I completed ) (Oct. 18)
- [x] Document the skill design part in the wiki (Oct. 18)

 
**Completion Deadline:** 18 Oct.

# **Member**
- Zhuohang Song(AndySong-2324) (AndySong)
