### ISSUE TITLE
<Task> Create Cooldown bar which displays cooldowns on equipped skills

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#256]
# **Description**
**Task:** [Create Cooldown bar which displays cooldowns on equipped skills](#3).
**Feature:** [Visual Skill Cooldowns, Skill Optimisation and Skill Visual Design Improvements](#253)

Adding the correctly equiped skills to a bar at the bottom of the screen,will assist the player to know which skills they have equipped to each skill slot, as well as allow us to visually represent cooldown timers on skills.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add correctly equipped skills to cooldown bar (10/10)
- [x] Fix Cooldowns to overlay over the correct skill and countdown for the length of the cooldown (12/10)
- [x] Set correct countdown for cooldowns of countdown overlay (13/10)
 
**Completion Deadline:** 13/10
 
# **Documentation**
- [Skills Wiki](../wiki/Skills)
 
# **Member**
- Kurt (@kurt-553) (Kurt Lucas)
