### ISSUE TITLE
JUNIT Testing for CombatItems

### ISSUE THREAD

**Issue by madifeddema** [UQdeco2800/2022-studio-2#258]
# **Description**
**Task:** JUNIT Testing for CombatItems
**Feature:** [FEATURE] Animation and Combat Items Optimisation #248

This task is about ensuring the code we have implemented into the game has appropriate tests associated with the functionality. Code coverage is specifically important tot he game to ensure there is minimal bugs and that the code is operating as expected. Testing the code for potential invalid input handing as well to minimise the risk of the game crashing. Furthermore to ensure the code is running as efficiently as possible to create a good user experience.
 
# **Dependencies**
There is one main dependency for completing this task:

- [x] Majority of any additional code added to the game should be completed
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write a list of all classes written in the code base (Oct. 10)
- [x] Complete all standard JUNIT tests (Oct. 13)
- [x] Complete any additional mocking tests (Oct. 15)
- [x] Finalise documentation wiki (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [JUNIT Testing](../wiki/Feature)
 
# **Member**
- Madi Feddema (@madifeddema) (madi-feddema#3384)
- Lachlan Benson (@LachlanBenson) (Lachlan.Benson#4926)
- Eugene Chong (@eugene2341) (gene#0005)

**Comment by madifeddema** [comment]
Animation controller class is tested and testing plan created for the final tests, need to confirm those, but will be done shortly
