### ISSUE TITLE
SonarCloud for CombatItems Code

### ISSUE THREAD

**Issue by madifeddema** [UQdeco2800/2022-studio-2#259]
# **Description**
**Task:** SonarCloud for CombatItems Code
**Feature:** [FEATURE] Animation and Combat Items Optimisation (#248)

This task is about ensuring the quality of the code we have implemented into the game. By using the development tool SonarCloud we will analyse any bugs we have created in the game to check the code we have implemented is clean. Additionally we will be looking at all major code smells and minimising any minor code smells that have implemented. Finally, we will check our test code coverage to confirm the tests we have written are aligned with the implementation of the code. This is important to the overall game as going through potential bugs and poor code will optimise the efficiency of the programming and better the user experience for the player.
 
# **Dependencies**
This task relies on:

- [x]  Majority of any additional code added to the game should be completed
- [x]  Majority of JUNIT tests completed
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] check for all bugs (Oct. 11)
- [x] check for all major code smells (Oct. 11)
- [x] analyse whether the minor code smells are impactful and make changes where appropriate (Oct. 12)
- [x] check for code coverage (Oct. 16)
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [SonarCloud](https://github.com/UQdeco2800/2022-studio-2/wiki/Combat-Items:-SonarCloud-Sprint-4)
 
# **Member**
- Nisha Vashist (@NishaVashist0) (nishavashist#4270)
- Madi Feddema (@madifeddema) (madi-feddema#3384)

**Comment by LachlanBenson** [comment]
@madifeddema closing
