### ISSUE TITLE
<Task> User testing and Team Consulataion of Story & Design

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#26]
# **Description**
**Task:** [Consultation and User Testing For Story and Design](#).
**Feature:** [Story and Player](#5)

To ensure the story and design of the game are cohesive and make sense to the developers we will consult with other teams on the design choices we have made to ensure it aligns with their vision and tasks. Team consultation will be done by asking each team in discord and discussing with them. 
We will also conduct user testing regarding the story and design to confirm it meets our target demographic and makes sense. This will be done by showing the storyline and design plan to a potential user, asking them open-ended questions about their initial impression, thoughts on how it fits our targeted themes, and if they have any suggested changes, then conducting a survey that allows for more anonymous honest scaling feedback.

 
## **Example (optional)**
- **User Testing Methods**: Qualitative attitudinal tests and basic opinion testing
https://www.toptal.com/designers/ux/user-testing-methods#:~:text=UX%20user%20testing%20is%20the,surveys%2C%20interviews%2C%20and%20observation.

# **Milestones**
List of steps that need to be completed for this task.

- [x] Create a survey to user test the story and character (Aug. 17)
- [x] User test initial story and character (Aug. 18)
- [x] Initiate consultation of other teams (Aug. 20)
- [x] Create a survey to user test document basics (Aug. 22)
- [x] User test design document basics (Aug. 23)
- [x] Consultation of other teams complete (Aug. 23)
- [x] Make changes and iterate after consultation (Aug. 27)

 
**Completion Deadline:** Aug. 27
- [x] Story tests complete and documentation uploaded to wiki (Aug. 23).
- [x] Consultation of teams complete and all feedback documented (Aug. 23)
- [x] `Design Rule Book` basics finalised (Aug. 23).
- [x] Documentation of `Story and Character Story` updated on wiki (Aug. 27).
 
# **Documentation**
- [Story, character and Design Development](..wiki/Story%2C-Character-and-Design-Development)
- [Design Rule Book](..wiki/Design-Rule-Book)
- [Testing Story and Character Sprint One](..wiki/Testing-Story-and-Character-Sprint-One)

 
# **Member**
- Isaac Graham ([@IsaacGraham128](https://github.com/IsaacGraham128)) - Isaac Graham
- Elias Blanch ([@ew-b](https://github.com/ew-b)) - Elias Blanch
- Hao Yang Wu ([@whyhlf](https://github.com/whyhlf)) - Hao Yang Wu
- Jingyi Luo ([@NolandLuo](https://github.com/NolandLuo)) - Jingyi Luo
- Yin Fang ([@aalice23](https://github.com/aalice23)) - Alice Fang

**Comment by ew-b** [comment]
Completed
