### ISSUE TITLE
[Collaboration] Implementation of Player Guide + Updating Pause Menu

### ISSUE THREAD

**Issue by cluanzon** [UQdeco2800/2022-studio-2#260]
# **Design and Implement Player Guide in the Pause Menu**
**Feature:** #247

The in-game player guide is a quick and easy tutorial that the user can browse through. This can be accessed in the pause screen menu under "player guide". It will also include information such as:

- Game Overview 
- How to Craft
- Finding / Picking up items and potions
- Weapon Buffs
- Skill Tree information 
- Levelling Up
- Accessing Inventory 
- How to win the game 

# **Dependencies**
*  #152 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new button on the pause screen called "player guide" [Oct. 9]
- [x] Implement the code for the new pause screen [Oct. 11]
- [x] Create Pages / designs for the player guide [Oct. 9]
- [x] Conduct user survey if users want to add extra information / recommendation for design improvement [Oct. 9]
- [x] Implement the code for the player guide screen [Oct. 12]
 
**Completion Deadline:** Oct. 12

# **Documentation**
- [Player Guide Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Guide-Implementation)
 
# **Member**
- Chaitanya Dasi Luanzon (@cluanzon)
- Enoe (Jolo) Gapusan (@jgapusan)
- Yingzheng Cai (@Rey-666)

**Comment by Rey-666** [comment]
I fixed some typo in this collab ticket, and add the documentation link, cheers!

**Comment by Rey-666** [comment]
I just finished implementing the player guide for both level 1 and 2, they have been merged and pushed to the main branch! I will be starting to debug after this wednesday, cheers guys! Great effort!
