### ISSUE TITLE
Implementing sound for Weapon Attack

### ISSUE THREAD

**Issue by NishaVashist0** [UQdeco2800/2022-studio-2#261]
# **Description**
**Task:** [Weapon Attack Animations](#178)
**Feature:** [Animation and Combat Items Optimisation](#248)

This task aims to further enhance the player experience when attacking the enemy by implementing a sound on the attack. 

# **Dependencies**
n/a
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Background research (Oct. 11)
- [x] Sound ideation (Oct. 12)
- [x] Sound creation (Oct. 15)
- [x] User testing (Oct. 17)
- [x] Update sound (Oct. 18)
- [x] Upload sound onto the game (Oct. 19)
 
**Completion Deadline:** Oct. 19

# **Documentation**

 
# **Member**
- Nisha Vashist, @NishaVashist0
- Caleb Ang, @PurrplePandaa
- Lachlan Benson, @LachlanBenson
- Eugene Chong  @eugene2341
