### ISSUE TITLE
[Feature] Team 6 Code Optimisation, Clean Up and Testing

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#262]
# **Description**

For this sprint, we will mainly focus on checking over code smells, code coverage and fixing the sound effect bug when the player walks. In terms of design, we will be cleaning up the character sprite, ensuring that the player character has a neater design. Key prompt interactions will also be moderated to improve the gameplay experience. 

# **Dependencies**
As of current nothing is dependant on other features or teams.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] [Player sprite artefacts & bugs (Oct. 12)](https://github.com/UQdeco2800/2022-studio-2/issues/315)
- [x] Key prompt interactions (Include level1 NPC, level2 NPC & CRAFTING) (Oct.12)
- [x] [The walking sound effect not disposing of/stop bug fix (Oct. 12)](https://github.com/UQdeco2800/2022-studio-2/issues/314)
- [x] SonarCloud clean up (Oct. 14)
- [x] Test classes complete (Oct. 16)
- [x] UML/ Class diagrams  (Oct. 14)
- [x] Keybind file fixes & updates (exit button, darkening screen) (Oct. 14)
- [x] Code smells, bugs and test classes (Oct. 18)

# **Relevant Task Tickets**
- [x] [Improve code of Player Controls/Keybinds Menu](https://github.com/UQdeco2800/2022-studio-2/issues/270)
- [x] [Improve code of Transition Screen](https://github.com/UQdeco2800/2022-studio-2/issues/271)
- [x] [Improve code of Player Modifier](https://github.com/UQdeco2800/2022-studio-2/issues/266)
- [x] [Player Movement Animation Optimisation and Clean Up](https://github.com/UQdeco2800/2022-studio-2/issues/269)
- [x] [Key Prompt Improvement](https://github.com/UQdeco2800/2022-studio-2/issues/268)
- [x] [Player Stats Improvement](https://github.com/UQdeco2800/2022-studio-2/issues/267)
- [x] [Player Stat Display Optimise and Test](https://github.com/UQdeco2800/2022-studio-2/issues/265)
- [x] [Player Animation Improvement](https://github.com/UQdeco2800/2022-studio-2/issues/264)
- [x] [Death and Win Screen Clean and Optimise](https://github.com/UQdeco2800/2022-studio-2/issues/263)

# **Members**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
