### ISSUE TITLE
<task> Death and Win Screen Clean and Optimise

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#263]
# **Description**
**Task:** Death and Win Screen Clean and Optimise
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

Code optimisation, cleanup, and testing of all files related to the Death and win screen, this includes:
* DeathScreen
* DeathScreenDisplay
* DeathScreenActions
* MainGameScreen

Additionally, the UML and sequence of these classes to be updated and corrected.

# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] UML Diagram Complete(Oct. 12)
- [x] Sequence Diagrams Complete(Oct. 14)
- [x] SonarCloud clean up Complete (Oct. 14)
- [x] Test classes Complete(Oct. 14)

 
**Completion Deadline:** Oct. 18
 
# **Documentation**
[Death & Death Screen Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-&-Win-Screen-Code-Implementation)
[Death Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Death-Screen-Design)
[Player Guide](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Guide)
[Win Screen Testing](https://github.com/UQdeco2800/2022-studio-2/wiki/Testing-plan-and-User-testing-of-Win-screen)
[Win Screen Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Win-Screen-Design)

 
# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
