### ISSUE TITLE
<Task> Player Animation Improvement

### ISSUE THREAD

**Issue by NolandLuo** [UQdeco2800/2022-studio-2#264]
# **Description**
**Task:** Player Animation Improvement(#264)
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

This task is to improve the animation performance of the player.

# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Iterate out new player animations (Oct. 12)
- [x] User Testing (Oct. 13)
- [x] Iterate the animation again based on the feedback (Oct. 16)
- [x] Upload the new player animation to game (Oct. 16)
- [x] Wiki’s updated to reflect work (Oct. 17)
 
**Completion Deadline:** Oct. 18
 
# **Documentation**
[player sprite Sprint 4](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-sprite#sprint-4)
 
# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)

**Comment by NolandLuo** [comment]
Completed
