### ISSUE TITLE
<Task> Improve code of Player Modifier

### ISSUE THREAD

**Issue by IsaacGraham128** [UQdeco2800/2022-studio-2#266]
# **Description**
**Task:** [Improve code of Player Modifier](#266).
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

Code optimisation, cleanup, and testing of all files related to the Player Modifier. Utilising SonarCloud code coverage, bugs, and smell reports, appropriate testing files and adjustments to all files related to the main functionality will be adjusted.

Wiki pages will include before and after pictures of SonarCloud reports as proof of improved file code.

Any code that doesn't include or is altered will be given an appropriately up to date UML or sequence diagram.

# **Related Files**

Files related to Player Modifier functionality are included below.

`com/deco2800/game/components/player/PlayerModifier.java`

# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify initial SonarCloud rating (Oct. 11)
- [x] Fix trivial code smells (Oct 13.)
- [x] Fix intermediate / difficult code smells and bugs (Oct 14.)
- [x] Finalise JUnit test coverage (Oct 15.)
- [x] Update relevant UML Diagram (Oct 16.)

**Completion Deadline:** Aug. 23
# **Documentation**
- [Player Modifier Framework](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Modification-Framework)
 
# **Member**
- e.g. IsaacGraham (@IsaacGraham128) (Isaac Graham)
