### ISSUE TITLE
<Task> Player Stats Improvement

### ISSUE THREAD

**Issue by whyhlf** [UQdeco2800/2022-studio-2#267]
# **Description**
**Task:** [Player Stats Improvement](#267)
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

Code optimisation, cleanup, and testing of all files related to the stamina and mana system: 
components/CombatStatsComponent
components/player/PlayerActions
entities/factories/PlayerFactory
components/player/PlayerStatsDisplay
# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] UML Diagram & Sequence Diagrams Complete(Oct. 14)
- [x] SonarCloud clean up Complete (Oct. 16)
- [x] Test classes Complete(Oct. 16)
 
**Completion Deadline:** Oct.18

 
# **Documentation**
[Stamina and Mana Code Implementation ](https://github.com/UQdeco2800/2022-studio-2/wiki/Stamina-and-Mana-System-Code-Implementation)

# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
