### ISSUE TITLE
<Task>Key Prompt Improvement

### ISSUE THREAD

**Issue by whyhlf** [UQdeco2800/2022-studio-2#268]
# **Description**
**Task:**[Key Prompt Improvement](#268)
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

Adding more interaction to the key prompt system, when player is approaching NPC and Level 2 Crafting Table.
Code optimisation, cleanup, and testing of all files related to the key prompt system:
PlayerFactory
player/PlayerKeyPrompt
player/PlayerKPAnimationController
# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] New Interactions with NPC and Level2 Crafting Table(Oct.12)
- [x] UML Diagram & Sequence Diagrams Complete(Oct. 14)
- [x] SonarCloud clean up Complete (Oct. 16)
- [x] Test classes Complete(Oct. 16)
 
**Completion Deadline:** Oct.18
 
# **Documentation**
- [Key Prompt] (https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Key-Prompt-System)
 
# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
