### ISSUE TITLE
<task>Player Movement Animation Optimisation and Clean Up

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#269]
# **Description**
**Task:** Player Movement Animation Optimisation and Clean Up
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

Code optimisation, cleanup, and testing of all files related to the PlayerAnimationController class, this includes SonarCloud cleanup, ensuring the classes are optimised for their purpose and do not slow down the game's loading, and ensuring the testing has full coverage.

# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] UML Diagram Complete(Oct. 14)
- [x] Sequence Diagrams Complete(Oct. 14)
- [x] SonarCloud clean up Complete (Oct. 16)
- [x] Test classes Complete(Oct. 16)
 
**Completion Deadline:** Aug. 16

# **Documentation**
[Player-Movement-Animations](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Movement-Animations)
 
# **Member**
- Isaac Graham @The Master Craig#7285 (@IsaacGraham128)
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Hao Yang Wu @whycoco#0430 (@whyhlf)
- Jingyi Luo @Noland#5518 (@Nolandluo)
- Yin Fang @Alice123#5689 (@aalice23)
- Chaitanya Dasi Luanzon @clxzn#4012 (@cluanzon)
