### ISSUE TITLE
<Task> Design Rule Book 

### ISSUE THREAD

**Issue by aalice23** [UQdeco2800/2022-studio-2#27]
Design Rule Book Ticket
# **Description**
**Task:** [Design Rule Book](#5).
**Feature:** [Story and Player](#5)

We will be working on developing the overall aesthetics for the game. We will be researching existing games that exhibit similar art styles of roguelike and adventure horror and decide on an appropriate colour scheme that will fit into those categories. We will also look into different types of font to include in the game that will help add to the theme of adventure horror. 
 
## **Example (optional)**
- **Colour and Theme**: An example of our goal for colour scheme is to have colour schemes picked for each setting and character, like: https://www.artstation.com/artwork/QZg1l
- **Font**: Similar to how a company or brand would develop a brand style guide we seek to develop something similar for the fonts, colours and themes.

# **Dependencies**
Task dependencies
- [x] Consult with `Maps` team about their idea on colour
- [x] Consult `Dialogue` team on their ideas on font

# **Milestones**
List of steps that need to be completed for this task.

- [x] By end of Wednesday’s studio team knows who the character is and what the basic idea of the story is (Aug. 17)
- [x] Collating inspiration of design and story (Aug. 17)
- [x] Design guideline book basics (Aug. 20)
- [x] Inspiration and environment scans complete (Aug. 20)
- [x] Colour scheme, font, and themes finalised (Aug. 23)
- [x] Documentation of `Design Rule Book` updated on wiki (Aug. 23)
- [x] Colour scheme, font and themes ready for consultation (Aug. 23)

**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Story, character and Design Development](..wiki/Story%2C-Character-and-Design-Development)
- [Design Rule Book](..wiki/Design-Rule-Book)
- [Testing Story and Character Sprint One](..wiki/Testing-Story-and-Character-Sprint-One)
 
# **Member**
- Isaac Graham ([@IsaacGraham128](https://github.com/IsaacGraham128)) - Isaac Graham
- Elias Blanch ([@ew-b](https://github.com/ew-b)) - Elias Blanch
- Hao Yang Wu ([@whyhlf](https://github.com/whyhlf)) - Hao Yang Wu
- Jingyi Luo ([@NolandLuo](https://github.com/NolandLuo)) - Jingyi Luo
- Yin Fang ([@aalice23](https://github.com/aalice23)) - Alice Fang

**Comment by ew-b** [comment]
Added dependancies

**Comment by ew-b** [comment]
Completed
