### ISSUE TITLE
<Task> Improve code of Player Controls/Keybinds Menu

### ISSUE THREAD

**Issue by IsaacGraham128** [UQdeco2800/2022-studio-2#270]
# **Description**
**Task:** [Improve code of Player Controls/Keybinds Menu](#270).
**Feature:** [Team 6 Code Optimisation, Clean up and Testing](#262)

Code optimisation, cleanup, and testing of all files related to the Key Bindings pause screen. Utilising SonarCloud code coverage, bugs, and smell reports, appropriate testing files and adjustments to all files related to the main functionality will be adjusted.

Wiki pages will include before and after pictures of SonarCloud reports as proof of improved file code.

Any code that doesn't include or is altered will be given an appropriately up to date UML or sequence diagram.

# **Related Files**

Files related to Key Bindings pause screen functionality are included below.

`/core/src/main/com/deco2800/game/components/maingame/OpenKeyBinds.java`

`/core/src/main/com/deco2800/game/components/player/OpenPauseComponent.java`

# **Dependencies**
No known dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify initial SonarCloud rating (Oct. 11)
- [x] Fix trivial code smells (Oct 13.)
- [x] Fix intermediate / difficult code smells and bugs (Oct 14.)
- [x] Finalise JUnit test coverage (Oct 15.)
- [x] Update relevant UML and Sequence Diagrams (Oct 16.)
 
**Completion Deadline:** Aug. 23
# **Documentation**
- [Key Bind Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Keybind-(Controls)-Page-Implementation)
 
# **Member**
- e.g. IsaacGraham (@IsaacGraham128) (Isaac Graham)
