### ISSUE TITLE
[Feature] Map components finalization, test implementation, optimisation and code cleanups

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#274]
# **Description**
Touching up on features implemented in sprint 2 to 3 and finalizing visual aspects of the map and environmental components. 

## SubFeature/component (optional)

- Minimap: Further optimizing the minimap by fixing the sizing, updating the UI design 
- Water: Configuring water boundaries within the map and changing some of the tiles to be a darker color, More water LVL 1 at the bottom
- Collisions: Adding in Level 1 collisions 
- Entities: Dynamic entities on level 2
- Collaborate with team 8: Require a re-iteration on changing the statue color scheme to a lighter shade. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Configure Minimap and Collisions (Oct. 11)
- [ ] Establish Dynamic Entities (Oct. 12)
- [ ] Iterate water with a darker shade (Oct. 12)
- [ ] Experiment test features that can be implemented using mockito (Oct. 16)
- [ ] Add code to include test features and clean up code smells (Oct. 17)
- [ ] Implement all changes made (Oct. 18)

**Completion Deadline:** Oct. 18

# **Documentation**
- ...

# **Members**
- Otis Carmichael (@Otili9890) (@Otis Carmichael)
- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
- Yibo Liu (@rlybgithub)
- Ishaan Ranade (@IshaanM8) (@Ishaan Ranade)
- Lonni Miller-Metzner (@lonnimm) (@Lonni Miller-Metzner)
