### ISSUE TITLE
Implement Buff Timers (Oct. 18)

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#276]
# Description 
**Task:** Implement Buff Timers
**Feature:** #248 

The aim of this task is to fully implement and enhance the ability for buffs to become animated. This would ideally enhance the gameplay and allow for a greater depth perception, ultimately leading to a juicer game design!

The buffs affected within this sprint will consist of:
1. Attack Buff
2. Speed Buff
3. Poison Buff
4. Fire buff

# Dependencies 
No dependencies related to this item.

# Milestones 
List of steps that need to be completed for this task.

- [x] Buff timer icon animation completed (Oct. 8th)
- [x] Buff timer bounce pixel are completed (Oct. 9th)
- [x] Completion of implementation of code into game (Oct. 10th)
- [x] Full implementation of buffs and timers into game after user feedback (Oct. 13)

**Completion Deadline:** Oct. 13th 

# Documentation
* [Buff Timer Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Buff-Animation-Touch-Ups)

# Member
* Caleb Ang, @PurrplePandaa 
* Eugene Chong, @eugene2341

**Comment by PurrplePandaa** [comment]
Sprite sheet seems to be having issues, will require relook at the sprite animation sheet to attain consistent animation timer.

**Comment by eugene2341** [comment]
> Sprite sheet seems to be having issues, will require relook at the sprite animation sheet to attain consistent animation timer.

yes

**Comment by LachlanBenson** [comment]
@eugene2341 marking issue as closed
