### ISSUE TITLE
Implement golden plunger projectile (Oct. 18)

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#277]
# Description
**Task:** Implementation of Golden Plunger Projectile and Bow
**Feature:** #248 

The aim of this task is to ensure the creation of the golden plunger bow is successfully implemented. It should micmic the abilities of the regular plunger bow but deal a lot more damage compared to it. This should be noted as the 'ultimate weapon' or a 'boss item' that should be collected during the second phase of the game. 

This is essential to the game as it allows for the creation and incorporation of new critical items that would impact the gameplay of individuals. For example, individuals may be a lot more inspired to complete side quests in order to attain materials to craft the golden plunger bow. It must be noted that the golden plunger bow must be created using a toilet roll and a golden poop.

# Example (Optional)
Inspiration of idea has already been generated within the previous sprint. It should mimic the regular plunger bow.

# Milestone
List of steps that need to be completed for this task.

- [x] Golden plunger bow inspiration pixel art completion (Oct. 13th)
- [x] Golden plunger bow projectile colour change completion (Oct. 15th)
- [x] Conversion of individuals .png files to sprite sheet (Oct. 15th)
- [x] Implementation and animation of golden plunger bow within game (Oct. 17th)
- [x] Implementation of additional test for golden plunger functionality (Oct. 18th)

# Documentation 
* [Golden Plunger Bow Animation](https://github.com/UQdeco2800/2022-studio-2/wiki/Bow-Plunger)

# Author
* Caleb Ang, @PurrplePandaa

**Comment by LachlanBenson** [comment]
golden plunger successfully implemented and exception clause added to prevent errors from occurring given limited scope of golden animations created
