### ISSUE TITLE
[Task] Crafting Refinement JUnit and Mocking Test & UML

### ISSUE THREAD

**Issue by EverittZ** [UQdeco2800/2022-studio-2#278]
# **Description**
**Task:** [Crafting Refinement JUnit Test & UML]( ).
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features](#247 )

Write JUnit Test and Mocking test for the code in sprint 4 and Complete the Junit Test and Mocking test that was not completed in Sprint 3 . And All the UML Diagram.
 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Junit test(Oct. 16)
- [x] Mocking Testing(Oct.17)
- [x] Code Coverage (Oct.16)
- [x] Crafting System UML(Oct. 14)
- [x] Pause Screen UML(Oct. 14)

 
**Completion Deadline:** Oct. 18

# **Documentation**
- [Crafting Contents Page](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-Contents-Page)

 
# **Member**
- Zhihao Zhang(@EverittZ ) (EverittZ)
