### ISSUE TITLE
<Task> Player Backstory

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#28]
# **Description**
**Task:** [Player Backstory Ticket](#)
**Feature:** [Story and Player](#5)

This aims to develop who our main character is and how they fit into the world of Atlantis, especially their motivation and why they are trying to sink Atlantis. This will be done by creating a character sheet, listing specific details of the character - even if some aren’t used in the game - to personalise our character. We will work on defining the player’s characteristics: age, gender, and appearance. 

## **Example**
- **Upset plumber**: As the only Atlantis plumber, Bobticular is sick of work. Middle-aged and horribly overworked, he plans to reach the depths of Atlantis and pull its plug to sink the city. No guard, monster, or eldritch beast will stop his quest to get a day off.

# **Dependencies**
Must align with the lore and design guideline rulebook.
- [x] Wait for initial character results of user survey testing
- [x] Discuss with the weapons team
- [x] Discuss with the enemy team
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Determines character base attributes. (Aug. 17)
- [x] Determines how the player relates to Atlantis (Aug. 20)
- [x] Determine what is driving the character, and why are they doing this (Aug. 20)
- [x] Determine what relationships the character has to NPCs and enemies (Aug. 23)
- [x] Determine what the character looks like visually (Aug. 27)
- [x] Determine the character’s weapon story. (Aug. 23)

**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Story, character and Design Development](..wiki/Story%2C-Character-and-Design-Development)
- [Testing Story and Character Sprint One](..wiki/Testing-Story-and-Character-Sprint-One)

# **Member**
- Isaac Graham ([@IsaacGraham128](https://github.com/IsaacGraham128)) - Isaac Graham
- Elias Blanch ([@ew-b](https://github.com/ew-b)) - Elias Blanch
- Hao Yang Wu ([@whyhlf](https://github.com/whyhlf)) - Hao Yang Wu
- Jingyi Luo ([@NolandLuo](https://github.com/NolandLuo)) - Jingyi Luo
- Yin Fang ([@aalice23](https://github.com/aalice23)) - Alice Fang

**Comment by ew-b** [comment]
Completed
