### ISSUE TITLE
Balance Changes (Collab)

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#284]
# **Description**
**Task:** Balance Changes
**Feature:** #248 

Requires a collaboration with Enemies Team and Skills Team - everyone involved with attacking - to improve balance throughout the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Revise attack damages and cooldowns of combat weapons (Oct. 14)
- [ ] Revise number of enemies on map (Oct. 15)
- [ ] Revise skills damages and cooldowns (Oct. 16)

**Completion Deadline:** Oct. 18

# **Member**
- Lachlan Benson (@LachlanBenson ) (Lachlan.Benson)
- Eugene Chong (@eugene2341 ) (eugene2341)

**Comment by PurrplePandaa** [comment]
Hey @LachlanBenson, balance changes from user testing results have come back. Sflr but please view the following link to see the changes that need amendment within the codebase! https://github.com/UQdeco2800/2022-studio-2/wiki/Sprint-4-User-Testing#balance-changes. Please lmk if there is anything else you require. Toodles! :)

**Comment by PurrplePandaa** [comment]
Also I think these balance changes will require another team (enemy and potentially even player class) if you would like to get some information from those.

**Comment by LachlanBenson** [comment]
{
  "athenaDag": {
    "damage": 20.6,
    "coolDown": 700,
    "weight": 1,
    "materials": {"gold": 1, "platinum": 1}
  },

  "heraDag": {
    "damage": 20.5,
    "coolDown": 700,
    "weight": 1,
    "materials": {"gold": 1, "steel": 1}
  },

  "SwordLvl2": {
    "damage": 25,
    "coolDown": 1200,
    "weight": 2,
    "materials": {"gold": 1, "iron": 1}
  },

  "dumbbell": {
    "damage": 19,
    "coolDown": 1000,
    "weight": 5,
    "materials": {"steel": 1, "plastic": 1}
  },

  "tridentLvl2": {
    "damage": 27,
    "coolDown": 1500,
    "weight": 2,
    "materials": {"gold": 1,"silver": 1}
  },

  "heraAthenaDag": {
    "damage": 32,
    "coolDown": 650,
    "weight": 3,
    "materials": {"herraDag": 1,"poop": 1}
  },

  "plunger": {
    "damage": 17,
    "coolDown": 650,
    "weight": 1,
    "materials": {"wood": 1, "rubber": 1}
  },

  "pipe": {
    "damage": 19.5,
    "coolDown": 500,
    "weight": 2,
    "materials": {"plastic": 1, "rubber": 1}
  },

  "plungerBow": {
    "damage": 20,
    "coolDown": 1500,
    "weight": 3,
    "materials": {"wood": 1, "toiletPaper": 1}
  },

  "goldenPlungerBow": {
    "damage": 70,
    "coolDown": 5000,
    "weight": 3,
    "materials": {"toiletPaper": 1, "poop": 1}
  }
}

^^ current damages

**Comment by LachlanBenson** [comment]
@bach-truong Can you please have a look and see if the current weapon damage changes will suit the balances changes we discussed that have been made to the enemies?

**Comment by LachlanBenson** [comment]
@bach-truong thank you for the feedback on the balance changes! Glad our balance changes have been effective at impacting the game's playability.

Have you considered increasing the health of boss enemies to make them more difficult to kill?

**Comment by LachlanBenson** [comment]
@rkoll55 changes rolled out to main please confirm once crafting system is updated accordingly

**Comment by LachlanBenson** [comment]
@rkoll55 confirmed by discord
