### ISSUE TITLE
<Task> Reduce Code Smells and Improve Code Coverage for Skills and Skills UI

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#285]
# **Description**
**Task:** [ Reduce Code Smells and Improve Code Coverage](#3).
**Feature:** [Visual Skill Cooldowns, Skill Optimisation and Skill Visual Design Improvements](#253)

Reduce code smell for the skill tree UI and the skill component classes, as well as any other related files. Increase code coverage for all related classes.

# **Dependencies**
- [ ] Functionality needs to be completed
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Reduce code smells to 0 for all designed classes (18/10)
- [ ] Get all code coverage to min 90% (18/10)

**Completion Deadline:** 18/10

# **Documentation**
- [Skills](../wiki/Skills)

 
# **Member**
- Kurt Lucas (@kurt-553) (Kurt Lucas)
