### ISSUE TITLE
<Task> Lore Basics

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#29]
# **Description**
**Task:** [Lore Basics](#3).
**Feature:** [Story & Player](#5)

Develop lore for two specific items and one enemy to build depth to the story and character. We will be working closely with the combat items team (team 4) to decide on weapons that are the most suitable for the players. 

## **Example (optional)**
- **Father’s Triton**: Player finds a triton in level 2 and find it has their dad’s name inscripted near the leather grip, they later find from their NPC uncle that this was given to their dad by their mum and that the triton has a the ability to always hit it’s target, acting as a buff.

# **Dependencies**

Must align with rule book and player 
Depend on tasks based around items and how those items benefit or hinder the character.
Depend on team 3 enemies task about an enemy they are writing.
Depend on team 4 combat items about weapons for the player
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Consultation with team 4 to decide on weapon (Aug. 23)
- [x] Determines 1st weapons’s lore (Aug. 24)
- [x] Determines 2nd weapons’s lore (Aug. 26)
- [x] Lore of items complete (Aug. 26).
- [x] Documentation of `Item Lore` updated on wiki (Aug. 29).

**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Item Lore](../wiki/Item-Lore)

 
# **Member**
- Isaac Graham ([@IsaacGraham128](https://github.com/IsaacGraham128)) - Isaac Graham
- Elias Blanch ([@ew-b](https://github.com/ew-b)) - Elias Blanch
- Hao Yang Wu ([@whyhlf](https://github.com/whyhlf)) - Hao Yang Wu
- Jingyi Luo ([@NolandLuo](https://github.com/NolandLuo)) - Jingyi Luo
- Yin Fang ([@aalice23](https://github.com/aalice23)) - Alice Fang

**Comment by ew-b** [comment]
Completed
