### ISSUE TITLE
[Feature] Code optimisation and remove code smell

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#290]
# **Description**
**Feature:** [Code optimisation and remove code smell](#290)

In sprint 4, we will optimise existing methods in the InventoryComponent and reduce code smells of all methods.

# **Milestones**
List of sub-features you intend to have done and in Main by the end of the sprint.
- [x] Optimise existing functions in the Inventory component (Oct. 10)
- [x] Remove code smell from InventoryComponent and its related display functions (Oct. 12)
- [x] [Documentation on wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/Inventory) (Oct. 16)

**Completion Deadline:** Oct 18

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
