### ISSUE TITLE
[Feature] Implement functionality to enhance UX

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#291]
# **Description**
**Feature:** [Implement functionality to enhance UX](#291)

In sprint 4, we will implement minor features to improve the player's experience while interacting with Inventory.

# **Milestones**
List of sub-features you intend to have done and in Main by the end of the sprint.
- [x] Minor feature enhancement (Oct. 15)
- [x] [Optimise drop-down menu for inventory Items](https://github.com/UQdeco2800/2022-studio-2/issues/273) (Oct. 14)
- [x] [Restrict menu to maximum one can be open at a time](https://github.com/UQdeco2800/2022-studio-2/issues/292) (Oct. 14)
- [x] [Documentation on wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/New-features) (Oct. 16)

**Completion Deadline:** Oct 18

# **Documentation**
- [Main description of feature](../wiki/Inventory)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
