### ISSUE TITLE
Fix Armour and Potions bugs + Quickbar display bugs

### ISSUE THREAD

**Issue by Lukeyone** [UQdeco2800/2022-studio-2#293]
# **Description**
**Task:** [Fix Armour and Potions bugs + Quickbar display bugs](#3).
**Feature:** [Armour and Potion implementation + Quickbar display bugs](#2)

Fix issues related Armour and Potions implementation and display bugs in the quickbar. This mainly focuses on cleaning up the leftover unused code and features, as well as making the armour and potions balanced in their placement throughout the game such that it provide a lively experience for the players. In addition to this, this includes fixing up slight display issues related to the quickbar for potion.  Armour and Potion inherit from component, whereas quickbar is made from several methods inside inventoryComponent which also inherits from component.
 

# **Dependencies**
This ticket relies on the full implementation of Armour and Potions

- [ ] Armour has to be already implemented (#1)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

- [ ] Fix issues related to spawning of potions and armour in the world map (Oct 18).
- [ ] Fix display issues for quickbar when items enter it (Oct 18).
- [ ] Add the last functionality for final armour type (Oct 18).
- [ ] Remove unused features in Armour (Oct 18)
- [ ] Documentation of `Armour` updated on wiki (Oct 18).
 
# **Documentation**
- (https://github.com/UQdeco2800/2022-studio-2/issues/75)
 
# **Member**
- Name (Lukeyone) (Lachlan McDonald)
