### ISSUE TITLE
Testing Plan for Combat Items which extend LibGDX

### ISSUE THREAD

**Issue by madifeddema** [UQdeco2800/2022-studio-2#298]
# **Description**
**Task:** [Testing Plan for Combat Items which extend LibGDX](#).
**Feature:** [FEATURE Animation and Combat Items Optimisation](#248)

This task is about creating a testing plan for our graphics and animations in the game, specifically those classes which extend LibGDX. While there are mechanisms such as headless testing, given the scope of the game and complexity of our animations and graphics a visual testing plan will be created. This testing plan will ensure that the correct visuals align when a user is equipping weapons or obtaining buffs. This is important to the game to ensure a smooth user experience and check that the correct imagery matches with the coded weapons.

# **Dependencies**
List any tasks on which this ticket relies. 

- [x] Any major bug fixes and all classes finalised 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Generate a list of all weapons in the game (Oct. 15)
- [x] Write a testing plan for the classes with libgdx components (Oct. 16)
- [x] Conduct testing in the game (Oct. 16)

 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
 

# **Member**
- Madi Feddema (@madifeddema) (madi-feddema#3384)
- Nisha Vashist (@NishaVashist0) (nishavashist#4270)

**Comment by madifeddema** [comment]
Weapons List:
Athena Dagger
Hera Dagger
Plunger
Plunger bow
Pipe
Trident

Buff List:
Speed
Attack
Damage
Toxic

**Comment by LachlanBenson** [comment]
@madifeddema @NishaVashist0 please confirm ticket status
