### ISSUE TITLE
[Task] Cleanup code files and reduce code smells

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#299]
# **Description**
**Feature:** [Map components finalization, test implementation, optimisation and code cleanups](#274)

Cleanup redundant code and reduce code smells for the GameArea classes classes and other files that branch under Team 5's responsibility. 
 
# **Milestones**

List of steps that need to be completed for this task.

- [ ] Clean up code for GameArea class (Oct. 14)
- [ ] Clean up code for ForestgameArea class (Oct. 15)
- [ ] Clean up code for UndergroundArea class (Aug. 16)
 
**Completion Deadline:** Oct. 18

# **Documentation**
- [GameArea](https://github.com/UQdeco2800/2022-studio-2/wiki/Game-Areas)
 
# **Member**
- Otis Carmichael (@Otili9890) (@Otis Carmichael)
- Yibo Liu (@rlybgithub)
- Ishaan Ranade (@IshaanM8) (@Ishaan Ranade)
