### ISSUE TITLE
[Feature] Enemies (Sprint 1)

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#3]
# **Description**
We plan to add enemies to the game. There will be different kinds of enemies such as basic enemies (melee, ranged) and boss enemies. The enemies will be able to attack the player.

## SubFeature/component
- Melee enemies (basic)
- Ranged enemies (basic)
- Boss enemies
- Enemy drops - when enemy dies, it drops a weapon or equipment

# **Dependencies**
Enemy design will be dependent on the Story/Player feature ticket, so enemies make sense in the story context. Each boss should be a character in the story. Once we know which characters are in the story, we will be able to research the character and take inspiration for the bosses.

Enemy drops will be dependent on the Items (Combat and Alchemy) feature ticket as items will need to be created before enemies can drop them.

# **Milestones**
Sprint 1
Week 4 - 19/08 - Friday
- [x] Create basic enemy that appears in game.
- [x] Design basic design for melee enemy
- [x] Code different stats for melee enemy (attack power, health, etc.)

Week 5 - 24/08 - Wednesday
- [x] Design walking animation for melee enemy
- [x] Code movement pattern for melee enemy

Week 5 - 28/08 - Sunday
- [x] Design attacking animation for melee enemy
- [x] Code attack pattern for melee enemy
- [ ] Code melee enemy drops
- [x] Documentation of melee enemy updated on wiki
- [ ] Make it so enemies can hold weapons

**Completion Deadline:** Aug. 30

# **Extras (For Later Sprints)**
- [ ] Design basic design for ranged enemy
- [ ] Design walking animation for ranged enemy
- [ ] Design attacking animation for ranged enemy

- [ ] Design basic design for boss enemy
- [ ] Design walking animation for boss enemy
- [ ] Design attacking animation for boss enemy

- [ ] Code different stats for ranged enemy (attack power, health, etc.)
- [ ] Code movement pattern for ranged enemy
- [ ] Code attack pattern for ranged enemy
- [ ] Code ranged enemy drops

- [ ] Code different stats for boss enemy (attack power, health, etc.)
- [ ] Code movement pattern for boss enemy
- [ ] Code attack pattern for boss enemy
- [ ] Code boss enemy drops

- [ ] Add enemy health bars

- [ ] Create UML Diagram to represent enemy classes
- [ ] Test code with JUnit tests

- [ ] Make the enemies more intelligent so they don't get blocked by obstacles

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
- [Enemy Weapons](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemy-Weapons)

# **Members**
- Caitlenn Alsop (github: c-alsop) (Slack: Caitlenn Alsop)
- Wenfang Hao (github: wenfangH) (Slack: Wenfang Hao)
- Yi Zhou(@MandalorianForce)
- Bach Truong (bach-truong)
- Yash Sharma (Yash20Sharma)

**Comment by c-alsop** [comment]
@notalie @BozenX Completed feature ticket

**Comment by BozenX** [comment]
Looks good!

**Comment by c-alsop** [comment]
Sprint 1 has concluded.
