### ISSUE TITLE
Dagger Weapon Implementation

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#30]
# **Description**
**Task:** Create a graphical representation of a dagger to be implemented into the codebase. 
**Feature:** Combat Items #7 

The task is to generate a graphical image for the dagger implemented under the dagger class implementation under task #34. Research will need to be conducted to suit the Greek Mythology theme this game is currently set within. Such information could take the form of choosing the colour scheme, size or even weight of the dagger to be implemented for the description of the item. From here, dagger sketches will need to be viewed first to get a better understanding of what kind of dagger will be implemented. Upon creation of all sketches, one (or a collation of multiple ideas) should be selected and implemented on a graphical level through pixelated art. 
 
## **Example**
Below are some inspirations and directions on potential dagger options. One represents two daggers placed together.
![Atlantis dagger 2](https://user-images.githubusercontent.com/109809229/184535572-0a77822f-f077-4ea3-8dd7-177ec1f3d020.png)
![Atlantis dagger](https://user-images.githubusercontent.com/109809229/184535576-bb3592c2-2d1a-4575-82bb-e2f31dcaec01.png)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Research completed  (Aug. 15)
- [x] Sketches completed  (Aug. 18)
- [x] Graphical representation drawn (Aug. 21)
- [x] Graphic provided to team (Aug. 23)
  
# **Documentation**
- Combat Items (...wiki/Combat-Items)
 
# **Member**
- Caleb Ang (PurrplePandaa) (Caleb Ang)
