### ISSUE TITLE
[Collab] Polishing the Crocodile NPC Voice Lines

### ISSUE THREAD

**Issue by MonitaMegaele** [UQdeco2800/2022-studio-2#300]
# **Description**
The crocodile currently has no voice lines. I believe the addition of a voice for the crocodile will be relevant in the game to add a sense of immersion.

# **Milestones**
- [ ] Create Voice Lines, written (14 Oct)
- [ ] Create Voice Lines, wav file (15 Oct)
- [ ] Implement in game (18 Oct)

**Completion Deadline:** Oct. 18

# **Documentation**
- [Main description of feature](../wiki/[Dialogue + NPC](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs))
 
# **Member**
- Megaele Muniappan (@MonitaMegaele)
- Garryco Thandi (@Harqua)

**Comment by MonitaMegaele** [comment]
hey @Harqua , Could you send through the written voice lines for the collab :D?

**Comment by Harqua** [comment]
@MonitaMegaele I will get it done by tonite and Im gonna send u the files

**Comment by MonitaMegaele** [comment]
cool cool

**Comment by Harqua** [comment]
ん？何しに来たんだ？
Hm? Why did u come here?

二度と来るなってつってんだろうが??!!!
Didn't I say never come here again??!!!

まあいい。。。とりあえずこれあげよっか
Whatever... lemme just give you this

*gives stuff*

終わったらささっと行けっ！！！
If you are done, LEAVE NOW

**Comment by Harqua** [comment]
The script that I came up with (might need some changes)

ん？何しに来たんだ？
Hm? Why did u come here?

キサマ。。。二度と来るなってつってんだろうが??!!!
You...Didn't I say never come here again??!!!

まあいい。。。とりあえずこれあげる
Whatever... lemme just give you this

*gives stuff*

終わったらささっと行けっ！！！
If you are done, LEAVE NOW

**Comment by MonitaMegaele** [comment]
Amazing! Thank you, Just saw your sent wav voiceline files too. Will update when we implement this before deadline!

**Comment by Harqua** [comment]
Awesome, hope it's good enough

**Comment by MonitaMegaele** [comment]
Could you possibly change a few lines?

**Comment by MonitaMegaele** [comment]
3. Whatever... sing me a song and I will give you something good
3.5 As expected... anyway, a promise is a promise. Here. The legendary toilet paper.

**Comment by Harqua** [comment]
Updated Script:

ん？何しに来たんだ？
Hm? Why the hell did u come here?

二度と来るなってつってんだろうが？？！！
Didn't I say never to come here again??!!!

まあいい。。。歌を歌ってくれ。そうしたらいいものあげる。
Whatever... sing me a song and I will give you something good

流石。。。とにかく、約束は約束だ。これ、伝説なトイレットペーパー。
As expected... anyway, a promise is a promise. Here, the legendary toilet paper.

gives stuff

終わったらささっと行けっ！！！
If you are done, LEAVE ME ALONE!!!
