### ISSUE TITLE
[Optimisation] SonarCloud Optimisation

### ISSUE THREAD

**Issue by rkoll55** [UQdeco2800/2022-studio-2#302]
# **Description**
**Task:** [SonarCloud Optimisation](#3).
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features ](#247)

The crafting system has numerous code smells and potential bugs according to sonar cloud. We will reduce these as much as possible this sprint to optimize the code.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Remove code smells in GameAreaDisplay(Oct. 5)
- [x] Remove code smells in rest of crafting(Oct. 7)
- [x] Finish up with last of Code Smells (Oct. 15)
 
**Completion Deadline:** Oct. 15

# **Documentation**
- [Main description of feature](../wiki/Feature)

 
# **Member**
- Rohan Kollambalath(@rkoll55 )

**Comment by rkoll55** [comment]
Finished with code smells
