### ISSUE TITLE
[Optimization] Main Menu Title - Text Animation Design and Programming

### ISSUE THREAD

**Issue by Rey-666** [UQdeco2800/2022-studio-2#307]
# **Description**
**Task:** [Main Menu Title - Text Animation Design and Programming](#3).
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features](#247 )

This task involves designing and implementing the main menu title animation to optimise the game aestheitc feature. This will make the game more consistent and attractive to play. The animation will be user tested before implementing for further evaluation. 
 
# **Milestones**
- [ ] Finish designing the animation frames. (Oct. 15)
- [ ] User testing for the animation. (Oct. 16)
- [ ] Programming the frames into the game. (Oct. 17)
- [ ] Documentation of User testing (Oct. 17)
- [ ] Documentation of programming side. (Oct. 18)
 
**Completion Deadline:** Oct. 18
 
# **Documentation**
- [Main Menu Title Animation Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Main-Menu-Title-Animation-Code-Implementation)
- [Main Menu Title Animation Frames User Testing](https://github.com/UQdeco2800/2022-studio-2/wiki/Main-Menu-Title-Animation-Frames---User-Testing)
 
# **Member**
- Yingzheng Cai (@Rey-666 ) (@Rey-666)
- Emily Southgate (@e-southgate ) (@e-southgate)
