### ISSUE TITLE
Crafting Visual Assets Design

### ISSUE THREAD

**Issue by Rey-666** [UQdeco2800/2022-studio-2#31]
# **Description**
**Task:** Finish the first draft of the visual design of “The crafting table, crafting materials, crafting interface”.
**Feature:** Crafting system #4 

This task is to design all the art/visual components of the crafting feature. In this task, the visual designs of the “crafting table, crafting materials, crafting interface will be finished by sprint one. None of the above features inherits from another feature. More importantly, the visual designs should ideally be finished before the code implementation for better results. For the crafting materials, there are two materials specifically that need to be designed before sprint 1, which are steel and wood. As for the crafting interface, it is discussed that at this stage, only two slots will be required for sprint one since we will just be crafting a very basic sword. 
 
## **Example (optional)**
![WechatIMG9487](https://user-images.githubusercontent.com/109886027/184536709-b1575ffc-7fed-4096-b489-e4c5f106e949.jpeg)
<img width="229" alt="WechatIMG9489" src="https://user-images.githubusercontent.com/109886027/184536723-41532347-3bd0-462f-8b77-17d0fd6e0a01.png">

Since the task in this case are all visual arts/assets, how the specific items will be represented will be briefly introduced. 
- **crafting table**: similar to the one in “Minecraft”, but shouldn’t be too fancy for sprint one. 
- **crafting interface**: basic two-slot crafting system, since only a sword will be crafted in sprint one. And it is discussed that there is no need to make a complicated crafting system since the gameplay will not rely on the crafting system too much. Would be similar to “Minecraft”.
- **Crafting materials**: Only wood and steel at this stage, the wood and steel is aimed to be cute and attractive, and should look as real as possible.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- None.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 - Finish the first draft of the crafting table. (Aug. 16)
- [x] Step 2 - Finish the first draft of the crafting interface. (Aug. 18)
- [x] Step 3 - Finish the first draft of the crafting materials, specifically, wood and steel.(Aug. 19)
- [x] Step 4 - Share the designs with the team and modify them according to feedback. (Aug. 20)

 
**Completion Deadline:** Aug. 20

 
# **Documentation**
- Crafting Visual Assets Design (.../Wiki/Crafting Visual Assets Design)
 
# **Member**
- Yingzheng (@Rey-666) (@Rey-666)

**Comment by Rey-666** [comment]
@lyphng @rkoll55

**Comment by rkoll55** [comment]
Designs were completed and are viewable in game
