### ISSUE TITLE
Mini Map Update

### ISSUE THREAD

**Issue by lonnimm** [UQdeco2800/2022-studio-2#312]
# **Mini Map Update**
**Task:** [Mini Map Update](#3).
**Feature:** [Map components finalization, test implementation, optimisation and code cleanups] #274)

After the initial implementation of the mini map, further development was required to improve the minimap interface and functionality. Through design iteration and user-testing, the mini-map will be updated. 

# **Dependencies**
The mini map interface depends on mini map bug fixes. 
- [ ] Dependency 1 Mini Map Bugs (#279 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create map update prototype sketches (10/10)
- [ ] Plan and distribute user testing (11/10)
- [ ] Analyse testing feedback (14/10)
- [ ] Design mini map based on feedback (15/10)
- [ ] Implement mini map to game (17/10)

 
**Completion Deadline:** 17/10

 
# **Documentation**
- [Main description of feature](../wiki/MiniMap)

 
# **Member**
- Lonni Miller-Metzner (@lonnimm) (Lonni Miller-Metzner
- e.g. Abi Borromeo (@Abi-B-28 ) (Abi Borromeo)
