### ISSUE TITLE
<Collaboration> Team 5 (Map) x Team 9 (Crafting) MiniMap Redesign Collab

### ISSUE THREAD

**Issue by Abi-B-28** [UQdeco2800/2022-studio-2#317]
# **Description**
**Task:** [Team 5 (Map) x Team 9 (Crafting) MiniMap Redesign Collab](#3).
**Feature:** [World Traversal + Maps](#117)

Incorporation of crafting tables & their placements into the mini-map redesign for both levels.
 
# **Dependencies**
- [MiniMap Update](#312).

# **Milestones**
List of steps that need to be completed for this task.
- [x] Crafting Team sends Crafting Table placements for both maps (12/10)
- [x] Crafting Team sends Crafting Table for both maps (12/10)
- [x] Map Team incorporates crafting table to both Level 1 & 2 MiniMap redesigns. (16/10)
 
**Completion Deadline:** (18/10)
 
# **Documentation**
- 
- 
 
# **Member**
Lonni Miller-Metzner (@lonnimm) (Lonni Miller-Metzner)
Abigail Borromeo (@Abi-B-28 ) (Abigail Borromeo)

**Comment by Abi-B-28** [comment]
@jgapusan hey we’ve added crafting tables for both mini maps, can u pls check locations?

**Comment by jgapusan** [comment]
@Abi-B-28 hi they look great, thanks for doing it !
