### ISSUE TITLE
<Task>Implement the collisions for the expanded maps

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#318]
# **Description**
**Task:** Implement the collisions for the expanded maps.
**Feature:** [Map components finalization, test implementation, optimisation and code cleanups](#274 )

The level one map has been expanded much larger compared to the previous sprints, so the old collisions for the walls and columns etc. are not working anymore. Moreover, the level two map also does not contain collisions at moment. Need to implement collisions for both maps.
 
## **Example (optional)**
Since the maps become really large, the work will be divided into different parts to complete. First, we got the annotated maps from Team 3(The Enemy team), which divide the different areas of the map by zones, and then we will implement the collisions among these zones.

Annotated Level 1 map:
![image](https://user-images.githubusercontent.com/109902711/196071687-903e7f02-0ce2-4817-b956-18d38189aa2e.png)
Annotated Level 2 map:
![image](https://user-images.githubusercontent.com/109902711/196071662-a7dbbb85-e59a-40c6-8f59-2751ff9c9fad.png)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] complete the collisions for the level 2 map for zones A, B, C, D, E. (Oct. 08)
- [ ] complete the collisions for the level 2 map for zones F, G, H, I. (Oct. 09)
- [ ] complete the collisions for the level 1 map for zones A, B, C, D. (Oct. 15)
- [ ] complete the collisions for the level 1 map for zones E, F, G, H. (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Member**
- Yibo Liu (@rlybgithub)
