### ISSUE TITLE
<Task> Inventory Button Redesign

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#319]
# **Description**
**Task:** [Inventory Button Redesign](#319 ).
**Feature:** [Inventory interactions and refinements](#149 ).

Redesign the style of button down which in the inventory menu, let the button style fits to the inventory and game
 
## **Example (optional)**
- #189 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Redeign for the button (Oct. 13)
- [x] Finalize the design (Oct. 14)
- [x] Implement to the game  (Oct. 16)
- [x] User test (Oct. 16)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
