### ISSUE TITLE
<Task>Junit test for game areas

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#321]
# **Description**
**Task:** Junit test for game areas
**Feature:** [Map components finalization, test implementation, optimisation and code cleanups](#274)

Make some Junit tests for game areas to verify the function in those classes.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Junit test for GameArea & GameAreaDisplay(Oct. 16)
- [ ] Junit test for GameArea & UndergroundGameArea(Oct. 17)
- [ ] Junit test for GameArea & ForestGameArea(Oct. 18)
 
**Completion Deadline:** Oct. 18
 
# **Member**
- Yibo Liu (@rlybgithub)
