### ISSUE TITLE
<Collaboration> skills and sound effect for skills Collab

### ISSUE THREAD

**Issue by TimothyLam123** [UQdeco2800/2022-studio-2#324]
# **Description**
**Task:** [Team 2 (Inventory) x Team 8 (Skills) skills and sound effect for skills Collab](#3).

Add sound effects to the designed skills to enhance the player's experience when using the skills and make it more attractive.

# **Milestones**
List of steps that need to be completed for this task.
- [x] recalculate the duration of the Ora sound to make the sound and animation have same duration (Oct. 18)
- [x] Optimise some sounds after user testing (interview) (Oct. 18)
- [x] implement sound effects to all the skills (excepted aoe) (Oct. 18)
 
 Completion Deadline: 18 Oct.

# **Member**
- Siu Ming Lam(Timothy_Lam) (Siu Ming Lam)
- Zhuohang Song(AndySong-2324) (AndySong)
