### ISSUE TITLE
Weapon GUI Implementation

### ISSUE THREAD

**Issue by eugene2341** [UQdeco2800/2022-studio-2#36]
# **Description**
**Task:** Merge the weapon logic with the UI of the game.
**Feature:** Combat Items #7 

Once the weapon logic #34 and aura logic #35 are done, the logic can be merged into the GUI to implement a functioning weapon into the game. The design of the weapon #30 will also be needed to map the logic onto the weapon design.
 
# **Dependencies**
- [x] Weapon Logic for the functionality of the weapon #34 
- [x] Aura Logic to buff/debuff/curse the weapon #35 
- [x] Weapon (Dagger) Design #30 
- [x] Weapon (Sword) Design #56

# **Milestones**
List of steps that need to be completed for this task.
- [x] Discover and experiment with Box Boy code to figure out frontend to backend implementation (Functionaility to GUI)  (Aug. 22)
- [x] Implement weapon logic, aura logic to the GUI with the weapon design from the deisgn team, (Aug, 24)
 
# **Documentation**
- Combat Items ([...wiki/Combat-Items)
 
# **Member**
- Eugene Chong (eugene2341) (Eugene Chong)
