### ISSUE TITLE
Task: Design and Create Enemy weapons

### ISSUE THREAD

**Issue by madifeddema** [UQdeco2800/2022-studio-2#37]
# **Description**
**Task:** [Design and Create Enemy Weapons](#3).
**Feature:** [Combat Items](#7)

This task is about designing enemy weaponry. This task will involve researching different types of enemy weaponry and discussing with team 3 about what enemies will be in sprint 1. After this I will need to ideate and design weapon/s to suit the enemies. The designs will then go through some evaluation/user testing to identify which is the most appealing stylistically and logical for the game story.
 
## **Example (optional)**
- **Part**: Enemies might drop their weapons which can then be picked up by the main player. For instance, the weapon might possess the power of the enemy so when the player collects it, the player then possess that power.
- **Weapon Use**: Enemies will use their weapons to fight back in the game and protect Atlantis from sinking.

# **Dependencies**

- [x] Types of enemies in the game are chosen (#xx)
- [x] Enemies for the game designed (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Research different types of weapons the enemies might use (Aug. 16)
- [x] Select a style which matches the game for the weapons (Aug. 17)
- [x] Sketch some rough weapons (Aug. 18)
- [x] Discuss with weapons team on which items would be best for sprint 1 (Aug. 20)
- [x] Create design for enemy weapons (Aug.20)
- [x] User testing of the enemy weapons (Aug.21)
- [x] Finalise any changes based on user feedback (Aug.24)
 
**Completion Deadline:** Aug. 24
 
# **Documentation**
- Combat Items ([...wiki/Combat-Items)
 
# **Member**
- Madison Feddema (madi-feddema) (madi_feddema)

**Comment by madifeddema** [comment]
User testing for the weapons was completed with lots of success! 
Key Notes:
- all able to recognise the weapon was a dumbbell
- thought a fit character would utilise the weapon
- damage would be considerable to the player. Something like whacking, breaking bones, gets knocked out and dizzy and slow
- when the player possesses the enemies weapon, player gains something like super strength, lots of power, someone said power of thor
- one key bit of feedback is they felt the colours were too calming and needed to be more evil and harsher. To vibrant
