### ISSUE TITLE
<Task> Pixel art for teleport with animation

### ISSUE THREAD

**Issue by AndySong-2324** [UQdeco2800/2022-studio-2#38]
# **Description**
**Task:** [Pixel art for teleport with animation and design skills](#3).
**Feature:** [Skills](#2)

We will be working on designing the ICONS and animation for teleport, dodging/dashing by pixel art, and extending the other skills like throwing, parrying that are relatively easy to implement in code and more general to use. We will also attempt to create a player statistic like a modification system.
 
# **Dependencies**
- [x] Need to know the type of teleport (e.g. whether teleport starts instantaneously or has a 1-2 second transfer animation)

# **Milestones**
List of steps that need to be completed for this task.

- [x] Add more new skills ability and mechanics (Aug. 19)
- [x] Draw the pixel Icons for dodging and dashing (Aug. 23)
- [x] Draw the pixel Icons for teleport (Aug. 25)
- [x] Design pixel Animation of 'teleport' skills (Aug. 28)
- [x] Draw the pixel Icons for block (Aug. 28)
- [x] Draw the pixel Icons for invulnerability (Aug. 29)
- [x] Put the five icons on the game's interface (Aug. 30)
 
**Completion Deadline:** Aug. 30

# **Member**
- Zhuohang Song (AndySong-2324) (AndySong)
