### ISSUE TITLE
[Task] Child NPC Design

### ISSUE THREAD

**Issue by MonitaMegaele** [UQdeco2800/2022-studio-2#39]
# **Description**
**Task:** [Making of Child NPC](#3).
**Feature:** [NPCs + Dialogue](https://github.com/UQdeco2800/2022-studio-2/issues/6) (#6 )

Making of Child NPC in order to get a grasp on designing an NPC to the game. Child NPC will include rough draft, iterations and final first iteration of animated pixel design. This task ticket will be a design-based focus on the Child NPC. This NPC will eventually be implemented and have dialogue interaction with the player.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Rough Sketch of Child NPC (Aug. 16)
- [x] Step 2: First Iteration of Pixel Model (Aug. 21)
- [x] Step 3: Second Iteration of Pixel Model + Idle Animation of NPC (Aug. 25)
- [x] Step 4: Final Iteration of Child NPC and Documentation (Aug. 28)
 
# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs) 
- ...Code yet to be implemented
- ...
 
# **Member**
- Monita (@MonitaMegaele) (Monita Muniappan)
