### ISSUE TITLE
<Task> Map Creation 

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#40]
# **Map Creation Task Ticket Sprint 1**
**Task:** [Overall Map Design and Layout](#3).
**Feature:** [Map Implementation](https://github.com/UQdeco2800/2022-studio-2/issues/22)

The Map creation of the map is going to consist of a comprehensive breakdown of the feature into multiple steps ranging from designing and implementing a map layout, movement between levels / into different sections of the map and having a static, smaller image of the map as a minimap.

# **Dependencies**

- [x] Spawn point of the player is necessary. Will allow in deciding what the initial map layout should look like.
- [x] Color palette needs to be decided, would support in maintaining a consistent color scheme throughout the project.

# **Milestones**
Sprint 1
Week 4 - 17th August
- [x] Decide what Application, color palette and dimensions are required to start brainstorming / sampling designs for potential map designs.

Week 5 - 22nd August
- [x] Produce a few samples of terrain, experiment and explore designs and its extent.

Week 5 - 26th August
- [x]  Implement the map layout into the game(Coding Side)

# **Documentation**
- [Terrain](https://github.com/UQdeco2800/2022-studio-2/wiki/Terrain)
- [Map](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Design)
 
# **Member**
- Otis Carmichael ([@otili9890](https://github.com/otili9890)) ([@otis](https://github.com/otis) Carmichael)
- Ishaan Ranade ([@IshaanM8](https://github.com/IshaanM8)) ([@ishaan](https://github.com/ishaan) Ranade)
