### ISSUE TITLE
<TASK> Other NPCs Design

### ISSUE THREAD

**Issue by uq-haze** [UQdeco2800/2022-studio-2#41]
# **Description**
**Task:** [Making design drafts of different NPCs depending on the Story and Location] (#41)
**Feature:** [NPCs + Dialogue] (#6)

Creating multiple drafts of additional NPCs that would be needed for the Story and Locations. This will include multiple drafts, iterations and animated pixel designs. This task ticket is focused on other NPCs that are needed to be created depending on the story and locations. They will eventually be implemented and have a dialogue interaction with the player (or other NPCs).
 
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Step 1: Consult with Story (Team 6 ) and Locations (Team 5) about what NPCs are needed to be made (Aug 17) 
- [x] Step 2: Create drafts and first iterations of Pixel Models  (Aug 21)
- [x] Step 3: Second iterations of Pixel Models + Idle and Walking animations of NPCs (Aug 26)
- [x] Step 4: Final Iterations of NPCs and Documentation (Aug 28)

 
**Completion Deadline:** Aug 31

 
# **Documentation**
- [NPCs + Dialogue](../wiki/[Dialogue & NPCs](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs)) 

 
# **Member**
- Hazeem bin Suffian (@uq-haze)
