### ISSUE TITLE
<Task> Implement Teleport Skill

### ISSUE THREAD

**Issue by TTevita** [UQdeco2800/2022-studio-2#42]
# **Description**
**Task:** [Implement Teleport Skill](#3)
**Feature:** [Skills](#18)

Implement a skill which allows the player to teleport. Will first need to decide the game mechanics associated with the teleport skill (frame data, range, mana cost, etc.). The skill can then be implemented based on these decisions.
 
# **Dependencies**

- [x] Mana system framework is needed for skill use (#25)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide on mechanics for how the teleport will function (Aug. 18)
- [x] Implement skill interrupt on 'e' keypress (Aug. 22)
- [x] Code teleport ability (Aug. 23)
- [x] User testing (Aug. 25)
- [x] Make necessary changes according to user feedback (Aug. 28)
 
**Completion Deadline:** Aug. 28

# **Member**
- Name (TTevita) (Tyler)
