### ISSUE TITLE
<Task> Create Interactive Environmental Components

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#43]
# **Description**
**Task:** Interactive Environmental Components
**Feature:** [Map + Environment Interaction] #22 

Design and implement dynamic environmental components Unlike the static map elements, these dynamic components can interact with the player and affect the game process, such as game resources that can be collected, targets that can be destroyed or repaired by the player, and portals for changing different scenes, etc.
 
## **Example (optional)**
- ![image](https://user-images.githubusercontent.com/109902711/184638258-b08ee4f7-2505-4cd5-86c0-0265a97293fa.png)Portal for transition between the scenes
- ![image](https://user-images.githubusercontent.com/109902711/184638446-7f38af8c-80ea-41ff-b3cf-f2c8fc24ac2f.png)Trees for getting woods
- ![image](https://user-images.githubusercontent.com/109902711/184638564-dcf096d9-b95d-47fd-9768-27ee39fffc21.png)Rocks for getting steels

# **Dependencies**

- [x] Most of the components will depend on the basic map.  #40 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide the necessary dynamic components for sprint 1(Aug. 18)
- [x] Design of components and create document on wiki(Aug. 23)
- [x] Implement the components into the game by coding. (Aug. 27)
- [x] Documentation of dynamic components updated on wiki. (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- Interactive Environmental Components
 
# **Member**
- Yibo Liu (@rlybgithub)
- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
