### ISSUE TITLE
<Task> Environment Design Style

### ISSUE THREAD

**Issue by lonnimm** [UQdeco2800/2022-studio-2#44]
# **<Task> Environment Design Style**
**Task:** [Environment Design Style](#22).
**Feature:** [ Map + Environment Interaction ](#22)

The design style guide for the environment is an important aspect, affecting a wide range of features within the game. The interactive and non-interactive environment is constantly present throughout the game and links the player to the setting, story and world in which the game is set. Thus it is essential that the environment has a strong stylistic theme throughout, in order to facilitate cohesive game play. 
 
## **Example (optional)**
- **Colour Palette**: Style guide example featuring primary game colours and secondary colours and hex code (created based upon concept art) 

<img width="302" alt="Colour Example" src="https://user-images.githubusercontent.com/89431628/184651841-c56da261-0d70-4e9e-b655-8dbf602b1884.png">

# **Dependencies**
Many components, particularly the visual aspects, and by association the functional aspects, will depend on the style guide of the game environment, and be affected by these design choices. 

- [x] Dependency 1 (#43)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Aug. 19) - Creation of design guide document including details regarding: 

- Identification of colour palette/colour scheme 
- Identification of art style 
- Design inspiration resources and concept art gathered 

- [x] Step 2 (Aug. 22) - Sketches for various game screens designed 
User testing to inform and reflect on aesthetic choices 

- [x] Step 3 (Aug. 24) - Implementation of user testing 

- [x] Step 4 (Aug. 26) - Finalisation of style guide to inform further iteration 

 
**Completion Deadline:** Aug. 26

# **Documentation**
- [Terrain](https://github.com/UQdeco2800/2022-studio-2/wiki/Terrain)
- [Map](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Design)
 
# **Member**
- Lonni Miller-Metzner (@lonnimm) (@Lonni Miller-Metzner)
- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
