### ISSUE TITLE
<Task> Static Environment Components

### ISSUE THREAD

**Issue by Abi-B-28** [UQdeco2800/2022-studio-2#45]
# **Description**
**Task:** [Static Environment Components](#45).
**Feature:** [Map + Environment Interaction #22](#22 )
**Feature:** [Map + Environment Interaction] #22 

Static environment components will be conceptualised in this task. These are the components within/concerning the environment the player does not/ cannot interact with, but serve the purposes of environmental setting, story context and aesthetics of the game. These components should be relevant/interconnected to the scene/levels and the game’s story. They are incorporated to help achieve emotional goals and enhance the user’s experience and immersion in the game.
 
## **Example (optional)**
- **Buildings and Structures**: In certain locations on the map, there are buildings and structures which represent those belonging to the city of Atlantis
- **Scenery**: The surrounding static scenery in the background - within and beyond the map (sky, clouds, silhouettes, weather etc.)
- **Terrain**:  trees, bushes etc.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] <Task> Map Creation (#40) - to know the layout of where certain components will be placed
- [x] <Task> Environment Design Style (#44) - for consistency of designs
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Conceptualise and gather inspirations for meaningful static components that are ideally relevant to Atlantis, and create a list of components under each category (Building/Structures, Scenery, Terrain)(Aug. 20)
- [x] Step 2: Initial designs for components, create corresponding wiki page/s (Aug. 22)
- [x] Step 3: User Testing for designs (Aug. 25)
- [x] Step 4: Finalise designs (Aug. 26)
- [x] Step 5: Implement static components and test code. (Aug. 28)
- [x] Step 6: Documentation of components updated on wiki. (Aug. 28)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Abigail Borromeo (@Abi-B-28) (@Abigail Borromeo)
- Yibo Liu (@rlybgithub )
