### ISSUE TITLE
<Task> The appearance of the potions

### ISSUE THREAD

**Issue by hideonbush-crl** [UQdeco2800/2022-studio-2#46]
# **Description**
**Task:** #46 
**Feature:** [Potions #32 ](#2)

This task is to get the appearance of the potions, which will be designed in a style that fits the overall game. The appearance of the potions will be different for different effects.Even when it is finished, it should have a different appearance.
 
## **Example (optional)**
Health potions are red-based. Speed potions can be blue-based.(just for now).

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x]  Potions need to conform to the design of the inventory(Design for Inventory #11)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Pick a colour for different potions (Aug. 19)
- [x] Draft the appearance of a potions bottle (Aug. 20)
- [x] Complete the basic appearance of the potion (Aug. 23)
- [x] Integration with other designs (Aug. 23)
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Bokai (@hideonbush-crl ) (Bokai Zhang)
