### ISSUE TITLE
Male citizen Design

### ISSUE THREAD

**Issue by 45229848** [UQdeco2800/2022-studio-2#47]
# **Description**
**Task:** [Making of  Male citizen].
**Feature:** [NPCs + Dialogue](#6)

Create  Male citizen  to master the design of game NPCs.  Male citizen  will include rough drafts, iterations and final pixel designs for the first iteration of the animation. This task list will be the focus of a design-based  Male citizen. This NPC will eventually be implemented and will interact with the player.
 
# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Rough Sketch of Male citizen (Aug. 16)
- [x] Step 2: First Iteration of Pixel Model (Aug. 21)
- [x] Step 3: Second Iteration of Pixel Model + Idle Animation of NPC (Aug. 25)
- [x] Step 4: Final Iteration of  Male citizen and Documentation (Aug. 28)
 
# **Documentation**
- [Main description of feature](Will edit this once we create a Wiki Page)
- ...Code yet to be implemented
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
-  Yongzhi ZHOU(@45229848) (YONGZHI ZHOU)

**Comment by 45229848** [comment]
finish step 1

**Comment by 45229848** [comment]
finish step2 and 3

**Comment by 45229848** [comment]
finish all
