### ISSUE TITLE
Task: User testing for weapon designs

### ISSUE THREAD

**Issue by madifeddema** [UQdeco2800/2022-studio-2#48]
# **Description**
**Task:** [User testing for weapon designs](#3).
**Feature:** [Combat Items](#7)

This task will include conducting user testing on all the different weapons we have designed. This is to ensure both the purpose of the weapon is clear in the game and the style and aesthetic is both appealing and makes sense to the user.

# **Dependencies**
- [x] All research into weaponry design and communication with other necessary teams
- [x] First iteration of the various weapons are designed and drawn
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write up a protocol for the user testing of the weapons (Aug. 19)
- [x] Conduct user testing for each design (Aug. 23)
- [x] Integrate the feedback into the design process (Aug. 24)
 
**Completion Deadline:** Aug. 24
 
# **Documentation**
- Combat Items ([...wiki/Combat-Items)
 
# **Member**
- Name, @madifeddema
- Lachlan Benson, @LachlanBenson
- Caleb Ang, @PurrplePandaa
- Nisha Vashist, @NishaVashist0
