### ISSUE TITLE
<Task> Dialogue Design and Dialogue Code

### ISSUE THREAD

**Issue by EverittZ** [UQdeco2800/2022-studio-2#49]
# **Description**
**Task:** [Dialogue Design](#49).
**Feature:** [[NPCs + Dialogue](#6)](https://github.com/UQdeco2800/2022-studio-2/issues/6)

Make the Dialogue box and design the style and appearance of the dialog box. Dialogue will include rough drafts, iterations and final design. This task ticket will be a design-based focus on the Dialogue. The Dialogue box appears when the player interacts with the NPC.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Rough Sketch of Animal NPC(Aug 18)
- [x]  First Iteration of Pixel Model (Aug 21)
- [x] The basic design of the dialog box (Aug 23)
- [x] First time Iteration of dialog box(Aug 24)
- [x] Second iterations of dialog box(Aug 25)
- [x] Complete base dialogue coding(Aug 26)
- [x] Testing and debug((Aug 27)

# **Documentation**
- [NPCs + Dialogue](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs)
 
# **Member**
- Zhihao Zhang(@EverittZ )
