### ISSUE TITLE
<Task> Dodge/Dash Mechanic Implementation

### ISSUE THREAD

**Issue by kurt-553** [UQdeco2800/2022-studio-2#50]
# **Description**
**Task:** [Dodge/Dash Mechanic Implementation](#).
**Feature:** [Skills](#18)

The dodge/dash mechanic will be implemented in code, allowing player to dash to speed up movement or avoid enemy attacks. This will involve directional movement, as well as a period of invulnerability during the movement. 
 
# **Dependencies**
- [ ] Player character sprite 
- [ ] Player character movement physics
- [ ] Directional Controls
- [ ] Cooldown Implementation for short cooldown after roll
- [ ] Considerations for short movement speed increase after roll 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement Key Press Interrupt (Aug. 22)
- [ ] Create Movement Speed Increase (Aug. 22)
- [ ] Create Unit Tests (Aug. 22)
- [ ] Create Directional Dodge/Dash (Aug. 28)
- [ ] Create Invulnerability Period During Dash (Aug. 28)
- [ ] Update Unit Tests to Include Direction and Invulnerability (Aug. 30)
- [ ] Documentation of Completed Dash/Dodge on Wiki (Aug. 30)
 
**Completion Deadline:** Aug. 30

# **Documentation**
- [Dodge/Dash Mechanic](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Kurt Lucas (kurt-553) (Kurt Lucas)
