### ISSUE TITLE
Create buffs/ debuffs icons

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#51]
# **Description**
**Task:** Create Buffs & Debuff icons for players + User testing
**Feature:** Combat Items #7 

The goal of this ticket is to create icons for the buffs and debuffs to be collected by the player on the game. These buffs and debuffs only apply to the weapon class or the combat items and should be created to support the implementation of the buffs/ debuffs under #35. After initial user research conducted in #63, the task at hand is to sketch out several ideas of buff/debuff icons according to a list pre-generated via the combat item feature ticket #7.  Icons should be made using a 32 x 32-pixel size ratio to adhere to the player class icon. After sketching, icons should then be translated into a graphical design in drawing ready to be used by the programmers within #35.

Buffs to be created for sprint one include:
* Attack Damage
* Attack Speed
* Poison (Food Poisoning/ Toxic Burritos)
* Fire (Peri Peri Sauce/ Chili)

Debuff icons to be created:
* Attack Damage
* Attack Speed
* Poison
* Fire

Furthermore, any buffs/ debuffs will need to be provided with stats consisting of weight increase/decrease, damage increase/decrease, cooldown reduction/ increment, area of effect reduction/ increment, and a duration increase/decrease. 
These items will then later be used in #35.

## **Example**
Below are some inspirations utilised for the buffs/ debuffs icons.
![image](https://user-images.githubusercontent.com/109809229/184785580-b47abd9a-1627-4d53-989e-83e1520c8f0b.png)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Sketches Completed (Aug. 22)
- [x] Graphical Representations Completed (Aug. 24))
- [x] Handing over of visual artifacts to programmers (Aug. 24)
 
**Completion Deadline:** Aug. 24

# **Documentation**
- [Buffs and Debuff Graphics](../wiki/Combat-Items)
 
# **Member**
- Caleb Ang (PurrplePandaa) (Caleb Ang)
- Nisha Vashist (@NishaVashist0) (Nisha Vashist)
