### ISSUE TITLE
<TASK> Dialogue and NPC code

### ISSUE THREAD

**Issue by viachen1** [UQdeco2800/2022-studio-2#52]
# **Description**
**Task:** [Creating base code for dialogue and NPC](#7).
**Feature:** [NPCs + Dialogue](#7)

Players can open the dialogue by clicking NPCs and get information or equipment from NPCs. 

# **Dependencies**
None

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Discuss with other teams related to NPCs features (Aug. 20)
- [ ] Step 2 Complete base NPC coding(Aug. 23)
- [ ] Step 3 Complete base dialogue coding(Aug. 26)
- [ ] Step 4 Testing and debug(Aug. 27)
 

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Pengxu (viachen1) (Pengxu Chen)

**Comment by viachen1** [comment]
done
