### ISSUE TITLE
<TASK> Creating Female Citizen NPC Design

### ISSUE THREAD

**Issue by Fayrain** [UQdeco2800/2022-studio-2#53]
# **Description**
**Task:** [Making of Female Citizen NPC](#3).
**Feature:** [NPCs + Dialogue](#6)

It involved creating Female Citizen NPC to get the understanding of a NPC design work for a game. It could be a starting point for various design for other female NPCs. Female Citizen NPC will be include rough drafts, first iteration and subsequent iterations of animated pixel art design. This task ticket will be a design-based focus on the Female Citizen NPC. The NPC will eventually be implemented and has dialogue interaction with the player.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Rough Drafts of Female NPC (Aug. 17)
- [x] Step 2: First Iteration of Pixel Art Model (Aug. 23)
- [x] Step 3: Second Iteration of Pixel Art Model + Idle Animation of NPC (Aug. 27)
- [x] Step 4: Final Iteration of Female Citizen NPC and Documentation (Aug. 29)
 
# **Documentation**
[NPCs + Dialogue](../wiki/NPCs + Dialogue) (Coming soon, will edit this section once the Wiki page got set up)
 
# **Member**
- Farahain Husain (@Fayrain) (Farah Husain)
