### ISSUE TITLE
Crafting Number Incrementation

### ISSUE THREAD

**Issue by abhat0** [UQdeco2800/2022-studio-2#54]
# **Description**
**Task:** [Putting a number next to each items to show how many were crafted.]
**Feature:** [Crafting System](#4)

The number depends on how many times that item has been crafted. Each time the craft button is clicked, the number next to the item will increment by 1. Items that have not yet been crafted will not have a number next to them.

## **Example**
The second row of items in this image is an example of what the numbers next to each item in the inventory may look like. However, currently, there is not a limit for the maximum amount of items that are able to be crafted.
https://res.cloudinary.com/featureupvote/image/upload/f_auto/swords_hux1yw.png

# **Dependencies**
- [ ] The visual design of the items in the inventory and the location of the number on the item needs to be created so that it can be placed in the correct position. 
- [ ] Requires there to be items in the inventory 
- [ ] Requires a working craft button
- [ ] Requires an element next to the item where the numbers 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Increment the number next to the item by 1 every time the craft button is clicked (Aug. 19)
- [ ] Decrement a number when an item is used (Aug. 20)
- [ ] When an item hasn’t been crafted, don’t show a number next to the item (Aug. 23)
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- Crafting Number Incrementation (../wiki/Crafting-Number-Incrementation)

# **Member**
- Aadya (@abhat0) (abhat0)
