### ISSUE TITLE
<Task>Dodging Speed Up

### ISSUE THREAD

**Issue by FutianJiang** [UQdeco2800/2022-studio-2#55]
# **Description**
**Task:** [Dodging Speed Up](#3).
**Feature:** [Skills](#2)

We will design ICONS for 'Speed Up' to provide sufficient feedback to the player, implement 'Speed Up' in the code, and ensure that players will not be harmed when 'Dodging Speed Up'.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] <Task> Dodge/Dash Mechanic Implementation 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create Movement Speed Increase (Aug. 22) 
- [ ] Create Unit Tests (Aug. 22)
 
**Completion Deadline:** Aug.22

# **Documentation**
- [Dodging Speed Up]
 
# **Member**
- Name (@FutianJiang) (Futian Jiang)
