### ISSUE TITLE
Design and Create Sword weapon

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#56]
# **Description**
**Task**: Create a graphical representation of a sword to be implemented into the codebase.
**Feature**: Combat Items https://github.com/UQdeco2800/2022-studio-2/issues/7

The task is to generate a graphical image for the sword; to be implemented under the weapon class task https://github.com/UQdeco2800/2022-studio-2/issues/34. Research will need to be conducted to suit the Greek Mythology theme this game is currently set within. Such information could take the form of choosing the colour scheme, size and weight of the sword to be implemented for the description of the item. From here, sword sketches will need to be ideated first to get a better understanding of what kind of sword should be implemented. Upon creation of all sketches, one (or a collation of multiple ideas) should be selected and implemented on a graphical level through pixelated art.
 
## **Example (optional)**
- Below are some inspirations and directions on potential sword options.
![image](https://user-images.githubusercontent.com/109946739/185034529-da892658-c70b-4a8a-8cc4-37ba9e49a979.png)
![image](https://user-images.githubusercontent.com/109946739/185034586-ff9ed53e-6160-4116-b68b-474fabf3e819.png)

# **Dependencies**
- [ ] Implement weapon GUI https://github.com/UQdeco2800/2022-studio-2/issues/36
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Research completed  (Aug. 18)
- [x] Sketches completed  (Aug. 21)
- [x] Graphical representation drawn (Aug. 22)
- [x] Graphic provided to team (Aug. 23)
- [x] Documentation of `Sword weapon` and stats updated on wiki (Aug. 23).
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- Combat Items ([...wiki/Combat-Items)
 
# **Member**
- Lachlan Benson (LachlanBenson)

**Comment by LachlanBenson** [comment]
Design and implementation completed
