### ISSUE TITLE
Determining how each potion will effect the player

### ISSUE THREAD

**Issue by jessfroio** [UQdeco2800/2022-studio-2#57]
# **Description**
**Task:** [Task Name](#3).
**Feature:** Potions #32 

This task is to determine what effect each potion will have on the player. For sprint 1, all effects on the player will be positive. This task-ticket is design focused. 

## **Example (optional)**

- speed potion: increases player speed
- health potion: restores player health
- strength potion: increases player damage output

# **Dependencies**

- [ ] Need to talk to player team about stats (max health, speed, etc.) to determine the increase for each potion #

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Brainstorm ideas of effects (Aug. 10)
- [ ] IFinalising effects for sprint 1 (Aug. 13)
- [ ] Consulting player team for stats (Aug. 18)
 
**Completion Deadline: 18 ** Aug. 

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
