### ISSUE TITLE
Use of the potions

### ISSUE THREAD

**Issue by hideonbush-crl** [UQdeco2800/2022-studio-2#59]
# **Description**
**Task:** [Use of the potions](#3).
**Feature:** [Potions #32](#2)

Characters using potions will gain different effects such as health regeneration, speed boosts and increased attack power. The character's values will change, permanently or for a certain period of time.
After use, the potion needs to be removed from the backpack.
 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ]Need to know the basic value changes of the character, Story and Player #5 (#5 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Determining the capacity of each potions (Aug. 19)
- [x] Make some change into the potions effect. (Aug. 20)
- [x] test (Aug. 23)
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Bokai (@hideonbush-crl )
