### ISSUE TITLE
[Feature] NPCs + Dialogue

### ISSUE THREAD

**Issue by MonitaMegaele** [UQdeco2800/2022-studio-2#6]
# Description
Implementing non-player characters (NPCs) into the game which allows the Player to interact with them. Dialogues will also be implemented into the game depending on the interaction by the Player 

## Features:

Non-playable characters:
- Their purpose
- The design of the NPC
- Their Dialogues
- Interactions with Player	

Dialogues:
- How it will be triggered
- UI/UX of dialogues
- Sub-Features:
- NPC Lore

_Consult with Team 6 ([Player + Story](https://github.com/UQdeco2800/2022-studio-2/issues/5)) NPC Story
Consult with Team 5 ([Map](https://github.com/UQdeco2800/2022-studio-2/issues/22)) NPC Locations
Consult with Team 4 ([Combat Items](https://github.com/UQdeco2800/2022-studio-2/issues/7)) and [Potions Team](https://github.com/UQdeco2800/2022-studio-2/issues/32) and [Crafting Team](https://github.com/UQdeco2800/2022-studio-2/issues/4)_ 

NPCs heavily rely on the story to create appropriate roles and a genuine storyline. This is where the consult on Team 6 comes into play. 

NPCs should have a certain location in the game where they are standing idle or walking around. This will involve consulting with Team 5 to check their Map regions. The NPCs should be tied to their geographic location (e.g. A blacksmith NPC should be in a blacksmith workshop.)

NPCs could potentially have a trade system and therefore the NPCs could potentially give the Player an item such as Combat Items, Crafting and Potions

# Documentation
Coming Soon :)

# Milestones
**Sprint 1：**

**Week 4 - 17/08 Wednesday**

- [x] Create a base NPC (Atlantis Citizen) + base Dialogue box 
- [x] Rough Idea of which NPCs we would like to have

**Week 5 - 24/08 Wednesday**

- [x] Consult with other teams to find out which NPCs should be made
- [x] Iterate through designing the base NPCs model
- [x] Ideate the NPCs going into the game

**Week 5 - 27/08 Saturday**

- [x] Dialogue to go with said NPCs are to be completed
- [x] Quality Check
- [x] User testing (due to sprint 1)

**Week 6 - 30/08 Tuesday**							

- [x] Second Iteration of NPCs 
- [x] NPC Lore
- [x] Second User testing

# Extras (Optional)

- Smaller, less important NPCs could be implemented:
- Easter Eggs possibly
- Different NPC dialogues

# Future Progress of NPCs

- Start of NPCs coding (Sprint 2)
- Start of Dialogue box code (Sprint 2)
- NPCs interaction with other NPCs (Possibly)
- 'Trade System' (Potential Currency Implementation)

# Team Members

- Megaele Muniappan (@MonitaMegaele)
- Hazeem bin Suffian (@uq-haze)
- Zhihao Zhang (@EverittZ)
- Nor Farahain Binti Husain (@Fayrain)
- Yongzhi ZHOU (@45229848)
- Pengxu Chen (@viachen1)

**Comment by uq-haze** [comment]
@notalie  @BozenX

**Comment by BozenX** [comment]
Looks good!
