### ISSUE TITLE
Potions in Backpack Inventory

### ISSUE THREAD

**Issue by cluanzon** [UQdeco2800/2022-studio-2#60]
# **Description**
**Task:** Putting Potions in Backpack Inventory .
**Feature:** [Potions](#32)

The purpose of this ticket is to implement the ability to have the potions in the inventory. At the start of the game, the player will be given 3 potion which can be used anytime during the game. These potions will be removed from the player's inventory after each usage. The three starting potions are listed below:
_NOTE: The specifics will be updated once information are released._ 

1. Health Potion
The health of the player will increase [x amount]. If the player has full health, the potion will not be used. Instead, an error feedback message will appear: "Current player is in full health. Please try again later". However, if the player has damaged health, it will increase [x amount] but it won't extend the health bar if there are excess amount from the potion. 

2. Speed/Movement Potion
The speed potion increases the player's speed [x amount] for [y amount] of seconds. After the speed potion is drank, it will disappear from the inventory and the countdown will begin. Once the timer is up, the player will go back to its original speed time. 

3. Attack Damage Potion (ADP)
The attack damage potion (ADP) increases the current damage amount of the player by [x amount]. Same as the speed potion, the ADP will also have a cool down [y amount]. Additionally, if the player currently has weapons equiped, it will increase the attack damage in addition to the weapons. 

 
## **Example (optional)**
When the player opens the inventory folder, they will see the 3 potions listed above. 

# **Dependencies**
- [Inventory - Implement Inventory Logic](#12) 
- [Inventory - Design for Inventory](#11)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Talk to the Inventory Team (Aug. 19)
- [ ] Create the Assets (Aug. 20)
- [ ] Give the Assets to the Inventory Team (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
_To Be Updated..._
 
# **Member**
_To Be Updated..._
