### ISSUE TITLE
Trident weapon implementation

### ISSUE THREAD

**Issue by NishaVashist0** [UQdeco2800/2022-studio-2#62]
**Task:** Create a graphical representation of a trident to be implemented into the codebase
**Feature:** Combat items #7 

The task is about ideating and designing a graphical image for the trident weapon item implemented under the trident class implementation under task #34 . The overall 'look' of the weapon will depend on research that needs to be conducted to suit the Greek Mythology theme this game is currently set within. Such research could impact the design decision for the colour scheme, size, or even weight of the trident to be implemented for the item's description. Once such research is conducted, the initial ideation of the weapon will be created through sketches so that I can better understand what kind of trident will be implemented. Upon creation of all drawings, one (or a collation of multiple ideas) should be selected and implemented on a graphical level through pixelated art.
 
## **Example (optional)**
The weapons will be 'Level 1' or basic, the weakest weapons in the evolution tree, dealing less damage.

<img width="263" alt="Screen Shot 2022-08-20 at 8 22 15 pm" src="https://user-images.githubusercontent.com/109975114/185741676-a557f605-995e-4fbf-b4d6-88c6177d8f9c.png">
reference: https://www.etsy.com/au/listing/1072518281/gungnir-polearm-spear-trident-dragoon

<img width="116" alt="Screen Shot 2022-08-20 at 8 23 22 pm" src="https://user-images.githubusercontent.com/109975114/185741735-b8ac3e59-559b-4359-b500-0cc266439e40.png">
reference: https://www.alamy.com/stock-photo/weapon-trident.html

# **Dependencies**
- Implement weapon GUI within game #36 

 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Research into Greek mythology (Aug. 15)
- [x] Sketches of the different variations of the trident completed (Aug. 18)
- [x] Graphical representation created (Aug. 21)
- [x] Graphic provided to the team (Aug. 23)
- [x] Documentation of Sword weapon and stats updated on the wiki (Aug. 23).

**Completion Deadline:** Aug. 24

# **Documentation**
- Combat Items ([...wiki/Combat-Items)
 
# **Member**
- Nisha Vashist (@NishaVashist0) (Nisha Vashist)
