### ISSUE TITLE
User testing for debuff/buff design implementation  

### ISSUE THREAD

**Issue by NishaVashist0** [UQdeco2800/2022-studio-2#63]
# **Description**
**Task:** User testing for debuff/buff design implementation  
**Feature:** Combat items #7 

The task is about choosing, creating a guideline and conducting user testing on all the debuff/buff designed within the team.  The rationale behind this task is to get user expectations on the visualisation of the debuff/buff to fit the game theme of Atlantis.  

# **Dependencies**

-  Initial research into the game themes #62 #56 #30 #37 
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] - Choose an appropriate user testing method (Aug 15)
- [x] - Create user testing guidelines (Aug 17)
- [x] - Conduct user testing (Aug 20)
- [x] - Analysis result (Aug 21) 
- [x] - Integrate the feedback into #51  (Aug 21)

**Completion Deadline:** Aug 21

# **Documentation**
- [Buffs and Debuff Graphics](../wiki/Combat-Items)

 
# **Member**
- Nisha Vashist (@NishaVashist0 ) (Nisha Vashist)
