### ISSUE TITLE
<Task> Camera moves along with the player

### ISSUE THREAD

**Issue by rlybgithub** [UQdeco2800/2022-studio-2#64]
# **Description**
**Task:** Camera moves along with the player
**Feature:** [Map + Environment Interaction #22

The mechanism which able to bind the camera with the player. This feature will allow the player to explore a larger map and the camera with move along with the player instead of on the fixed screen.
 
# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Explore the game engine (Aug. 20)
- [x] Research on the class related to the camera(Aug. 21)
- [x] Implement the code (Aug. 23)
- [x] Visually check the function (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Yibo Liu (@rlybgithub )
