### ISSUE TITLE
<Task> Minimap Implementation

### ISSUE THREAD

**Issue by otili9890** [UQdeco2800/2022-studio-2#68]
# **Description**
**Task:** [Minimap Implementation] (#68).
**Feature:** [Map + Environment Interaction] (#22)

This task will allow the player to press a button (M) and have a minimap window open with an image of the users current map. The player will also be able to press the same button (M) to close the window. 
 
## **Example**
- **Part**: Player presses M to help find out where to go. They press M again to close the minimap. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Review code for creating a window (Sep. 26)
- [x] Implement minimap creation (Oct. 1)
- [x] Implement minimap removal (Oct. 3)
 
**Completion Deadline:** Aug. 30

# **Documentation**
- [Minimap Wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/MiniMap)
- [Minimap Commit](https://github.com/UQdeco2800/2022-studio-2/commit/fe1a83dc578c58e85aafe979f979ed149f4a30b4)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Otis Carmichael (@otili9890) (@Otis Carmichael)
