### ISSUE TITLE
<Task> Effect of the potions on players

### ISSUE THREAD

**Issue by hideonbush-crl** [UQdeco2800/2022-studio-2#69]
# **Description**
**Task:** [Effect of the potions](#3).
**Feature:** [Potions #32](#2)

The potion will act on the character first to help boost their attributes and act as a support item to give the player a better gaming experience. The potion should have a limited boost to attributes and we need to specify the ability of the potion based on the value of the basic attributes set for the player by the player group. (For example, if a player has 100 for health in total, the effect of a health potion will be to restore up to 100 health.)
 
## **Example**
- **Health Potions**: if a player has 100 for health in total, the effect of a health potion will be to restore up to 100 health.
- **Speed Potions**: The speed of the player after drinking the potion will be reasonable, not too fast and not too fast. A certain duration of time is required. Set according to the player's values..

# **Dependencies**
We need to set the effects for our potions based on the values set by the player group for the player. Limit the change in values to a certain percentage. Data from the enemy group is also needed to be able to better determine the effect that should be achieved by the strength potion and the speed potion.

- [x] Create basic enemy that appears in game. #61
- [x] Player Modification Framework #23
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Confirm values with the player group and determine settings for health potions etc. (Aug. 25)
- [x] Confirming values with the enemy group and determining settings for speed potions etc. (Aug. 25)
- [x] Create tables to consolidate data (Aug. 27)
- [x] Make changes to the player. (Aug. 27)
 
**Completion Deadline:** Aug. 27

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Bokai (@hideonbush-crl )
