### ISSUE TITLE
[FEATURE] Combat Items

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#7]
### **UPDATE 22/08/22:** 

After commencement of the 1st sprint, a change was made to the theme of the game; which required a re-consideration of how our team would implement weaponry.

Upon liaising with **_Team 6 - story and player team_**, it was determined that because the change was made at little notice in the sprint, that we would continue with our original plan for Combat Items, with the expectation that our original designs will be utilised later on in the game, rather than at level 1.

The weapons we intended to use as Lvl1 weapons will instead be used as Lvl2/3 weapons.

In Sprint 2, the Combat Items team will design the Lvl1 weapons which will be inspired by the main _plumber_ character.

# **Description**
In the current state of the game no weapons and buffs/debuffs exist for players, enemies and the game environment. As a team we need to design and implement the basic functionality of weapons and buffs/debuffs for players, enemies and the game environment. 

For sprint one we aim to design the basic level of weapons and it buffs/debuffs for a player and its enemies. For the environment we aim for the weapon and its buff/debuff to be able to be dropped and picked up. This feature will involve multiple combat items for the player, NPCs and the environment. 

Combat items will consist of but will not be limited to weapons, buffs/debuffs, relics and runes. These items are essential and will play a role in determining whether the player wins or loses and contribute to game progression. Weapons should be able to be picked up by players and dropped by players. 

Should players wish to be more creative, they are able to craft their own combat items provided they have enough available resources (collaboration with crafting team). Buffs/debuffs, relics and runes will also be added as they provide necessary variety to the game. This makes the game more versatile and encourages continuous learning in an engaging and interactive manner.

## Sub Features
Weapons
- Melee weapons, each weapon will have different stats like damage, cooldown and weight.
  - Basic Dagger
  - Basic Trident
  - Basic Sword
- These weapons are ‘Level 1’ or basic, which are the weakest weapons in the evolution tree; dealing less damage.
- Enemies weapon design will be created in collaboration with the enemies team 
- Weapons can be dropped and picked up in the environment. 
- Buffs (icons and animation) to 
  - Additional strength to the weapon 
  - Attack Speed
  - Damage inflicted on player over time 
- Debuffs
  - Slowed attacks
  - Reduced Damage

## **Examples**
- Player wishes to interact with a sword that has been dropped onto the ground. As they hover over the item, an active description of the sword appears showing a brief description of it. Within the description, it displays how the sword should be utilised as well as the status of it specifically regarding any DPS and any buffs that has applied to that weapon. Lastly, there will be a brief description of the background story of the combat item for further immersion of the game environment.

# **Dependencies**

In the creation of our features, we will need to consult with the following teams/classes:

- **Enemies**
  - Discuss with enemy team whether they will have a drop combat item on death effect or if they will even include an inventory for the enemies; consult with design of enemies
- **Player**
  - Interaction with player class will be required as we will need to consider when/if curses are created
- **Map/ Environment** 
  - Items spawning into the game will require our design

Our class will most likely rely on classes such as the enemy class since enemies have the capability of dropping items on death. As for the map and environment dependencies, it will impact the way ranged items are being utilised within our class. 

**Note:** The design needs for enemies and players there needs to be significant differentiation between their items. 

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.

- [x] Designs completed for all 3 weapons **(Due: 21st of August)**
- [x] Designs completed for buffs and debuffs **(Due: 23rd of August)**
- [x] Design completed for aurora around weapon **(Due: 26th August)**
- [x] Create weapon class and appropriate subclasses **(Due: 23rd of August)**
- [x] Create aura (buffs, debuffs, curses) class with the appropriate subclasses **(Due: 17th of August)**
- [x] Integrate graphics/GUI **(Due: 27th of August)**
- [x] Successful integration of graphics into the game  **(Due: 26th of August)**
- [x] Successful push of compilation of local code into main branch repository **(Due: Sun 27th August)**

**Completion Deadline:** Aug. 30

# **Extras (optional)**
Extra components that you may implement if you get the time
- ~~Animations~~
- ~~Curses (A buff plus debuff) -> inside Alchemist/potion?~~
- ~~Weapon Skins (flashy animations/ effects - probably sprint 2 or 3 item?)~~

# **Documentation**
### **UPDATE 22/08/22:** 

After commencement of the 1st sprint, a change was made to the theme of the game; which required a re-consideration of how our team would implement weaponry.

Upon liaising with **_Team 6 - story and player team_**, it was determined that because the change was made at little notice in the sprint, that we would continue with our original plan for Combat Items, with the expectation that our original designs will be utilised later on in the game, rather than at level 1.

The weapons we intended to use as Lvl1 weapons will instead be used as Lvl2/3 weapons.

In Sprint 2, the Combat Items team will design the Lvl1 weapons which will be inspired by the main _plumber_ character.

# **Description**
In the current state of the game no weapons and buffs/debuffs exist for players, enemies and the game environment. As a team we need to design and implement the basic functionality of weapons and buffs/debuffs for players, enemies and the game environment. 

For sprint one we aim to design the basic level of weapons and it buffs/debuffs for a player and its enemies. For the environment we aim for the weapon and its buff/debuff to be able to be dropped and picked up. This feature will involve multiple combat items for the player, NPCs and the environment. 

Combat items will consist of but will not be limited to weapons, buffs/debuffs, relics and runes. These items are essential and will play a role in determining whether the player wins or loses and contribute to game progression. Weapons should be able to be picked up by players and dropped by players. 

Should players wish to be more creative, they are able to craft their own combat items provided they have enough available resources (collaboration with crafting team). Buffs/debuffs, relics and runes will also be added as they provide necessary variety to the game. This makes the game more versatile and encourages continuous learning in an engaging and interactive manner.

## Sub Features
Weapons
- Melee weapons, each weapon will have different stats like damage, cooldown and weight.
  - Basic Dagger
  - Basic Trident
  - Basic Sword
- These weapons are ‘Level 1’ or basic, which are the weakest weapons in the evolution tree; dealing less damage.
- Enemies weapon design will be created in collaboration with the enemies team 
- Weapons can be dropped and picked up in the environment. 
- Buffs (icons and animation) to 
  - Additional strength to the weapon 
  - Attack Speed
  - Damage inflicted on player over time 
- Debuffs
  - Slowed attacks
  - Reduced Damage

## **Examples**
- Player wishes to interact with a sword that has been dropped onto the ground. As they hover over the item, an active description of the sword appears showing a brief description of it. Within the description, it displays how the sword should be utilised as well as the status of it specifically regarding any DPS and any buffs that has applied to that weapon. Lastly, there will be a brief description of the background story of the combat item for further immersion of the game environment.

# **Dependencies**

In the creation of our features, we will need to consult with the following teams/classes:

- **Enemies**
  - Discuss with enemy team whether they will have a drop combat item on death effect or if they will even include an inventory for the enemies; consult with design of enemies
- **Player**
  - Interaction with player class will be required as we will need to consider when/if curses are created
- **Map/ Environment** 
  - Items spawning into the game will require our design

Our class will most likely rely on classes such as the enemy class since enemies have the capability of dropping items on death. As for the map and environment dependencies, it will impact the way ranged items are being utilised within our class. 

**Note:** The design needs for enemies and players there needs to be significant differentiation between their items. 

# **Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.

- [x] Designs completed for all 3 weapons **(Due: 21st of August)**
- [x] Designs completed for buffs and debuffs **(Due: 23rd of August)**
- [x] Design completed for aurora around weapon **(Due: 26th August)**
- [x] Create weapon class and appropriate subclasses **(Due: 23rd of August)**
- [x] Create aura (buffs, debuffs, curses) class with the appropriate subclasses **(Due: 17th of August)**
- [x] Integrate graphics/GUI **(Due: 27th of August)**
- [x] Successful integration of graphics into the game  **(Due: 26th of August)**
- [x] Successful push of compilation of local code into main branch repository **(Due: Sun 27th August)**

**Completion Deadline:** Aug. 30

# **Extras (optional)**
Extra components that you may implement if you get the time
- ~~[ ] Animations~~
- ~~[ ] Curses (A buff plus debuff) -> inside Alchemist/potion?~~
- ~~[ ] Weapon Skins (flashy animations/ effects - probably sprint 2 or 3 item?)~~

# **Documentation**
[Click Me](https://github.com/UQdeco2800/2022-studio-2/wiki/Combat-Items)

# **Members**
Lachlan Benson, @LachlanBenson
Caleb Ang, @PurrplePandaa
Nisha Vashist, @NishaVashist0
Madi Feddema, @madifeddema
Eugene Chong, @eugene2341

**Comment by LachlanBenson** [comment]
@BozenX @notalie

**Comment by BozenX** [comment]
looks good!
