### ISSUE TITLE
<Task> User test of potions

### ISSUE THREAD

**Issue by hideonbush-crl** [UQdeco2800/2022-studio-2#71]
# **Description**
**Task:** [User test of potions](#3).
**Feature:** [Potions #32](#2)

Each of us successfully designed a potion, and to help us confirm that our designs matched the theme and user preferences, we designed a user test to allow users to choose their preferred potion design for the final potion version.

 Method1:Questionnaires, we will design questions for each potion in the questionnaire to let people know what aspects we want to get their opinion on.
Method2: Interview. Interviews are a great way to get direct feedback from users. Through a relaxed chat environment, users are more likely to give design suggestions and help us optimise our drawings.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Environment Design Style #44 (The design of the potion should be in keeping with the style of the environment)
- [x] Player Backstory #28 (Potions are designed to fit the player's backstory)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Designing the questionnaire. (Aug. 25)
- [x] Designing interview questions. (Aug. 25)
- [x] Conducting user tests. (Aug. 27)
- [x] Integrating data.(Aug. 27)
 
**Completion Deadline:** Aug. 27

 
# **Documentation**
- [Survey of potion and effects](https://forms.gle/mymzjZeBgkTNFsc47)
- [Survey of overall integration into Greek theme](https://forms.gle/a3bVJgM8MZcPZZrr8)
- ...
 
# **Member**
- Bokai (@hideonbush-crl ) 
- Chai (@cluanzon)
- Emily (@e-southgate)
