### ISSUE TITLE
<Task> Visual test plan for Map + Environmental Components

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#73]
# **Description**
**Task:** [Visual test plan for Map and Environmental Components](https://github.com/UQdeco2800/2022-studio-2/issues/22).

Visual Testing Plan is to be implemented when starting the game after building it with each visual element inserted, looking for various components that are meant to be displayed on the map. 

## **Example (optional)**
- **Grass**: When scanning the background of the map, the main, reoccuring tile should be grass, which should cover most of the said map and if there are any empty tiles, debugging as to why empty tiles are occuring is required.
- **Trees**: Players should be able to run around trees but not through them, which is where physics and collosion comes in and testing entails running into them and confirming not being able to run through it.

# **Dependencies**

- [x] Static Environment Components (#45)
- [x] Create Interactive Environmental Components (#43)
- [x] Map Creation (#40)
- [x] Map + Environment Interaction (#22)

# **Milestones**

- [x] Load Entity onto Map (Aug. 20)
- [x] Interact with Entities on the Map (Aug. 23)
- [x] Change Map dimensions and test placing components(Aug. 26)
- [x] Try editing map border color and test all components placements and interaction on map(Aug. 29)
 
**Completion Deadline:** Aug. 29

# **Documentation**
- Map Components
  * [Map Layout Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-Layout-Design)

- Environmental Components
  * [Tree](https://github.com/UQdeco2800/2022-studio-2/wiki/Tree-Component)
  * [Floor Tiles](https://github.com/UQdeco2800/2022-studio-2/wiki/Tile-Components)
  * [Columns](https://github.com/UQdeco2800/2022-studio-2/wiki/Columns)
  * [Water](https://github.com/UQdeco2800/2022-studio-2/wiki/Water)
  * [Rock](https://github.com/UQdeco2800/2022-studio-2/wiki/Rock)
  * [Walls](https://github.com/UQdeco2800/2022-studio-2/wiki/Walls-Component)

- Map Code System
  * [Code Logic](https://github.com/UQdeco2800/2022-studio-2/wiki/Map-System-Code-Implementation)
 
# **Members**
- Otis Carmichael (@otili9890) 
- Abigail Borromeo (@Abi-B-28)
- Yibo Liu (@rlybgithub)
- Ishaan Ranade (@IshaanM8)
- Lonni Miller-Metzner (@lonnimm)
