### ISSUE TITLE
[Feature] Armour 

### ISSUE THREAD

**Issue by 0ceanfloor** [UQdeco2800/2022-studio-2#75]
# **Description**
This feature aims to add armour into the game increasing the strength of the player with stat boosts and unique effects. Armour will add extra depth to game.

# **Dependencies**
This feature is dependent on inventory.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement armour equipment
- [x] Create 3 armour sets
- [x] Armour equipment slot in inventory
- [x] Implement armour stat or effect buffs

**Completion Deadline:** sprint 2

# **Documentation**
- https://github.com/UQdeco2800/2022-studio-2/wiki/Inventory

# **Members**
- 0ceanfloor
