### ISSUE TITLE
[Feature] Enemies (Sprint 2)

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#76]
# **Description**
We plan to continue adding further enemies to the game in order to enhance gameplay. In this sprint, we aim to add ranged level 2 enemies (flying poops) and the level 1 boss (super strong ultimate gym bro). Also, we aim to finish adding animations for the enemies from Sprint 1 and making sure they drop items.

## SubFeature/component
Adding in animations for enemies from sprint 1
Creating the flying enemy poops for level 2
Creating the super strong boss for level 1

# **Dependencies**
- [x] Enemies - Sprint 1 (#3)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Add dumbbell to animations for Atlantis gym bro from sprint 1
- [x] Add in animations to the game for Atlantis gym bro from sprint 1
- [x] Design the base design for the flying enemy poops
- [x] Create the animation for the flying enemy poops
- [x] Code the ranged movement and attack for the flying enemy poops
- [x] Design the base design for the boss from level 1
- [x] Design the animation for the boss from level 1
- [x] Code the movement and attack for the boss

**Completion Deadline:** 12 September

# **Extras (optional)**
- [ ] Add enemy health bars
- [ ] Create UML Diagram to represent enemy classes

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
- [Enemy Weapons](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemy-Weapons)

# **Members**
- Yi Zhou (@MandalorianForce) (Yiiiiiii)
- Caitlenn Alsop (@c-alsop) (slack: Caitlenn Alsop)
- Wenfang Hao (@wenfangH) (slack: Wenfang Hao)

**Comment by LachlanBenson** [comment]
Hey guys, just letting you know we made a slight modfication to NPCFactory.createGymBro()

```
.addComponent(new HitboxComponent())
.addComponent(new ColliderCOmponent())
```
Is unnecessary because they are already used earlier in the code

This was causing errors to show up in the log. We have now removed these two lines of code to stop the errors from showing in the log.

![image](https://user-images.githubusercontent.com/109946739/189251037-f363c18c-8c1b-4672-91cf-2f238fc41e0c.png)

**Comment by eugene2341** [comment]
For the sake of providing evidence of collaboration, few days ago I've modified some code in Entity.dispose() to check if the entity has animation, and if it does, it does not dispose of that animation when Entity.dispose() is called as other entities that uses the same TextureAtlas will have their animations discarded too.
![image](https://user-images.githubusercontent.com/41180628/189519212-6d21e07c-add6-44e2-8ab9-68a848620513.png)
