### ISSUE TITLE
Create the animation for the flying enemy poops

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#81]
# **Description**
**Feature:** [Enemies (Sprint 2)](#76)

Create the animation for the flying enemy poops.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create animation for the flying enemy poops
- [x] Put animation in game.
- [x] User test animation
- [x] Document the animation in the wiki
 
**Completion Deadline:** 12 September

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
