### ISSUE TITLE
[Task] Pause Screen

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#83]
# **Pause Screen**
**Task:** [Pause Screen](#83).
**Feature:** [Refinement of Crafting Menu and Addtional Features](#82)

Design and animate a general UI for the pause screen.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Sept 7th)
- [x] User Testing (Sept 11th)
- [x] Updating Design Based on Feedback (Sept 12th)
- [x] Implementing Animations (Sept 13th)
- [x] Final Iteration/Implementation (Sept 14th)
 
**Completion Deadline:** Sept 14th
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
 
# **Member**
- Enoe (Jolo) Gapusan (@jgapusan)
