### ISSUE TITLE
[Feature] Game Main Menu Soundtrack Design

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2022-studio-2#84]
# **Description**
Music can add more interest to the game. Team2 will be responsible for the music design of the entire menu screen.

The music designs including: 
Sound effect for interacting with buttons.(Button part)
Soundtracks for menu screens.(Background part)

Style of music :Chip music or 8-bit music.

## SubFeature/component (optional)

Sound effect for interacting with buttons
Soundtracks for menu screens

# **Dependencies**
According to the meaning of these buttons.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Desgin Button sound effects(Sept. 3)
- [x] Interacting with buttons sound effects(Sept. 5)
- [x] Desgin menu background soundtrack.(Sept. 8)
- [x] Interacting with menu background soundtrack(Sept. 10)
- [x] User test (Sept. 12)

**Completion Deadline:** Sept. 12

# **Members**
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
