### ISSUE TITLE
[Task] Old NPC Iterative Update

### ISSUE THREAD

**Issue by MonitaMegaele** [UQdeco2800/2022-studio-2#85]
# **Description**
**Task:** Iteration of Old NPC design (#41 , #53 , #39 ).
**Feature:** NPC + Dialogue (#92)

Iteration of the NPC design includes `updating the old NPCs` to be in it's final design stages, ready to be released into the project game. Adding `consistency to all NPC designs`, Adding the `animations` of the NPC and creating a `short line for an interaction`. Result of this task will include **interact able updated NPCs from previous sprint**.
 
## **Example**
**Child NPC Update**: 

- Design will be updated and consistent with other old NPCs
- Animation Added into game
- Small Message when interaction happens

# **Dependencies**
None all the previous NPCs have been completed (#41 , #53 , #39 ).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Old NPC Design Update (Sep. 4)
- [x] NPC Animation (Sep. 9)
- [x] NPC Quote (Sep. 10)
- [x] Implementation & Quality Check (Sep. 12)
 
# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs) 
- Code Yet to be Implemented
 
# **Member**
- Monita (@MonitaMegaele) (Monita Muniappan)
