### ISSUE TITLE
[Task] Crafting Menu Update

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#86]
# **Redesigning Crafting Menu**
**Task:** [Crafting Menu Update](#86 ).
**Feature:** [Refinement of Crafting Menu and Additional Features](#82)

Redesign the crafting menu, and implementing another 'dictionary' tab.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Sept 4th)
- [x] User Testing (Sept 5th)
- [x] Updating Design Based on Feedback (Sept 6th)
- [x] Final Iteration/Implementation (Sept 7th)
 
**Completion Deadline:** Sept 7th
 
# **Documentation**
- [Crafting UI Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-UI-Visual-Assets-Design#sprint-two-1)
 
# **Member**
- Emily Southgate (@emily.southgate)
- Enoe (Jolo) Gapusan (@jgapusan)

**Comment by jgapusan** [comment]
@PurrplePandaa can you please send thru the pixil files for the weapons so i can add them to the crafting menu :DD

**Comment by PurrplePandaa** [comment]
@jgapusan I sure can! Please find the attached weapon files in the zip. I haven't managed to get one weapon which consists of the PVC Pipe which is meant to be for the level one map. 
[Weapons.zip](https://github.com/UQdeco2800/2022-studio-2/files/9536446/Weapons.zip)

**Comment by PurrplePandaa** [comment]
Btw @jgapusan tell me if I need to edit any of the files for the crafting display/ menu update.

**Comment by jgapusan** [comment]
@PurrplePandaa in terms of sizing i did change some stuff since the size of all the weapons weren't consistent ;-; - which makes sense for stuff like daggers but for the purpose of displaying in the menu i made them a bit bigger, just wanna get your okay on it

<img width="282" alt="Screen Shot 2022-09-11 at 4 12 59 pm" src="https://user-images.githubusercontent.com/110016922/189514935-ee4fb9d0-bc8c-41e4-8e87-c943908acdd3.png">

<img width="662" alt="Screen Shot 2022-09-11 at 4 13 11 pm" src="https://user-images.githubusercontent.com/110016922/189514941-0fc39f68-e928-4abe-b8e0-21afc64d8832.png">

<img width="146" alt="Screen Shot 2022-09-11 at 4 13 37 pm" src="https://user-images.githubusercontent.com/110016922/189514947-608397d3-6525-4250-ba05-161ed27f8151.png">

**Comment by jgapusan** [comment]
@PurrplePandaa also any update on your pipe pixil file ? need it asap plz :D

**Comment by PurrplePandaa** [comment]
Oh yeah no, those images loook HEEEEEEEEELAAA sick. I'm trying to get @NishaVashist0 to provide you with the pipe file. Let me check whether she's got it on a our google drive file. She must've forgotten.  I think the only comment that I have is that some of the weapons look a little bit distorted? But i think that's because you've enlarged the frames of the canvas xD hahaha @jgapusan

**Comment by jgapusan** [comment]
@PurrplePandaa nah i did that draggy thing that like extends it but shouldn't affect the canvas :0 i do agree it does look more pixelated tho i'll look into fixing that before this sprint ends

**Comment by PurrplePandaa** [comment]
[Weapons (2).zip](https://github.com/UQdeco2800/2022-studio-2/files/9541897/Weapons.2.zip)
Hey @jgapusan please see the above attached zip file containing ALL the weapons :). Apparently Nisha did put the pixil file inside the discord chat. It just must've gotten lost ahhaha.

**Comment by PurrplePandaa** [comment]
> 

It's not a super huge issue because in terms of your GUI when it's expanded out, the images are still relatively small in the crafting screen. Like it's big enough to see what the weapon is but it's not big enough for a very noticeable distortion..? Not sure if you know what I mean. I guess you'll really just have to look into seeing how distorted it is within the game and if it really affects the visibility and UI of it. Could also do some quick user testing on it if really neccessary.

**Comment by jgapusan** [comment]
@PurrplePandaa i can definitely have a look and make some adjustments shouldn't take too long --- but are the different sizes of weapons intentional ? in terms of displaying those assets in our crafting menu, they need to be as close to 32 x 32 as possible.

obviously it'd be nice to have all them of them already at that size, but alternatively 'crafting menu' versions might need to be made to fit in the menu --- is that ok ?

**Comment by PurrplePandaa** [comment]
Yeah @jgapusan, what I meant was like, if you need to enlarge the canvas to get a bigger image then feel free to do it. But yeah if you guys are happy to keep it in 32x32 then I'm cool with that too!
