### ISSUE TITLE
Integration with weapons 

### ISSUE THREAD

**Issue by rkoll55** [UQdeco2800/2022-studio-2#87]
# **Description**
**Task:** [Integrate Crafting System with weapons system](#99).
**Feature:** [Refinement of Crafting Menu and Additional Features](#82 )

This task will see us working with the weapons team to allow all weapons to be craftable via the crafting system. Each weapon will take a different combination of two distinct materials to craft. 
 
## Example 
- **Craft Dagger**: User can use gold and silver to craft a dagger. 

# **Dependencies**
This task ticket relies on the weapons team having a working system to generate weapons and setting crafting recipes for crafting system to use.  

- [x] Weapons System must finish crafting recipes

# **Milestones**
List of steps that need to be completed for this task.
- [x] Be able to get lists of all buildable weapons [Sep.5th]
- [x] Be able to display weapons in crafting menu [Sep.6th]
- [x] Craft all weapons in menu [Sep.10th]
 
**Completion Deadline:** Sep.14th
 
# **Documentation**
The implementation of the code used to make the weapons appear. 
https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-System-Code-Implementation#sprint-two-1
 
# **Member**
- Rohan @rkoll55  MainBreaker

**Comment by jgapusan** [comment]
hi

**Comment by jgapusan** [comment]
@eugene2341
