### ISSUE TITLE
[Task] Crafting Materials for Weapons

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#88]
# **Crafting Materials for Weapons**
**Task:** [Crafting Materials for Weapons](#83).
**Feature:** [Refinement of Crafting Menu and Additional Features](#82)

Design all crafting items that will be used in the crafting feature.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Sept 2nd)
- [x] High-Fidelity Design (Sept 4th)
- [x] User Testing (Sept 5th)
- [x] Updating Design Based on Feedback (Sept 6th)
- [x] Final Iteration/Implementation (Sept 7th)
 
**Completion Deadline:** Sept 7th
 
# **Documentation**
- [Weapons and their required materials](https://github.com/UQdeco2800/2022-studio-2/wiki/Combat-Items#weapons)
- [Crafting Visual Assets Design (Sprint 2)](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-Materials-Visual-Assets-Design#sprint-two)

# **Dependencies**
- [Combat Items Team](#106) - to begin designing and implementing the crafting items required for each combat weapon, the Combat Items Team needs to complete their designs of their weapons and finalise 'blueprints' of each weapon. 
 
# **Members**
- Enoe (Jolo) Gapusan (@jgapusan)
- Caleb Ang (@PurrplePandaa)

**Comment by jgapusan** [comment]
@PurrplePandaa hey does this look good to you ?

**Comment by PurrplePandaa** [comment]
Yeah the images look pretty decent from what I can see in your demo. Perhaps enlarge them a little bit to make it easier for the individuals to see?

**Comment by PurrplePandaa** [comment]
@jgapusan please see the attached files within discord for the rest of the weapons attached. Keen on looking at what weapons come up on the crafting system! Should be named "Weapons".

**Comment by jgapusan** [comment]
okok, i'll see if we can upscale the images a bit more for the ui - but if the actual images are good then we're sweet 👍

**Comment by PurrplePandaa** [comment]
Yeah nah, it looks good if it's bigger cuz then the details of the items will be enlarged and nicer to look at I wreckon. I hope it's not too much additional stuff you guys need to add in.

**Comment by PurrplePandaa** [comment]
Also, the excel doc has a list of all the items we have created and the materials that they require. If you guys can adhere to that, it would be splendid. Check the discord chat.

**Comment by jgapusan** [comment]
>  I hope it's not too much additional stuff you guys need to add in.

Updating this will require a rework of the crafting menu design, which we probably can't get around to this sprint, but i'll make it a top priority for next sprint !
