### ISSUE TITLE
Game Pausing Code Implementation

### ISSUE THREAD

**Issue by Rey-666** [UQdeco2800/2022-studio-2#89]
# **Description**
**Task:** Game pausing in gameplay. 
**Feature:** Crafting Refinement (#82)

The new task which I will be implementing is the "Game Pausing" feature. For this task, the player should successfully achieve the following  by the end of sprint 2:

- Be able to pause the game whenever a key is pressed. 
- Be able to pause the game whenever the crafting table is opened.
- Be able to pause the game whenever the player is interacting with another feature or the game environment.

The reason why this feature should be included in this game is because game pausing is one of the most fundamental features across game history. More importantly, a great once said, "Game pausing feature makes a single-player game dope." What is more, game pausing makes the game more coherent to play. For example, if the player is using the crafting table and the game is not paused, the player will easily get killed by enemies. 

The `game pausing class` should have a strong relationship with `MainGameActions` . 
 
## **Example**
<img width="495" alt="image" src="https://user-images.githubusercontent.com/109886027/187617571-d32b3d6c-bbe9-4021-bacd-d8dbceb84e66.png">

# **Dependencies**
The "Game Pausing" will be dependent on the overall gameplay, and the it will also count a bit on the functioning crafting UI and other interactable features.

- [x]  (#22 )
- [x]  (#82)
- [x]  (#77)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finish the overall game pausing using "escape" key. (Sept. 6)
- [x] Finish the game pausing feature for while player is interacting with other interactable features. (Sept. 9)
- [x] Finish the game pausing feature for while player is using crafting table. (Sept. 7)
- [x] Finish implementing poping up / disposing pause menu when pause/resume event is triggered. (Sept.10)

 
**Completion Deadline:** Sept. 12

 
# **Documentation**
[Game Pause Screen Code Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Game-Pause-Screen-Code-Implementation)

# **Member**
- Yingzheng Cai (@Rey-666 ) (Rey-666)
- Ly phung (@lyphng )
