### ISSUE TITLE
[Feature] Inventory

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#9]
# **Description**
**Feature:** [Inventory](#9 )

In sprint 1, We will implement an inventory function that allows users to close and open. And we will implement and quickbar in order to store basic items.

## SubFeature/component (optional)
-Menu that will allow users to interact with using specified keybind
-Logic of the inventory
-Graphic design of the inventory menu
-Graphic design of the item bar

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Initial graphic design of quickbar (Aug. 20)
- [x] Initial graphic design of inventory menu (Aug. 23)
- [x] Basic functionality of inventory (Open/Close)(Aug. 26)
- [x] Integration of UI and functionality of inventory(Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [x] Store items in the inventory
- [x] Quickbar for consuming certian items 
- [x] Logic of item consumption and equipment
- [x] Do items stack, and if what is a full stack

# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Inspirational Art**
-Pixel 2d
![image](https://user-images.githubusercontent.com/66679637/184525455-e5ab4011-2ab0-48b8-813e-58a0a7831c64.png)
-Nebulosa
![image](https://user-images.githubusercontent.com/66679637/184525527-bc3fcb34-9762-410f-8a7c-7a622a7f54fd.png)
-Minecraft
![image](https://user-images.githubusercontent.com/66679637/184525600-4b60e243-9380-449b-89c0-6d6484cf9c62.png)
-Resident Evil
![image](https://user-images.githubusercontent.com/66679637/184542971-e8650710-16af-49ab-a61f-0d0867fa224d.png)

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)
- Anders Jepsen (@0ceanfloor)
- Zhenyu Ding (@7ayuu) (Zhenyu Ding)
- Siu Ming Lam (@TimothyLam123)
- Lachlan McDonald (@Lukeyone)

**Comment by 7ayuu** [comment]
@notalie @BozenX Feature ticket confirmation

**Comment by BozenX** [comment]
looks good!
