### ISSUE TITLE
<Task>Crafting Refinement JUnit Test & Wiki

### ISSUE THREAD

**Issue by EverittZ** [UQdeco2800/2022-studio-2#90]
# **Description**
**Task:** [Crafting Refinement JUnit Test & Wiki](#90 ).
**Feature:** [Crafting Refinement](#82)

Write JUnit Test for the code in sprint 2. Complete all design and code Wiki pages for Sprint 2.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Pause screen that will appear when the user presses Esc(Design) Wiki (Sept. 4)
- [x] Main menu screen that will appear when you launch the game(Design) Wiki (Sept. 4)
- [x] Design of materials that will be used to craft the weapons Wiki (Sept. 4)
- [x] Refining current menu design (add tab that shows all crafting recipes) Wiki (Sept. 4)
- [x] Integration with weapons Code JUnit test (Sept 12)
- [x] Code Wiki (Sept 12)
- [x] Testing Plan(Sept 12)
- [x] UML (Sept 12)
 
# **Documentation**
[Crafting-System-Code-Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-System-Layout)
 
# **Member**
- Zhihao Zhang(@EverittZ )
