### ISSUE TITLE
Updating Crafting Table

### ISSUE THREAD

**Issue by e-southgate** [UQdeco2800/2022-studio-2#91]
# **Description**
**Task:** [Updating Crafting Table](#3).
**Feature:** [Crafting](#2)

Updating the design and implementing a new crafting table. Adding animation and sounds to crafting table.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] User Testing of Original Design (Sep 2)
- [ ] Using feedback to enahnce design of crafting table (Sep 4)
- [ ] Animation of opening and closing crafting table (Sep 11)
- [ ] Sound of crafting table being opened (Sep 12)
 
**Completion Deadline:** Sep. 14

 
# **Member**
- Emily Southgate (e-southgate)
