### ISSUE TITLE
[Feature] NPC + Dialogue

### ISSUE THREAD

**Issue by uq-haze** [UQdeco2800/2022-studio-2#92]
# **Description**
Implementing new NPCs for the second map into the game which the Player can interact with. A dialogue box will also be functional and it will function when the Player interacts with NPCs.

##  Features in this sprint:
NPCs:
- Plumber Friend
- Human Guard
- Friendly Creature
- Iterating sprint 1 NPCs

Dialogue:

- Small dialogue icon
- Interactive function of dialogue

# **Milestones**
Sprint 2:

Week 6 - 3/9 Saturday
- [x] Create Drafts for new NPCs 
- [x] A working Dialogue Interactive Function 

Week 7 - 7/9 Wednesday
- [x] First Iteration of NPCs
- [x] User Testing
- [x] NPC Relationships/Lore

Week 7 - 10/9 Saturday
- [x] Create Second Iterations 
- [x] Create Animations

**Completion Deadline:**  Sep 12

# **Documentation**
- [Main description of feature](../wiki/[Dialogue + NPC](https://github.com/UQdeco2800/2022-studio-2/wiki/Dialogue-&-NPCs))

# **Members**
- Megaele Muniappan (@MonitaMegaele)
- Hazeem bin Suffian (@uq-haze)
- Nor Farahain Binti Husain (@Fayrain)
- Pengxu Chen (@viachen1)
- Bokai Zhang (@hideonbush-crl)
