### ISSUE TITLE
<TASK> Creating Friendly Creature NPC Design

### ISSUE THREAD

**Issue by Fayrain** [UQdeco2800/2022-studio-2#93]
# **Description**
**Task:** [Creating Friendly Creature NPC Design](#93).
**Feature:** [NPC + Dialogue](#92)

It involved creating Friendly Creature NPC to be placed on the second map of the game. Friendly NPC will be include rough drafts, first iteration, subsequent iterations of pixel art design and then creation of animated idle sprite. This task ticket will be a design-based focus on the Friendly Creature NPC. The NPC will eventually be implemented and has dialogue interaction with the player.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Rough Drafts of Friendly Creature NPC (Sept. 3)
- [x] Step 2: First Iteration of Pixel Art Model (Sept. 6)
- [x] Step 3: Second Iteration of Pixel Art Model + Idle Animation of NPC (Aug. 10)
- [x] Step 4: Final retouch of Friendly Citizen NPC and Documentation (Aug. 12)

**Completion Deadline:** Aug. 12
 
# **Documentation**
- [Main description of feature](../wiki/NPC + Dialogue)

# **Member**
- Farahain Husain  (@Fayrain) (Farah Husain)
