### ISSUE TITLE
Code the ranged movement and attack for the flying enemy poops

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#94]
# **Description**
**Feature:** [Enemies (Sprint 2)](#76)

Code the ranged movement and attack for the flying enemy poops.
 
# **Milestones**
- [x] Decide how the enemy is going to move and attack
- [x] Need to code movement for the enemy (As it is ranged, it will probably try to stay a distance away from the player)
- [x] Code the projectiles to attack
- [x] JUnit test the code
- [x] Document the code in the wiki
 
**Completion Deadline:** 12 September

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)

# **Member**
- Bach Truong (@bach-truong ) (Bach Truong)
- Caitlenn Alsop (@c-alsop) (Caitlenn Alsop)
