### ISSUE TITLE
 Design the base design for the boss on level 1

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#95]
# **Description**
**Feature:** [Enemies (Sprint 2)](#76)

Design the base design for the boss on level 1
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a concept for the boss
- [x] Draw boss
- [x] User test boss design
- [x] Document the design in the wiki

**Completion Deadline:** 12 September
 
# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
