### ISSUE TITLE
Design the animation for the boss from level 1

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#96]
# **Description**
**Feature:** [Enemies (Sprint 2)](#76)

Design the animation for the boss from level 1.

# **Dependencies**
- [x] Will need base design completed before animating (#95)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide what the animation will be
- [x] Create animation
- [x] User test animation for boss
- [x] Document the animation in the wiki
 
**Completion Deadline:** 12 September

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
