### ISSUE TITLE
Code the movement and attack for the boss

### ISSUE THREAD

**Issue by c-alsop** [UQdeco2800/2022-studio-2#97]
# **Description**
**Feature:** [Enemies (Sprint 2)](#76)

Code the movement and attack for the boss on level 1. The boss will be Heracles and will be the strongest gym bro. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Need to decide how boss will move, if there are different phases etc.
- [x] User test proposed moveset
- [x] Code boss into game
- [x] Code discus throw
- [x] Code jump/smash attack
- [x] JUnit test code
- [x] Document the code in the wiki

**Completion Deadline:** 12 September

# **Documentation**
- [Enemies](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Caitlenn Alsop (@c-alsop) (Slack: Caitlenn Alsop)
- Yi Zhou (@MandalorianForce) (Slack: Yi Zhou)
