### ISSUE TITLE
<Task> Visual cues for different skills and conceive with the skill tree

### ISSUE THREAD

**Issue by AndySong-2324** [UQdeco2800/2022-studio-2#98]
# **Description**
**Task:** [Visual cues for different skills and conceive with the skill tree](#3).
**Feature:** [Skills](#2)

I will be working on the animation of the dodge/block/dash skill and the animation of the visual attack speed buff by pixel art. Besides, I will conceive the pixel skill tree and show it in a new window when clicking the skill tree icon.
 
# **Dependencies**

- [x] Develop overlaid animation component to player (Sep. 5)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalised the animation of blocking by pixel art (Sep. 3)
- [x] Conceive the architecture of the skill tree(provide the draft) (Sep. 5)
- [x] Finalised the animation of dodging by pixel art (Sep. 8)
- [x] Finalised the animation of ultimate skill(vendemaire) by pixel art (Sep. 9)
- [x] User testing of all the designs I have completed(Sep. 10)
- [x] Finalised the animation of projectiles by pixel art (Sep. 12)
- [x] Responsible for documenting the entire skill design section on the wiki(Sep.13)
 
**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Place the pixel skill tree in the new window by code implement (Sep.12)

# **Member**
- Zhuohang Song(AndySong-2324) (AndySong)
