### ISSUE TITLE
[Task] Integration of Inventory with Crafting System

### ISSUE THREAD

**Issue by lyphng** [UQdeco2800/2022-studio-2#99]
# **Description**
**Task:** [Integration of Inventory with Crafting System](#99).
**Feature:** [Refinement of Crafting Menu and Additional Features](#82)

This task is to integrate the player's inventory with the crafting system. This involves being able to read the availability of items and displaying them on the menu as well as automatically adding weapons that have been crafted into the inventory.

# **Dependencies**
- Player inventory logic needs to have been implemented (#12)
 
# **Milestones**
- [x] Reading the availability of items in the inventory (4th Sept)
- [x] Display them on the menu in the correct slots (4th Sept)
- [x] Adding weapons that have been crafted into the inventory (9th Sept)
 
**Completion Deadline:** 9th Sept
 
# **Documentation**
- [Crafting System Code Implementation](../wiki/Crafting-System-Code-Implementation)
 
# **Member**
- Ly Phung (@lyphng)
